### ISSUE TITLE
Soldier elf redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#101]
Soldier elf redone using militia elf and Eggplant sword ( https://opengameart.org/content/eggplant-sword )(kanaya2529)(CC0).
![rsolelf](https://user-images.githubusercontent.com/37004874/37876728-0a2d252e-301f-11e8-827a-3f46c710344b.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 34716c7
