### ISSUE TITLE
Commander elf redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#102]
Commander elf redone using Bard-M-01 light.png, Prince-01 light.png, and Fighter-M-02 light.png from 24x32 characters pack extended by diamonddmgirl, ears_long-light.png from cabbit collection, and similar to old colors.  
![rcomelf](https://user-images.githubusercontent.com/37004874/37884811-ca113956-307f-11e8-8110-3068a3e45a98.png)
In addition, I extracted/reworked a little.  I'm not sure if these are needed.
By pulling bard's cloak around, I got a bard style cloak without the cloak interfering in front.
![simcloakman](https://user-images.githubusercontent.com/37004874/37884843-eef4dcb4-307f-11e8-807c-3d80ee16d4d1.png)
Here's the cloak.  It's very similar, if not the same as the mage cloak.  You may have to fill in a few pixels to work it on other sprites.
![simcloak](https://user-images.githubusercontent.com/37004874/37884897-44c31e12-3080-11e8-9b45-453716a8abd9.png)
You may want the crown from diamonddmgirl's pack instead of the old one.  There is a slight difference in shape, and the old one is charas.
![mcrown](https://user-images.githubusercontent.com/37004874/37884924-6fba46c2-3080-11e8-93da-81f6b3175e0f.png)

**Comment by olonu** [comment]
slight revision
![rcomelf](https://user-images.githubusercontent.com/37004874/37885649-7a5744dc-3084-11e8-92ea-9bb6db21c99f.png)

**Comment by AntumDeluge** [comment]
Committed to master: 3ede8f3

Thanks @olonu. Those should be useful.
