### ISSUE TITLE
Wikipedian redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#103]
Wikipedian(investigatornpc.png) redone using Townfolk-Adult-M-007 light.png from 24x32 characters pack extended by diamonddmgirl.
![rinvesti](https://user-images.githubusercontent.com/37004874/37887276-d6f848bc-308e-11e8-88de-87a19fed67ec.png)

**Comment by olonu** [comment]
This is another choice.  Adding beard-002-black.png from cabbit-collection gives...
![rinvestic2](https://user-images.githubusercontent.com/37004874/37887554-65e186e6-3090-11e8-823f-8756bf165c8c.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 74b7879

Using beardless version for now.
