### ISSUE TITLE
Albino elf magician redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#104]
This may be a little too much due to transparency.  If so, I can pull something similar with some more solid pieces or go back to the solid confetti toss style in one coloration.  First, here is aem with no effects.
Albino elf magician redone using current imperial scientist and elf-m-ash.png from cabbit collection.
![raelfmagwomag](https://user-images.githubusercontent.com/37004874/37892460-e9079258-30a5-11e8-99ce-d40e39e31f61.png)
Albino elf magician redone using current imperial scientist, elf-m-ash.png from cabbit collection, and beams.png from Lasers and beams (  https://opengameart.org/content/lasers-and-beams )(Rawdanitsu)(CC0).
![raelfmag](https://user-images.githubusercontent.com/37004874/37892563-31570d68-30a6-11e8-8fcd-2ff7f384179d.png)
In addition, I've pulled the scicloak since it seems to be a common usage among about 10 or more sprites.
![scicloak](https://user-images.githubusercontent.com/37004874/37892616-5ec5229e-30a6-11e8-8810-dc5efb4b845a.png)

**Comment by AntumDeluge** [comment]
I think you meant https://opengameart.org/content/lasers-and-beams :wink:

**Comment by AntumDeluge** [comment]
We'll try it with the effects. I think the client can handle it.

**Comment by AntumDeluge** [comment]
We'll try it with the effects. I think the client can handle it.

**Comment by AntumDeluge** [comment]
Committed to master branch: eea3710
