### ISSUE TITLE
Dark elf sacerdotist redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#105]
Dark elf sacerdotist redone using NPC_F-(Amanda) light.png from 24x32 characters pack extended by diamonddmgirl and elf-f-dark_ash.png from cabbit bases collection.
![rdelfsacernostaff](https://user-images.githubusercontent.com/37004874/37924271-569e8336-30ff-11e8-94bf-445dc4a5ed3d.png)
Dark elf sacerdotist redone using NPC_F-(Amanda) light.png from 24x32 characters pack extended by diamonddmgirl, elf-f-dark_ash.png from cabbit bases collection, Quarter Note (Stem Facing Down) ( https://openclipart.org/detail/92953/quarter-note-stem-facing-down )(jaschon), and influence from pestilence staff.png ( https://opengameart.org/content/staff-64-x64 ) (LordNeo)(CC0).
![rdelfsacer](https://user-images.githubusercontent.com/37004874/37924437-dd93bcc6-30ff-11e8-8b4a-193f5911b656.png)
In addition...
![build](https://user-images.githubusercontent.com/37004874/37924457-e8c01f22-30ff-11e8-81af-5f5b9b4bb4d0.png)
![sacerstaffwork](https://user-images.githubusercontent.com/37004874/37924480-f202ee66-30ff-11e8-8551-56a278f9f8e2.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 2abf4f7
