### ISSUE TITLE
Madaram stalker redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#106]
Madaram stalker without cloak redone using Fighter-M-02 light.png from 24x32 characters pack extended by diamonddmgirl, similar to old colors, and RPGCharacterSprites32x32.png from 
32x32 RPG Character Sprites ( https://opengameart.org/content/32x32-rpg-character-sprites ) (Eldiran)(CC0).
![rmadstanocloak](https://user-images.githubusercontent.com/37004874/37963886-a35eaed8-318d-11e8-93d7-e560fc59411b.png)
Madaram stalker redone using Fighter-M-02 light.png and Bard-M-01 light.png from 24x32 characters pack extended by diamonddmgirl, similar to old colors, and RPGCharacterSprites32x32.png from 
32x32 RPG Character Sprites ( https://opengameart.org/content/32x32-rpg-character-sprites ) (Eldiran)(CC0).
![rmadsta](https://user-images.githubusercontent.com/37004874/37963931-cb7626e4-318d-11e8-96da-4de51ca95c0d.png)
In addition, here is the top layer for fighter arm bolster.  The light blue color might depend on the situation; it's not intended for actual usage.  I'm not sure I'd use this bolster on another sprite.
![fibolster](https://user-images.githubusercontent.com/37004874/37963985-fbe03f18-318d-11e8-9299-15ba94761e47.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: ec85996
