### ISSUE TITLE
Dark elf wizard redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#107]
Dark elf wizard redone using alchemist_Zmiter_char.png from (24x32 characters, 16x16 tiles) ( https://opengameart.org/content/24x32-characters-16x16-tiles )(Cabbit), similar to old colors, and Quarter Note (Stem Facing Down) ( https://openclipart.org/detail/92953/quarter-note-stem-facing-down )(jaschon).
![rdelfwiz](https://user-images.githubusercontent.com/37004874/38012646-464bb92c-3230-11e8-8556-23b0c4e67a1a.png)
Here is version without staff.
![rdelfwiznowand](https://user-images.githubusercontent.com/37004874/38012651-4e804928-3230-11e8-901f-274f76ef0f46.png)
Here is some staff rework and outfit stuff.
![staffrework](https://user-images.githubusercontent.com/37004874/38012667-5a0ea0d2-3230-11e8-8d64-2fe107f98103.png)
![zhimoutfit](https://user-images.githubusercontent.com/37004874/38012672-5e6e029e-3230-11e8-99ae-29ba2dde3d32.png)
![more2](https://user-images.githubusercontent.com/37004874/38012675-5fddbfac-3230-11e8-90a5-5b038599bb49.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 68e1621

Thank you for the layers. 😄
