### ISSUE TITLE
Amazoness coastguard redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#108]
Amazoness coastguard redone using current dress_091.png, jacket-001-black.png, and pants-001-blue.png from stendhal repository and Townfolk-Adult-F-004 light.png from 24x32 characters pack extended by diamonddmgirl.
![ramacom](https://user-images.githubusercontent.com/37004874/38017912-76701c9a-3241-11e8-84b7-0acdc7db40ff.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 83d5b2b
