### ISSUE TITLE
Kasarkutominubat redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#109]
Kasarkutominubat redone using Cultist-02.png and TEMPLATE thin light.png from 24x32 characters pack extended by diamonddmgirl, similar to old colors, and Baseball-Bat-300px.png from Baseball Bat ( https://openclipart.org/detail/264927/baseball-bat )(NicholasJudy456).
![kasa](https://user-images.githubusercontent.com/37004874/38081285-a78a5f4a-3311-11e8-8b9f-25243e07d270.png)
It's a lil small, as such here is regular kasa before another scale2x, in case there's another scale for a slightly bigger kasa that works.
![kasareg](https://user-images.githubusercontent.com/37004874/38080754-4de36618-3310-11e8-806a-f05a42f26cda.png)
Here's baseball bat work.
![kasabbat](https://user-images.githubusercontent.com/37004874/38080780-5541772e-3310-11e8-868c-d864f5ea0a94.png)

**Comment by AntumDeluge** [comment]
Size looks alright to me. 😄

Committed to master branch: 58b2c79
