### ISSUE TITLE
Amazoness coastguard master/mistress redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#110]
This one is a doozy.  It's all part of the same animation, but I'm going to list stuff a little separately.
-Amazon coastguard mistress body redone using Aristocrate-F-02 light.png and Townfolk-Adult-F-003 light.png from 24x32 characters pack extended by diamonddmgirl and similar to old colors.
-Chakram done using wheel16x16.png from 4-frame conveyor belt and seperate wheel ( https://opengameart.org/content/4-frame-conveyor-belt-and-seperate-wheel )(Spring)(CC0) and handle using w_scimitar.png tip.  Color influence from w_scimitar.png, w_scimitar_copper.png, and w_scimitar_gold.png ( https://opengameart.org/content/scimitar-64x64 )(LordNeo)(CC0).
-Sword is w_shortsword_steel.png from short sword [64x64] ( https://opengameart.org/content/short-sword-64x64 )(LordNeo)(CC0).
![ramacom](https://user-images.githubusercontent.com/37004874/38106614-9119d118-335d-11e8-923d-7c2c57aee117.png)
Without weapons...
![ramacomnowpns](https://user-images.githubusercontent.com/37004874/38106653-b4f1bca4-335d-11e8-8594-00d5c45ed4f7.png)
Here's weapon's work.
![acmwpns](https://user-images.githubusercontent.com/37004874/38106739-f5459dac-335d-11e8-8135-d1d09b7d8482.png)

**Comment by AntumDeluge** [comment]
Looks great! I especially like the sword.

**Comment by AntumDeluge** [comment]
Committed to master branch: 63581fe
