### ISSUE TITLE
Madaram trooper redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#111]
Madaram trooper redone using Fighter-M-01 light.png from 24x32 characters pack by diamonddmgirl, rpgportraits.png from RPG portraits ( https://opengameart.org/content/rpg-portraits )(Buch)(CC0), and horrorsaber.png from Pixel Swords ( https://opengameart.org/content/pixel-swords-0 )(Shawneth)(CC0).
![rmadtroo](https://user-images.githubusercontent.com/37004874/38122522-8c4a996a-33a3-11e8-9620-821a861c4569.png)
Madaram trooper without weapons and saber work.
![rmadtroonowpn](https://user-images.githubusercontent.com/37004874/38122555-c3ff6836-33a3-11e8-80d5-a1b5577f4092.png)
![hsaberwork](https://user-images.githubusercontent.com/37004874/38122559-c7d660e0-33a3-11e8-9ed2-6906bb3a5052.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: b82daca
