### ISSUE TITLE
Dark elf viceroy redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#112]
Dark elf viceroy redone using ears_long-dark_ash.png from cabbit collection, preview-full.xcf from   Armor Outfit by deluge, similar to old colors, and w_shortsword dark.png from short sword [64x64] ( https://opengameart.org/content/short-sword-64x64 ) (LordNeo)(CC0), and Electrical disintegration animation( https://opengameart.org/content/electrical-disintegration-animation )(superjoe)(CC0).
![rdelfvroy](https://user-images.githubusercontent.com/37004874/38134041-87359e5c-33df-11e8-9acd-5c3debfbda49.png)
Here is some along the way work.
![rdelfvroynoaur](https://user-images.githubusercontent.com/37004874/38134058-953abfb4-33df-11e8-8686-f2d1222fcc46.png)
![rdelfvroynowpns](https://user-images.githubusercontent.com/37004874/38134064-97d5ab9e-33df-11e8-8861-8a8a56150ce1.png)
![rdelfvrwpns](https://user-images.githubusercontent.com/37004874/38134072-9b4625ce-33df-11e8-83dc-9b1730b95370.png)
The aura has been cleaned up a little since imperial demon lord.  It probably lacks gray pixels now.
![rdelfvroyaur](https://user-images.githubusercontent.com/37004874/38134077-a1a306e4-33df-11e8-9dde-1d1f5bda437e.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 64e5dba

Thank you so much @olonu. You are doing great work & helping out so much.

**Comment by AntumDeluge** [comment]
I made a [child base](https://github.com/AntumDeluge/cabbit-bases-collection/tree/master/art/sprite/base/human/child) if you want to use it in the future.
