### ISSUE TITLE
Amazon bodyguard redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#113]
Amazon bodyguard redone using Townfolk-Adult-F-001 light.png and Fighter-F-02 light.png from 24x32 characters pack extended by diamonddmgirl and rpg_sprite_walk.png from 2D RPG character walk spritesheet ( https://opengameart.org/content/2d-rpg-character-walk-spritesheet )(arikel)(CC-BY-SA 3.0).
![ramabg](https://user-images.githubusercontent.com/37004874/38161593-d8b3a308-349f-11e8-97b4-01aae0b9345f.png)
Here is the armor work, although it isn't fully adjusted.  I'm not sure I'd use this as a replacement for the armor I replaced on the original amazon bodyguard, but it looks different enough here that it's sort of funny.
![amaarmwork](https://user-images.githubusercontent.com/37004874/38161603-05a59768-34a0-11e8-9e0c-b250a0a9453e.png)
Here is part way to the hair.
![hairstyle](https://user-images.githubusercontent.com/37004874/38161606-26973ec2-34a0-11e8-88fd-6d854714b33e.png)

**Comment by olonu** [comment]
I may need to revise.

**Comment by olonu** [comment]
Action in top row was corrected to resemble action from rpg_sprite_walk.png.
![ramabg](https://user-images.githubusercontent.com/37004874/38162048-4e9476c6-34a8-11e8-9819-34b11ca20313.png)

**Comment by AntumDeluge** [comment]
Missed the revision at first, but added now 😉: abc5261
