### ISSUE TITLE
Dark Elf Master redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#116]
Dark elf master redone using Cultist-02.png 24x32 characters pack diamonddmgirl, ears_long-dark_ash.png cabbit collection, Yan_char.png from Heroes_by_KusSv, mostly similar to old colors, and Electrical disintegration animation( https://opengameart.org/content/electrical-disintegration-animation )(superjoe)(CC0).
![rdelfmas](https://user-images.githubusercontent.com/37004874/38184741-bcb83f5a-3617-11e8-8f31-821d4f6507e3.png)
![rdelfmasaur](https://user-images.githubusercontent.com/37004874/38184743-be8ef5b2-3617-11e8-8931-0d43ee88d1e5.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 6b3b217
