### ISSUE TITLE
Dark elf redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#117]
Dark elf redone using Prince-01 light.png and Cultist-03.png from 24x32 characters pack extended by diamonddmgirl, ears_long-dark_ash.png from cabbit collection, and similar to old colors.
![rdelf](https://user-images.githubusercontent.com/37004874/38201020-a7e7c49a-3664-11e8-9a2e-386366f78e29.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: a9a958d
