### ISSUE TITLE
Oni warrior redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#118]
Oni warrior redone using Healer-M-01 light.png, Townfolk-Adult-M-005 light.png, and Townfolk-Child-M-002 dark.png from 24x32 characters pack extended by diamonddmgirl and holly staff.png from 
Staff [64 x64] ( https://opengameart.org/content/staff-64-x64 )(LordNeo)(CC0).
![roniwar](https://user-images.githubusercontent.com/37004874/38210214-bf2d77a6-3684-11e8-872c-cd7145a71da2.png)

**Comment by AntumDeluge** [comment]
The oni look so good. I love the new sprites. 😄

**Comment by AntumDeluge** [comment]
Commited to master branch: 2e62111

**Comment by olonu** [comment]
I may need to make a revision already.  The ears on this hat need to be tucked.  I kind of remember why I didn't want to use this hat now, but it'll work.  The only alternative is to try to draw the ears on the sides of the hat to the corresponding front/back sprites visible ear portions, but it'll look more like random lines.
![roniwar](https://user-images.githubusercontent.com/37004874/38217108-08db3f62-369b-11e8-848d-611664e17c8f.png)

**Comment by olonu** [comment]
Here it is in the alternate style.  It's a little rough conceiving a hat in this shape, but it may be best as not to hide the ears completely.
![roniwarc2](https://user-images.githubusercontent.com/37004874/38217686-42a4c720-369d-11e8-9ec1-dff75de51353.png)

**Comment by olonu** [comment]
It won't work with the ears completely out like elf ears as the hat front will be to damaged.

**Comment by AntumDeluge** [comment]
I don't see the difference between the first & last ones.

**Comment by AntumDeluge** [comment]
Here are the ears on their own layer:
![oni-ears](https://user-images.githubusercontent.com/3631473/38225121-35f9292a-36a8-11e8-844f-b6696843dd6d.png)

**Comment by AntumDeluge** [comment]
I actually like the first version better, keeping the weapon behind the hat. I'd rather leave it. How do you feel about that?

**Comment by olonu** [comment]
I don't really like the ears completely tucked, but I don't like the ears elfing out like elf ears, so either version one or version three.  Version three accounts for the tips of the ears in the side sprite rows.  Otherwise the front/back sprites have unexplained ear tips.  I'm not seeing a weapons reorientation because of that.  Probably no one will ever notice, but version one will let one think the hat has some kind of open mechanism when the sprite is front/back with a close mechanism on the sides.  I'm fine either way as version three can be obtained again quickly using version one.

**Comment by AntumDeluge** [comment]
Oh, I see, I was looking at it wrong. I though the slits in the hat were showing the weapon.

**Comment by AntumDeluge** [comment]
You really don't think it looks good with the ears completely out?
![oni_warrior-alt](https://user-images.githubusercontent.com/3631473/38341986-60ff8bda-3830-11e8-86f6-d016b44672c0.png)

I think if you're going to have "slits", the south-facing frames should demonstrate this as well.

**Comment by olonu** [comment]
You choose.  If you go ears completely out, the south facing frames may need the hat bottom under the ears clipped.

**Comment by olonu** [comment]
I choose the ears out, even though it partially "destroys" the healer hat, which isn't really relevant.  Destroying the healer hat gives a beanie like hat appearance, which isn't quite the same as the old oni warrior's hat, but it'll work.

**Comment by AntumDeluge** [comment]
That version I had uploaded & added was missing the weapon on the south-facing frames. Fixed now.
