### ISSUE TITLE
Dark elf matronmother redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#119]
Dark elf matronmother redone using Townfolk-Child-F-001 light.png from 24x32 characters pack extended by diamonddmgirl, current imperial scientist cloak, similar to old colors, and 59_32_sword.png from 32x sword icon ( https://opengameart.org/content/32x-sword-icon )(59naga)(CC0).
![rdelfmamot](https://user-images.githubusercontent.com/37004874/38287596-86946902-3799-11e8-8b78-d555e056089c.png)

**Comment by AntumDeluge** [comment]
Ooh, this looks good. 😀

**Comment by AntumDeluge** [comment]
Committed to master branch: 1d8115b

**Comment by AntumDeluge** [comment]
I noticed that your Stendhal character is named [olonu](https://stendhalgame.org/character/olonu.html). At least, I'm assuming that is you.

**Comment by olonu** [comment]
Ya.
