### ISSUE TITLE
Imperial demon servant redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#120]
Imperial demon servant redone using TEMPLATE thin light.png and Cultist-01.png from 24x32 characters pack extended by diamonddmgirl, similar to old colors, and horns from Dark Soldier rework.
![rimpdser](https://user-images.githubusercontent.com/37004874/38291566-41cb45f6-37ae-11e8-94be-5adc9fee8a1b.png)
The head isn't entirely blacked.

**Comment by AntumDeluge** [comment]
Looks great!
