### ISSUE TITLE
Amazoness commander redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#121]
Amazoness commander redone using Bard-M-01 light.png and Fighter-F-02 light.png from 24x32 characters pack extended by diamonddmgirl.
![ramacom](https://user-images.githubusercontent.com/37004874/38393835-28a792bc-38fa-11e8-8169-7e47a20aa75f.png)
As I was doing this one, I noticed I plastered the cloak over the front sprites' leg armors.  As such, commander elf has this error also.  Madaram stalker doesn't have this error, but instead it has a contrast mesh across the armor/cloak.  Mad stalker's error isn't as severe, and I do have the no cloaked version.  Here is a revision for commander elf.
![rcomelf](https://user-images.githubusercontent.com/37004874/38393892-646937ec-38fa-11e8-8902-36428804de10.png)

**Comment by AntumDeluge** [comment]
Commited to master branch: 17720e5 & 6ab5db3
