### ISSUE TITLE
Dark elf general redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#122]
Dark elf general redone using Cultist-01.png and Fighter-M-01 light.png from 24x32 characters pack extended by diamonddmgirl, ears_long-dark_ash.png from cabbit collection, mix of old and new colors, and w_shortsword_0.png from short sword [64x64] ( https://opengameart.org/content/short-sword-64x64 )(LordNeo)(CC0).
![rdelfgen](https://user-images.githubusercontent.com/37004874/38450608-f57b5afe-39ee-11e8-8dc2-3ec9a732b3f9.png)
Without weapons and weapons work...
![rdelfgenowpns](https://user-images.githubusercontent.com/37004874/38450609-fd4b0e50-39ee-11e8-92ad-d943bb53279a.png)
![delfgenwrk](https://user-images.githubusercontent.com/37004874/38450612-ff4f02e2-39ee-11e8-8913-62a2788c345e.png)

**Comment by olonu** [comment]
I propose using the short sword here as the drop in replacement for the old broadsword that was on many of the monsters' backs as I've now used it 3 times and it is CC0.  Use the base version before recoloring, so that recoloring for purposes is easier.

**Comment by AntumDeluge** [comment]
Committed to master branch: d130034
