### ISSUE TITLE
Dark elf captain redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#123]
Dark elf captain redone using Yan_char.png from Heroes_by_KusSv.7z, Fighter-M-01 light.png from 24x32 characters pack extended by diamonddmgirl, similar to old colors, ears_long-dark_ash.png from cabbit collection, and 23.png from Sword ( https://opengameart.org/content/sword-3 )(Amir027)(CC0).
![rdelfcap](https://user-images.githubusercontent.com/37004874/38460541-10a1974e-3a8a-11e8-9ec4-5d03a033f7ac.png)
Some weapons work...
![delfcapwpns](https://user-images.githubusercontent.com/37004874/38460543-16af52ac-3a8a-11e8-92e4-3e20260df4ee.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: b87c212
