### ISSUE TITLE
Mithrilbourgh soldier redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#130]
Mithrilbourgh soldier(soldier_common.png) redone using TEMPLATE thin light.png and Townfolk-Adult-M-005 light.png from 24x32 characters pack extended by diamonddmgirl.
![rsoldier](https://user-images.githubusercontent.com/37004874/38600844-9eec245a-3d33-11e8-860d-dca5eaf998c9.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 6bc7fc6
