### ISSUE TITLE
Barrett Holmes and Wilfred redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#131]
Barrett Holmes(estateagentnpc.png) redone using base-m-light_black.png from cabbit-bases-collection and suit-002.png and townfolk-child-m-001-black.png from cabbit collection 0.4.
![restagent](https://user-images.githubusercontent.com/37004874/38607191-fe248856-3d45-11e8-8acb-efe4b6c44739.png)
Wilfred(executivenpc.png) redone using base-m-light.png from cabbit-bases-collection and suit-002.png from cabbit collection 0.4.
![rexenpc](https://user-images.githubusercontent.com/37004874/38607267-27df711a-3d46-11e8-85e6-57fbf2b96d5d.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 26c2402 & 689426e
