### ISSUE TITLE
estateagent2npc.png redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#132]
estateagent2npc.png redone using suit-002.png from cabbit collection 0.4, base-m-light.png from cabbit-collection-bases, and Townfolk-Adult-M-007 light.png from 24x32 characters pack extended by diamonddmgirl.
![restagent2](https://user-images.githubusercontent.com/37004874/38609667-ab9d6a92-3d4c-11e8-9c02-842fbc7dc654.png)

**Comment by olonu** [comment]
Slight revision...
![restagent2](https://user-images.githubusercontent.com/37004874/38609869-42c36d40-3d4d-11e8-9f45-49d49c8cc529.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 7ec9f93
