### ISSUE TITLE
How can I build a website like stendhalgame.org

### ISSUE THREAD

**Issue by rmb338** [arianne/stendhal#133]
https://stendhalgame.org/ and it's wiki supply the whole game knowledgement.
Where is the soucre code of this site?or how to make a new language translation?

**Comment by AntumDeluge** [comment]
The website source is currently hosted on [SourceForge](https://sourceforge.net/p/arianne/stendhal-website/ci/master/tree/). I think there are instructions on setting up a local PHP server & database on the wiki.

**Comment by rmb338** [comment]
I have logon as a member of SourceForge.net,but I can't access the url [SourceForge](https://sourceforge.net/p/arianne/stendhal-website/ci/master/tree/).
Is there any permission limited or I have to join any group?
thanks!

**Comment by AntumDeluge** [comment]
No, there aren't any restrictions like that.

SourceForge has been going through some transitions & the site often becomes unreachable. That may be what you are experiencing. Keep trying.

**Comment by rmb338** [comment]
Sorry for my ambiguous description for "can't access" that is not mean can't open,
the url says 403 error:
Forbidden
Sorry, the permissions for this page don't allow you to access it.

**Comment by AntumDeluge** [comment]
That is strange. That shouldn't be happening. Are you able to see the main Arainne SourceForge page? https://sourceforge.net/projects/arianne

**Comment by rmb338** [comment]
I can see the project https://sourceforge.net/projects/arianne
but I can't clone the repo of arianne-stendhal-website because of access denied or repository not exported
git log show that:

Cloning into 'P:\git-src\arianne\stendhal-website arianne-stendhal-website'...
Looking up git.code.sf.net ... done.
Connecting to git.code.sf.net (port 9418) ... 216.105.38.16 done.
fatal: remote error: access denied or repository not exported: /p/arianne/stendhal-website arianne-stendhal-website

**Comment by AntumDeluge** [comment]
That sounds like it might be the issue I mentioned above. SourceForge has been going through some big transitions. There are times when parts of the site are not available. Try again later. I'm hoping that admins will mirror website code on GitHub.

I've created a clone of the website repo on GitHub, but I don't know how far out of date it is. But if you want to try it, it is here: https://github.com/AntumDeluge/arianne-stendhal-website

**Comment by rmb338** [comment]
thanks,It's a great work!

**Comment by nhnb** [comment]
> fatal: remote error: access denied or repository not exported: /p/arianne/stendhal-website arianne-stendhal-website

The repository path is wrong. The correct path is git://git.code.sf.net/p/arianne/stendhal-website

I assume the error occurred because the git command quoted above contained the extra "arianne-stendhal-website" destination folder at the end and I assume you did not use the command line but included that parameter into the repository url input field of some other git software.

**Comment by AntumDeluge** [comment]
@nhnb is right. Sorry, I wasn't looking at the errors carefully.
