### ISSUE TITLE
Blacksheep(blacksheepnpc.png) redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#134]
Blacksheeps(blacksheepnpc.png) redone using Pepper-001.png from cabbit collection 0.4, TEMPLATE thin light.png, and Townfolk-Adult-M-003 light.png from 24x32 characters pack extended by diamonddmgirl.
![rblacksheep](https://user-images.githubusercontent.com/37004874/38712949-b602dbb0-3e9c-11e8-83d6-fe753ef654c6.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: bcecee9
