### ISSUE TITLE
Demon redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#135]
Demon redone using base-m-tough-light.png from cabbit-bases-0.3, eyes from Icy Tower Demon Sprites ( https://opengameart.org/content/icy-tower-demon-sprites )(surt)(CC0), and head from Candle Sprite ( https://opengameart.org/content/candle-sprite )(ahmadmanga).
![rdemon](https://user-images.githubusercontent.com/37004874/38733161-e569c326-3eee-11e8-9595-a4c69942b850.png)
Here's the head layer as a separate png...
![rdhead](https://user-images.githubusercontent.com/37004874/38733226-15d4f6c0-3eef-11e8-90a8-5552fceb0fa6.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 7b55ca6
