### ISSUE TITLE
Kalavan wisewoman redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#136]
Kalavan wisewoman redone using Aristocrate-F-02 light.png from 24x32 characters pack extended by diamonddmgirl.
![rkalwiwo](https://user-images.githubusercontent.com/37004874/38763944-48e43cc6-3f74-11e8-8080-7134d3704c3a.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: b0555c3
