### ISSUE TITLE
Despot Halb Errvl(blacklord.npc) redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#137]
Despot Halb Errvl(blacklord.npc) redone using fighter-m-002-black.png from cabbit collection 0.4 and Cultist-02.png from 24x32 characters pack extended by diamonddmgirl.
![rblacklord](https://user-images.githubusercontent.com/37004874/38773984-c1f9283c-4029-11e8-814f-d898ae8a78e5.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 5e8d33f
