### ISSUE TITLE
Imp redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#138]
Imp redone using base-c-A-light.png from cabbit-bases-collection and horns from Icy Tower Demon Sprites ( https://opengameart.org/content/icy-tower-demon-sprites )(surt)(CC0).
![rimp](https://user-images.githubusercontent.com/37004874/38775025-b46b4978-4044-11e8-82e4-16f101f01a3c.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: d908ac9
