### ISSUE TITLE
littlegirl2npc.png redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#139]
littlegirl2npc.png redone using Townfolk-Child-F-001 light.png and Townfolk-Child-F-002 light.png from 24x32 characters pack extended by diamonddmgirl.
![rlilgirl2](https://user-images.githubusercontent.com/37004874/38775609-13811784-4055-11e8-8db1-a75322bf3e5e.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: e881818
