### ISSUE TITLE
Annie Jones(pinkgirlnpc.png) redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#140]
Annie Jones(pinkgirlnpc.png) redone using Townfolk-Adult-F-001 light.png and Townfolk-Child-F-002 light.png from 24x32 characters pack extended by diamonddmgirl.
![rpinkgirl](https://user-images.githubusercontent.com/37004874/38775871-f3deb11a-405a-11e8-95b6-18531cef3181.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 923f02b
