### ISSUE TITLE
Vasi Elos(madscientistnpc.png) redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#141]
Vasi Elos(madscientistnpc.png) redone using Mask-M-01 light.png and Cultist-01.png from 24x32 characters pack extended by diamonddmgirl.
![rmadsci](https://user-images.githubusercontent.com/37004874/38776243-db160eba-4061-11e8-9434-dfee6817ae91.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: d12dccb & e90d58f

Thank you for the hard work @olonu. :smile:
