### ISSUE TITLE
Archer elf redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#142]
Archer elf redone using Townfolk-Adult-M-003 light.png and Townfolk-Adult-M-004 light.png from 24x32 characters pack extended by diamonddmgirl, ears_long-light.png from cabbit bases collection, and bow from Archer Job set ( https://opengameart.org/content/archer-job-set )(SoCay).
![rarchelf](https://user-images.githubusercontent.com/37004874/38790553-03ea2700-4110-11e8-8116-f18121ce7118.png)
Here's some bow work.
![rosebow](https://user-images.githubusercontent.com/37004874/38790548-fa8507e8-410f-11e8-9933-75401774c7f5.png)

**Comment by olonu** [comment]
If this bow doesn't agree with a green grass background, it can probably be recolored to some other vine-like color later, for example purple.

**Comment by AntumDeluge** [comment]
Committed to master branch: 5ab4dff
