### ISSUE TITLE
Swimmers 1 and 2 redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#143]
Cyk(swimmer1npc.png) redone using Townfolk-Adult-M-002 light.png from 24x32 characters pack extended by diamonddmgirl, base-m-light.png, and dress_097.png from stendhal repository.
![rswimr1](https://user-images.githubusercontent.com/37004874/38842372-9e285254-41b7-11e8-81b1-d68ad6905047.png)
Dorinel(swimmer2npc.png) redone using Townfolk-Adult-M-004 light.png from 24x32 characters pack extended by diamonddmgirl, elf-m-light.png, and dress_097.png from stendhal repository.
![rswimr2](https://user-images.githubusercontent.com/37004874/38842381-a5d8fb66-41b7-11e8-9507-83f3f36f4048.png)
Slight possible Yan(swimmer4) correction for top row...
![ryan2](https://user-images.githubusercontent.com/37004874/38830102-38085cb8-4189-11e8-97dc-0c09b7ca5a35.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 9ea81d7, 75b910e, 8223588
