### ISSUE TITLE
Swimmers 3 and 5 redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#145]
Enrique(swimmer3npc.png) redone using hair_006.png and dress_097.png from current stendhal repository and TEMPLATE thin light.png from cabbit.
![rswimr3](https://user-images.githubusercontent.com/37004874/39029664-01579aea-442b-11e8-9a09-e60db2428ab2.png)
John(swimmer5npc.png) redone using dress_097.png, hair_005.png, and hair_025.png from current stendhal repository base-m-light_black.png from cabbit-bases-collection.
![rswimr5](https://user-images.githubusercontent.com/37004874/39029936-a77b2b98-442c-11e8-9f6a-2dc287d28770.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 84d526d & e98659d
