### ISSUE TITLE
Little assassin and little johnny redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#147]
Little assassin redone using Townfolk-Child-M-001 light.png from 24x32 characters pack extended by diamonddmgirl, hair_012.png from stendhal repository, base-c-A-light.png from cabbit bases collection, and dagger from current apprentice assassin.
![rlilassas](https://user-images.githubusercontent.com/37004874/39083104-db541870-452c-11e8-8403-f50c196df4f4.png)
Little Johnny redone using Townfolk-Child-M-001 light.png from 24x32 characters pack extended by diamonddmgirl, hair_012.png from stendhal repository, base-c-A-light.png from cabbit bases collection, and dagger from current apprentice assassin.
![rliljohnny](https://user-images.githubusercontent.com/37004874/39083108-e905471e-452c-11e8-9684-8ecf31559868.png)

**Comment by AntumDeluge** [comment]
Aren't these both the same?

**Comment by AntumDeluge** [comment]
Committed to master branch: d7bd8af
