### ISSUE TITLE
Little fairy redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#149]
I'm submitting two slightly different versions.  In the side rows, one emphasizes the wings as in the old sprite.  The other emphasizes the hair in front of the wings and the wings' smallness in the side rows.  This is a close call.  Also it may be that wing action needs to be added, but the old little fairy did not have wing action.
Little fairy redone using base-c-A-light.png, hair_011.png from stendhal repository, and Asas de borboleta/fada vetor - butterfly/fairy wings vector - Inkscape from ( https://openclipart.org/detail/194497/asas-de-borboleta-vetor-butterfly-wings-vector-inkscape ) (leangoro).
![rlilfairy](https://user-images.githubusercontent.com/37004874/39211401-779ad5f8-47d9-11e8-8d64-22798f036bc0.png)
![rlilfairy2](https://user-images.githubusercontent.com/37004874/39211406-7a5c48d0-47d9-11e8-8808-bf8c798f11d0.png)

**Comment by AntumDeluge** [comment]
Gosh, that shouldn't be such a difficult decision for me. lol.

Not a big deal, either looks great. I would picture the wings in front of the hair. But I actually think I like the emphasis on the hair a little better. So, I will go ahead & add the 2nd one. 😃

Love the wings BTW. I wanted to make some like that for the floating lady/oracle sprites. But now we have these. Thanks!

**Comment by AntumDeluge** [comment]
Committed to master branch: bf32778

**Comment by AntumDeluge** [comment]
Used wings on the [oracle](https://github.com/arianne/stendhal/blob/fa19b111cd2489c51e0270bc16cc2a1c85c137b2/data/sprites/npc/oracle1npc.png) NPC sprites. :)

May add some action to wings later.
