### ISSUE TITLE
Dark elf archer redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#150]
This bow may have some trouble against the cave background.  It probably can be recolored later if it needs to be.  I'm fitting through the remaining bows that I have easy access to according to the remaining archers.
Dark elf archer redone using Yan_char.png from Heroes_by_KusSv, elf-m-dark_ash.png from cabbit-bases-collection, hair_042.png from stendhal repository, and bow from Archer Job set ( https://opengameart.org/content/archer-job-set )(SoCay).
![rdelfarch](https://user-images.githubusercontent.com/37004874/39255604-ebcf2900-487a-11e8-88d8-1138c8ae93d4.png)
Some bow work...
![delfbow](https://user-images.githubusercontent.com/37004874/39231907-9c1cebcc-4839-11e8-9e06-e22c308955b3.png)

**Comment by olonu** [comment]
Dark elf elite archer redone using Yan_char.png from Heroes_by_KusSv, elf-m-dark_ash.png from cabbit-bases-collection, hair_010.png from stendhal repository, and bow from Archer Job set ( https://opengameart.org/content/archer-job-set )(SoCay).
![rdelfearch](https://user-images.githubusercontent.com/37004874/39238806-2d6bce1e-484d-11e8-8bb2-b248d4ad7b83.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 0297c26 & 6d3cae5

Thank you so much @olonu. 😃
