### ISSUE TITLE
Imperial Archer redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#151]
I think the eye setting is ok being similar to the old.  If not, then the "Kalavan" look has to be removed from several of the sprites, and it probably would have to find something alternative, which may not be easy.  I will probably get to elite archer and decide on archer leader later.  Use carbuncle's color pattern for e archer and sapphire's color pattern for archer leader.
Imperial archer redone using Bard-M-01 light.png from 24x32 characters pack extended by diamonddmgirl and RoyalBow.png from Minecraft Items ( https://opengameart.org/content/minecraft-items )(SoCay)(CC0).
![rimparch](https://user-images.githubusercontent.com/37004874/39268408-e1d57404-489d-11e8-98fd-762acbac71c8.png)
Some bow work...
![riarchbow](https://user-images.githubusercontent.com/37004874/39268450-05f92fba-489e-11e8-94f5-bb7577f1355b.png)

**Comment by olonu** [comment]
Imperial elite archer redone using Bard-M-01 light.png from 24x32 characters pack extended by diamonddmgirl, hair_006.png from stendhal repository, and RoyalBow.png from Minecraft Items ( https://opengameart.org/content/minecraft-items )(SoCay)(CC0).
![rimpearch](https://user-images.githubusercontent.com/37004874/39274139-07331376-48af-11e8-9228-d2269f7d084b.png)

**Comment by olonu** [comment]
Frame 1,3 probably needs some kind of correction, though I can't think exactly what to do except pull the cloak around the bow or go ahead and place the back side behind the cloak.

**Comment by AntumDeluge** [comment]
Looks okay to me. I'll check it out in-game & see what it looks like.

**Comment by AntumDeluge** [comment]
Ya, it kind of looks like the bow disappears for second when the archers are walking north. But it's fine for now. :)

Committed to master branch: 73f963d & 2fd97a0
