### ISSUE TITLE
Blordrough concept

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#153]
Here is the blordrough concept.
![ulblortest](https://user-images.githubusercontent.com/37004874/39342565-8d489c22-49a6-11e8-938c-cb6d989af917.png)

**Comment by AntumDeluge** [comment]
Interesting. Looks like it could work.

**Comment by olonu** [comment]
You may can actually scale it without too much blunder.  Scaling it would preserve the arms and legs.  The legs are a tiny bit off to this game, but the arms are right.  A side view different from the LPC side view needs to be drawn.  Otherwise you might use the LPC head, especially if it hasn't been used on something else.  The scaling on the front/back needs to be exact as possible to the original sprite, for example maybe 64x46 to 48x46 if not more exact.
![blor2](https://user-images.githubusercontent.com/37004874/39483397-3af1cc44-4d40-11e8-843f-13b1f58e6e86.png)

**Comment by olonu** [comment]
Another option you could get is to get someone to draw 1 side sprite for you that's adjustable to the walking.

**Comment by olonu** [comment]
Another option too with all this is to change the sprite dimensions to fit the mech at 2x and use the LPC head or get a side sprite.

**Comment by olonu** [comment]
On another note, this sprite looks really similar to the stone/ice golem already in use albeit not having a fancy interior design.  You might take the stone/ice golem, fancy design the interior, pull the golem head off, and shove a head in there.
