### ISSUE TITLE
Duergar redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#154]
Duergar redone using current dwarf, Townfolk-Adult-M-009 light.png from 24x32 characters pack, and 
Blue Heavy Armor ( https://opengameart.org/content/blue-heavy-armor )(bearmetal)(CC0).
![rduergar](https://user-images.githubusercontent.com/37004874/39370859-fdb20a9a-4a0d-11e8-953b-663ce3d38d71.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 7a3a338
