### ISSUE TITLE
Imperial high priest redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#157]
Imperial high priest redone using Fighter-M-02 light.png and Cultist-02.png from 24x32 characters pack extended by diamonddmgirl and Pepper-001.png from cabbit collection 0.4.
![rimphipri](https://user-images.githubusercontent.com/37004874/39611987-88869198-4f29-11e8-80f7-6e41d25f7489.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 64ed2b4
