### ISSUE TITLE
Balduin redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#158]
Balduin/Gamblos redone using townfolk-elder-m-001-light.png from 24x32 characters pack extended by diamonddmgirl and hair_037.png from stendhal repository.
![rbaldy](https://user-images.githubusercontent.com/37004874/39645609-f386594c-4fa6-11e8-8079-1b841e794644.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: d3e0a44
