### ISSUE TITLE
Ruarhi redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#159]
Ruarhi(barman2npc.png) redone using pirates' bandana, Townfolk-Adult-M-005 light.png from 24x32 characters pack extended by diamonddmgirl, pants-001-brown.png from stendhal repository, and Hair for 24x32 bases by diamonddmgirl ( https://opengameart.org/content/hair-for-24x32-bases )(CC0).
![rbarman2](https://user-images.githubusercontent.com/37004874/39659762-ee311494-4ffd-11e8-8f83-ad3b9769dc74.png)

**Comment by olonu** [comment]
I made a baby bear.
Baby bear redone using townfolk-child-f-003-black.png from cabbit collection 0.4 and base-c-A-light.png.
![rbabybear](https://user-images.githubusercontent.com/37004874/39660291-a6681228-5009-11e8-85bb-09b3af2e6693.png)

**Comment by AntumDeluge** [comment]
Love the baby bear. 😸

**Comment by AntumDeluge** [comment]
Committed to master branch: 2089a5e & f9fa2eb
