### ISSUE TITLE
Imperial archer leader redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#160]
It suffers from the same problem as the other two, but it can pretty much stay like this or add the rest of the bow back into the affected frame in 1,3.  I can't really quite envision how to budge the cloak back exactly right, but once done, the fix could be applied to all 3 imperial archers.
Imperial archer leader redone using hair_005.png from stendhal repository and Prince-01 light.png and Bard-M-01 light.png from 24x32 characters pack extended by diamonddmgirl.
![rimparcl](https://user-images.githubusercontent.com/37004874/39952083-bc0825c8-555e-11e8-8f5c-9d564b2b5c12.png)
![rimparclnobow](https://user-images.githubusercontent.com/37004874/39952084-bf0cb8ec-555e-11e8-91e7-2b2899488808.png)
![riarchbow](https://user-images.githubusercontent.com/37004874/39952086-c86189ae-555e-11e8-886c-7300ab4e84fd.png)

**Comment by AntumDeluge** [comment]
Is the bow one of SoCay's?

**Comment by olonu** [comment]
Ya, RoyalBow.png from Minecraft Items ( https://opengameart.org/content/minecraft-items )(SoCay)(CC0).  Oops.  It's the same bow as the other imperial archers.
