### ISSUE TITLE
Amazoness vigilance redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#161]
Amazoness vigilance redone using dress_009.png from stendhal repository, base-f-light.png from cabbit bases collection, Dancer-F-01 light.png from 24x32 characters pack extended by diamonddmgirl, and 
short sword [64x64] ( https://opengameart.org/content/short-sword-64x64 )(LordNeo)(CC0).
![ramavig](https://user-images.githubusercontent.com/37004874/39953421-9412e1b4-5579-11e8-80cc-accecd364659.png)
![ramavignowpn](https://user-images.githubusercontent.com/37004874/39953424-96118132-5579-11e8-8301-32dcba57a14f.png)
![amavigwpn](https://user-images.githubusercontent.com/37004874/39953427-9d318566-5579-11e8-8a54-26d9ae2c51f4.png)

**Comment by olonu** [comment]
Sara Beth(woman_013_npc.png) redone using base-f-light.png from cabbit bases collection and dress_091.png and hair_028.png from stendhal repository.
![rsarabeth](https://user-images.githubusercontent.com/37004874/39954366-54a6320c-558c-11e8-8523-37ba0c177ea3.png)

**Comment by olonu** [comment]
Albino elf king redone using elf-m-ash.png from cabbit bases collection, King_01 light.png and Mask-M-01 light.png from 24x32 characters pack extended by diamonddmgirl, and Collection of Rune Stones, Seamless Tiles ( https://opengameart.org/content/collection-of-rune-stones-seamless-tiles )(ztn)(CC0).
![raelfki](https://user-images.githubusercontent.com/37004874/39956306-b6561408-55ab-11e8-82cb-14d056314fdd.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 751f57a, deb10ca, & 4028f89
