### ISSUE TITLE
Dark gargoyle candidate...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#162]
It's not exactly the right style, but here it is.
Dark gargoyle redone using LPC Lizard Headgear ( https://opengameart.org/content/lpc-lizard-headgear )(Nila122) and Drakes and lizardfolk ( https://opengameart.org/content/drakes-and-lizardfolk )(Nila122).
![rdgarg](https://user-images.githubusercontent.com/37004874/39963006-d22f3434-562d-11e8-8d2a-ca546953bf76.png)
![rdgarg1](https://user-images.githubusercontent.com/37004874/39963007-d4271608-562d-11e8-85f7-e325a118336f.png)
![rdgarg2](https://user-images.githubusercontent.com/37004874/39963008-d5727d5e-562d-11e8-8cdc-f33fef4d51c0.png)
If this is ok, tell me which horns to go with, so I can conform the others in this group.

**Comment by AntumDeluge** [comment]
Hey, this looks really good.

I think I like the last horns the best.

**Comment by olonu** [comment]
Ok, all 4 are done.  There's a slight error in the previous 3 posted pics, still holding a little color left over from the drakes, but I've fixed it now in dark gargoyle.  The others do not have this error.  It would have been noticeable on regular gargoyle.

**Comment by AntumDeluge** [comment]
They look great @olonu. I will go ahead & close this now.
