### ISSUE TITLE
Elder duergar redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#164]
Elder duergar redone using current dwarf set and Townfolk-Adult-M-009 light.png and Fighter-M-02 light.png from 24x32 characters pack extended.
![rduerel](https://user-images.githubusercontent.com/37004874/40027768-85953baa-57a9-11e8-8ff4-898ff56ab934.png)

**Comment by olonu** [comment]
Duergar wizard is the other one that uses this type armor.  I need a nice necklace that can hold a medallion, clock, etc.

**Comment by AntumDeluge** [comment]
Yes, the beard actually blocks a lot. If you look at the newer dwarves that I recently created, you'll notice that I trimmed the beard back a bit on the sides so it wouldn't cover the shoulders of the armor:

![dwarf](https://raw.githubusercontent.com/arianne/stendhal/cc32adac308e96bd196df4aa9479ecf3f9610b3f/data/sprites/monsters/dwarf/dwarf.png) compared to ![hero dwarf](https://raw.githubusercontent.com/arianne/stendhal/a8c5b1570b8b4614bda2523f51022d9d4ad16cd5/data/sprites/monsters/dwarf/hero_dwarf.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: a42df2c

**Comment by AntumDeluge** [comment]
The rest of the dwarves' sources can be found here: https://opengameart.org/node/83728
