### ISSUE TITLE
Imperial knight redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#165]
Imperial knight redone using current royalguardnpc's hat and dress_012 and Scimitar [64x64] ( https://opengameart.org/content/scimitar-64x64 )(LordNeo)(CC0).
![rimpkniwpn](https://user-images.githubusercontent.com/37004874/40167598-70edc48c-598f-11e8-9416-a8960187d725.png)
Some work...
![base-m-light copy 1](https://user-images.githubusercontent.com/37004874/40167617-7c5aa45c-598f-11e8-9e80-c2f66fed71ef.png)
![base-m-light copy 1 copy 1](https://user-images.githubusercontent.com/37004874/40167622-800fd586-598f-11e8-97d1-72917f84bb80.png)
![base-m-light copy 1 copy 2](https://user-images.githubusercontent.com/37004874/40167625-828bac22-598f-11e8-93c1-cfecbb2eddbc.png)
![dress_012 copy 1](https://user-images.githubusercontent.com/37004874/40167635-8758b484-598f-11e8-89b4-f48bc1794743.png)
![rimpkni](https://user-images.githubusercontent.com/37004874/40167650-8f4bb952-598f-11e8-9e50-99c0ac4fbecd.png)
![w_scimitar_blood](https://user-images.githubusercontent.com/37004874/40167686-a6caddba-598f-11e8-8494-3c35de5578b0.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 06fa40c
