### ISSUE TITLE
Amazoness elite coastguard redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#166]
Amazoness elite coastguard redone using Ranger-F-01 light.png and Pirate-F-01 light.png and anchor ( https://openclipart.org/detail/292353/anchor-sign )(dwtoch).
![ramelico](https://user-images.githubusercontent.com/37004874/40223612-aaede17c-5a51-11e8-96aa-388e8a355141.png)

**Comment by olonu** [comment]
Kirla(photographernpc.png) redone using base-f-light.png, dress_017.png, and hair_019.png.
![rphoto](https://user-images.githubusercontent.com/37004874/40225738-e2ce7902-5a57-11e8-8c46-c3fa525561a1.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 16f8f2b & 8f848a0
