### ISSUE TITLE
Elephant Concept

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#167]
Just wanted to show the work I am doing on the elephant sprite. It is based on [lawnjelly's Jungle Creatures](https://opengameart.org/node/59627):

![preview-concept](https://user-images.githubusercontent.com/3631473/40226033-8617424c-5a3f-11e8-9287-12f4b8a785da.gif)

**Comment by AntumDeluge** [comment]
Some more work: ![preview-concept](https://user-images.githubusercontent.com/3631473/40274291-db75b13a-5b87-11e8-8181-891333132ee3.gif)

![elephant-redo-96x96](https://user-images.githubusercontent.com/3631473/40274292-e59b959e-5b87-11e8-9af8-420c8eb68bb6.png)

**Comment by balaur64** [comment]
I think it looks good from front and back.
However, from the side it's not consistent with the other sprites in Stendhal. All others are viewed exactly from the side, while this elephant is viewed a bit from above. I mean the ear in the back shouldn't be visible, and the two feet in the background should be on the same line as the feet in the foreground.

**Comment by AntumDeluge** [comment]
Final version:

![preview](https://user-images.githubusercontent.com/3631473/40333110-9c5faffc-5d0b-11e8-8115-f0fc6139beba.gif)

The rear ear is still slightly visible, but I like it.
