### ISSUE TITLE
dress_056 question?

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#169]
I really like this dress, as I used to use it a lot.  I would also consider it for the remaining priest sprites.
![dress_056](https://user-images.githubusercontent.com/37004874/40336975-d28687e8-5d3a-11e8-9dd7-cce1b48df64e.png)
![dress_056a](https://user-images.githubusercontent.com/37004874/40336977-d4070732-5d3a-11e8-87a3-403c9ff9ab5c.png)
The following image is 025-cleric01.png from rpg maker xp rtp.
![025-cleric01](https://user-images.githubusercontent.com/37004874/40336973-cf474374-5d3a-11e8-8518-5b3f6a97aae1.png)

**Comment by AntumDeluge** [comment]
Darnit. It's gotta be replaced. I had my doubts about it, but the original commit message said it was by bleutailfly. So I thought it was okay. Now I'm going to need to check the other submissions by him/her.

**Comment by olonu** [comment]
055 looks homemade, but I think it's in something too.  I forgot where, but I did see it.  I may have mentioned it the last time I mentioned 056.

**Comment by AntumDeluge** [comment]
I plan on attempting to contact bleutailfly, & some other contributors, sometime after next release to verify that their work is original & confirm licensing for them.

I'm sure there are some more that will need replaced in the future.

**Comment by AntumDeluge** [comment]
Re-drawn: 49017cb
