### ISSUE TITLE
Morgrin Gives Strange Reply While Quest is Active

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#196]
[Morgrin](https://stendhalgame.org/npc/Morgrin.html) seems to give an unusual response to ***task/quest*** if [Kill Spiders quest](https://stendhalgame.org/quest/kill_spiders.html) is active:

> [13:37] <deluge> hi
[13:37] <Morgrin> Hello my friend. Nice day for walking isn't it?
[13:37] <deluge> quest
[13:37] <Morgrin> Would you like to help me again?
[13:37] <deluge> yes
[13:37] <Morgrin> Fine. Go down to the basement and kill all the creatures there!
[13:37] <deluge> quest
[13:37] <Morgrin> Thanks for your help. Now I'm sleeping well again.

It's different than the response he gives after quest is completed:

> [13:40] <Morgrin> Sorry there is nothing to do for you yet. But maybe you could come back later. I have to clean the school once a week.

[*(mirrored on SourceForge)*](https://sourceforge.net/p/arianne/bugs/5895/)

**Comment by cosminhume** [comment]
The `KillSpiders` quest uses the states:

- `started` when in progress
- `killed` when done

`Player::isQuestCompleted` checks whether the state starts with `done`.

Therefore it won't be `true` and I think this part here needs to be adjusted:
https://github.com/arianne/stendhal/blob/a0df62244fc1954a05136c9550d3e7475ed037b0/src/games/stendhal/server/maps/quests/KillSpiders.java#L87-L89

A condition similar to the one in [KillDhohrNuggetcutter](https://github.com/arianne/stendhal/blob/a0df62244fc1954a05136c9550d3e7475ed037b0/src/games/stendhal/server/maps/quests/KillDhohrNuggetcutter.java) might solve the issue:
https://github.com/arianne/stendhal/blob/a0df62244fc1954a05136c9550d3e7475ed037b0/src/games/stendhal/server/maps/quests/KillDhohrNuggetcutter.java#L94-L97
