### ISSUE TITLE
Aliasing Items & Entities

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#200]
As I understand it, items & entities are identified by their names, which are static. This makes it virtually impossible to rename anything. If the engine/game could understand aliases, it might be possible to rename some things when we feel it might be necessary.

[*(mirrored on SourceForge)*](https://sourceforge.net/p/arianne/feature-requests/1437/)

**Comment by nhnb** [comment]
Renaming items is handled in `games.stendhal.server.entity.player.UpdateConverter`.
