### ISSUE TITLE
HP Bar Position Does Not Update When Client Scaling Enabled

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#202]
When the "*Scale view to fit window*" setting is enabled in the client, once the window is actually scaled, HP bars positions no longer update.

![client_scaling-gui_setting](https://user-images.githubusercontent.com/3631473/46984646-0e1ba080-d09b-11e8-87cf-a6d138721da1.png)

I waited for the balrog to move offscreen so its HP bar was closer to its feet. Then I scaled the window & the HP remained in its position relative to the balrog. In the screenshot below, you can see the balrog's head, but the HP bar is near its feet, out of view of the client display.

![client_scaling-no_update_hp_bar](https://user-images.githubusercontent.com/3631473/46984745-8bdfac00-d09b-11e8-89e6-19cddc93a0e7.png)

[*(mirrored on SourceForge)*](https://sourceforge.net/p/arianne/bugs/5897/)

**Comment by nhnb** [comment]
Was this fixed by 3a26beaee9f542c523d49bf83d78a36a6a29b3a2?

**Comment by kiheru** [comment]
Yes, this is a duplicate report. The one on SF was already closed.
