### ISSUE TITLE
Browser Right-Click Menu Interferes With Web Client Menu

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#206]
Not sure how it works, but I'm guessing web browser's menu should be disabled on this page? Or just on client display area?

![web_client-right_click](https://user-images.githubusercontent.com/3631473/47052697-551e9a00-d15e-11e8-94dc-d0b2546ee0df.png)

**Edit:** Using Chrome 69.0 on Windows 10 64-bit.

**Edit:**
---
Works correctly in Microsoft Edge:
![web_client-right_click-edge](https://user-images.githubusercontent.com/3631473/47053112-708aa480-d160-11e8-9b24-81db419c3fc1.png)

**Edit:**
---
Firefox behavior on Windows is same as Chrome:
![web_client-right_click-firefox](https://user-images.githubusercontent.com/3631473/47053525-37533400-d162-11e8-9d39-30cb8964bd66.png)

[*(mirrored on SourceForge)*](https://sourceforge.net/p/arianne/bugs/5902/)

**Comment by nhnb** [comment]
You can long click with the left mouse button.

**Comment by nhnb** [comment]
I think, I fixed the issue. But someone on Windows needs to confirm

**Comment by AntumDeluge** [comment]
Thanks @nhnb, I will check it out when I get a chance.

**Comment by AntumDeluge** [comment]
Still occurring, same behavior in test webclient.

**Comment by AntumDeluge** [comment]
Fixed with commit: 6b35d49
