### ISSUE TITLE
Old map tiles are rendered after being teleported to a smaller zone

### ISSUE THREAD

**Issue by markuskeunecke** [arianne/stendhal#208]
With the current release parts of the previous map are still drawn after being teleported to a smaller zone.

I was able to reproduce it by visiting the vault in semos as shown in the attached screenshot.

![screenshot-vault-semos-bank](https://user-images.githubusercontent.com/3355613/47456490-ff3c9880-d7d4-11e8-9041-85eb9f280a19.png)

**Comment by AntumDeluge** [comment]
Duplicate of #204.

**Comment by markuskeunecke** [comment]
Ah, thank you. I did not recognize the bug at first. :)
