### ISSUE TITLE
Web Client Not Very Mobile Friendly

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#211]
It is quite difficult to use the web client on a mobile devices with a small display. Moving character using the keyboard arrow is messy & touching a point to move causes the software keyboard to be displayed. There is much fuctionality missing as well, such as action menus for entities.

This is a short video demonstration of using the web client on an Android device:
[![Stendhal: Testing Web Client On Android Mobile](https://img.youtube.com/vi/P2gB7PzpOxk/0.jpg)](https://www.youtube.com/watch?v=P2gB7PzpOxk)

*([mirrored on SourceForge](https://sourceforge.net/p/arianne/developers/286/))*

**Comment by nhnb** [comment]
Duplicated of #57

**Comment by AntumDeluge** [comment]
Interesting. I must have forgotten that I made that report. Sorry.
