### ISSUE TITLE
Broken items must be logged

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#216]
When an items "breaks" due to alternative item deterioration implementation, the event must be logged.

**Comment by nhnb** [comment]
Removing release-blocker label as the only breakable item "training bow" is not in game at this time.

**Comment by AntumDeluge** [comment]
Do you just mean a message in the logger? Something like "<item name> with ID <id> broke"?

**Comment by markuskeunecke** [comment]
@AntumDeluge: @nhnb means logging of game events to our logging table gameEvents. See [GameEvent class](https://github.com/arianne/stendhal/blob/master/src/games/stendhal/server/core/engine/GameEvent.java)


`new GameEvent(source, event, params).raise()`

**Comment by AntumDeluge** [comment]
Forgive me, I'm just trying to understand. But what is the benefit of logging when an item breaks?

**Comment by AntumDeluge** [comment]
Please let me know if the logged message is acceptable in c2f1def728.
