### ISSUE TITLE
Missing sprite for Ortiv's house

### ISSUE THREAD

**Issue by cosminhume** [arianne/stendhal#220]
The sprite for Ortiv's house is missing and doesn't look pretty:

> You are in 0_kirdneh_river_w at (55,108)

![ortiv_house](https://user-images.githubusercontent.com/42698386/52180970-1daf2880-27f5-11e9-9a45-66c3990c8838.png)

Maybe a quick fix could be to reuse one of the dummy houses outside of Ados:

> You are in 0_ados_wall_n2 at (79,14)

![other_house](https://user-images.githubusercontent.com/42698386/52180971-1daf2880-27f5-11e9-8d17-3924d1334ec9.png)

**Comment by cosminhume** [comment]
This is the result of commit `ea20436` ("Replace non-free building tilesets with placeholder images").
I would like to fix this house. I already started, working with `building/house_pink_blue.png` as a new tileset in `river_w.tmx`. Still need to fit the windows on the first floor.
Current status:
![ortiv_house_wip](https://user-images.githubusercontent.com/42698386/53297128-1393af00-3822-11e9-919b-8ef6ff7fc6a6.png)

**Comment by bleutailfly** [comment]
oh that looks so much better

**Comment by AntumDeluge** [comment]
Fixed via #222.
