### ISSUE TITLE
Make Web Client Embeddable

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#226]
I recently came across an MMORPG similar to Stendhal called [Mystera Legacy](https://www.mysteralegacy.com/). They have a very interesting client that seems can be embedded into different applications.

If the same thing could be done with the Stendhal client, it would make it much more versatile. For players that don't want to use the "web client", it could be embedded into a simple application window on any supported mobile or desktop platforms.

*([mirrored on SourceForge](https://sourceforge.net/p/arianne/feature-requests/1443/))*

**Comment by nhnb** [comment]
I think PWA (Progressive Web App) is a better approach nowadays.
