### ISSUE TITLE
Repeatable marker wrong Find Rat Children and The Guessing Game

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#229]
by selenil on #arianne:

## 🐞 Describe the bug

Normally, repeatable quests get a marker (the unicorn shield symbol) in the Completed Quests tab of the Travel Log, when they are available for repeat. Two quests have their repeat markers incorrectly set.
- Find Rat Children repeat marker never comes on, even though the quest is repeatable. I have tested this.
- The Guessing Game repeat marker never goes off, even when the quest is not yet ready for a repeat. The marker stays on, as soon as the quest is completed, always.

**Comment by AntumDeluge** [comment]
Fixes applied in b711e4d457 & 49f7dd5010. Will close this issue soon after a little more testing & verification.
