### ISSUE TITLE
vampire.py fails with cannot open resource

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#231]
## 🐞 Describe the bug

The latest version of vampire.py fails with cannot open resource:

~~~~
stendhal/tiled$ python3 vampire_maplabel.py -world
Processing ./world/int_dreamscape_rural.png
Processing FNAME: ./world/int_dreamscape_rural.png
Traceback (most recent call last):
  File "vampire_maplabel.py", line 76, in <module>
    do_label('./world/' + fname)
  File "vampire_maplabel.py", line 51, in do_label
    font = ImageFont.truetype(fontPath, 12)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 261, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 144, in __init__
    self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine)
OSError: cannot open resource
~~~~

## 🔥 How to reproduce

1. On the command line, change into folder stendhal/tiled
2. execute `python3 vampire_maplabel.py -world`

## 🌍  Environment

latest git master

## 🔭 Additional information

This version works fine:
https://raw.githubusercontent.com/arianne/stendhal/15761851d2c8cf8c23a5b2b0c7003855236e7942/tiled/vampire_maplabel.py.2019-09-10.1

**Comment by AntumDeluge** [comment]
Does the same error occur when executed with `python2`?

**Comment by nylon0700** [comment]
The problem with the ´cannot open resource´ is  most likely due to vampire_*.py script
trying to ¨use¨ a specific font for rendering.

The script IS NOT devised to be ¨smart¨ enough to retrieve a font name automagically
from the system, there is no easy solution unless one does ´manually´ tailor the script for
a good path where to look for the desired ´somefont.ttf´

/usr/share/fonts is a good location to start looking.

The ´original´ vampire_maplabel.py is ages old...
Uses syntax related to a now deprecated and no longer maintained PIL module.

PIL is replaced by Pillow, wich does its best to keep backward compatibility with PIL.
In theory Pillow module would work in python2, but it was developed for python3.
Much of the syntax in python2/python3 has changed in the course of 10+ years...
The shebang is there to enforce a sane interpreter (pyton3) that can understand PIL/Pillow
the way it works now and not 10+ years ago.

**Comment by AntumDeluge** [comment]
I suggest finding another [free/libre font](https://fontlibrary.org/) to bundle with the source code that the script can use.

**Comment by AntumDeluge** [comment]
Oh, I just looked at the source & *arial.ttf* is included in [tiled directory](https://github.com/arianne/stendhal/blob/2cacfc3d86e10682fca00fc22449a5f5f1c4295f/tiled). I'm not sure that's a good idea. It uses a proprietary license that I don't know if it is GPL-compatible. The old script was pointed to this included font file.

**Comment by nylon0700** [comment]
arial.ttf needs not be bundled/included/referenced whatsoever.

just edit script to use a ´sane´ font with a ´simplesomefont.ttf´

the ´simplesomefont.ttf´ has to be in the system path.

the script has to be instructed about

a) the path where to look for fonts

b) the simplesomefont.ttf


script will then do ´the dirty job´.

**Comment by AntumDeluge** [comment]
The script can also use fonts given with a relative or absolute path. So it's not necessary that they reside in a standard directory. The good thing about bundling a font (like the way Arial currently is) guarantees that the output labels always use the same font, regardless of who or on which system the script is run as System fonts on one user's computer are not guaranteed to be installed on another's.

**Comment by nhnb** [comment]
That  font file was committed by accident. I just deleted it again.

But even with this font file, the issue remains: vampire.py crashes, vampire_maplabel.py.2019-09-10.1 works.

**Comment by AntumDeluge** [comment]
Does this work for you @nhnb: https://github.com/AntumDeluge/arianne-stendhal/commit/a61f171c569432573310db32e2894daca1509ebd

**Comment by nhnb** [comment]
If I execute the script in stendhal/tiled, I get the error message that an empty directory name does not exist:

~~~~
~/workspace/stendhal/tiled$ python3 vampire_maplabel.py -world
Traceback (most recent call last):
  File "vampire_maplabel.py", line 38, in <module>
    os.chdir(dir_root)
FileNotFoundError: [Errno 2] No such file or directory: ''
~~~~

If I execute it from the Stendhal root folder, it can open the mal files (although it somehow found them):

~~~~
hendrik@computer:~/workspace/stendhal$ python3 tiled/vampire_maplabel.py -world
Processing /home/hendrik/workspace/stendhal/tiled/world/int_dreamscape_rural.png
Processing LABEL: int_dreamscape_rural
Traceback (most recent call last):
  File "tiled/vampire_maplabel.py", line 88, in <module>
    do_label(absolute_fname)
  File "tiled/vampire_maplabel.py", line 65, in do_label
    font = ImageFont.truetype('Carlito-Regular', 12)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 261, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 144, in __init__
    self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine)
OSError: cannot open resource
~~~~

**Comment by AntumDeluge** [comment]
Oh, darnit. I know what the problem is. I forgot to test for that. I will fix it.

**Comment by AntumDeluge** [comment]
Note that you can now execute the script without directly calling `python3`. E.g.:

```
./vampire_maplabel.py -world
```
...instead of:
```
python3 vampire_maplabel.py -world
```
