### ISSUE TITLE
Big Boss Monster "blue phantom"

### ISSUE THREAD

**Issue by Megajack64** [arianne/stendhal#234]
## 💡 Describe your idea

A new big boss. For snowed areas, or abandoned, scary areas.

Anything else

![BlPhantom](https://user-images.githubusercontent.com/55405437/65000358-eaffff00-d8b0-11e9-8d3d-786fb3c1c666.png)

**Comment by nylon0700** [comment]
Wow! Very nice sprite. It rivals with old style ones...

**Comment by bleutailfly** [comment]
did you make that yourself?

**Comment by Megajack64** [comment]
> did you make that yourself?

Yes. I did it some years ago inspired by some of my drawings when I was at school. He had done this before leaving the game for a while because of my work. 
It is inspired by a Mayan legend.

**Comment by nylon0700** [comment]
> > did you make that yourself?
> 
> Yes. I did it some years ago inspired by some of my drawings when I was at school. He had done this before leaving the game for a while because of my work.
> It is inspired by a Mayan legend.

how would be that licensed?

**Comment by nylon0700** [comment]
Added ingame
