### ISSUE TITLE
wanda the witch NPC <name>

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#238]
## 🙍‍♀️ Basic profile
she sells potions and sometimes needs ingredients to fill orders
* Name: ...wanda the witch
* Location: ..potions_shop in deniran. 
* Sprite: ...magicianhousegreeternpc

## 🗣 Chatting

Please list the interactions of player and NPC. You can mark blue trigger words with a $dollar sign.

Trigger | Response
---------|-------------
hi        |   Hello, and welcome to my potions shop
job      |   I am the local witch
offer    |   I sell ... / I buy ...at this moment I seem to have everything that I need, but check back later I may need some supplies.
...        |   ...

## 🍜 Additional notes
just getting npcs ready for release
* Ideas for quests: ...
* If the NPC should buy, produce or sell items, please list them here and suggest prices: ...
* Anything else

**Comment by kevinmody** [comment]
Hey, guys I really like the game you are working on. I would like to contribute to this repo and maybe help to fix some bugs, and help with a feature request.
