### ISSUE TITLE
Issues with Groongo Rahnnt

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#240]
## 🐞 Describe the bug

Groongo Rahnnt reacts to "hi" with a question, but does accept neither "yes" nor "no" as an answer.

[23:03] <Groongo Rahnnt> Gah! It was about time that someone showed up eventually! Are you ready to do your $task now?!
[23:03] <hendrikus> yes
[23:03] <hendrikus> no

----

After asking him for a dessert he prints macedonia and dessert in blue, but does not react to any of them:

[23:07] <hendrikus> dessert
[23:07] <Groongo Rahnnt> Indeed, I shouldn't have forgot that! With the kushari I will try a macedonia di frutta. Now go ask Chef Stefan to prepare my $macedonia for $dessert, at once!
[23:08] <hendrikus> macedonia
[23:08] <hendrikus> dessert

There are other situation, that I have not logged, when he seems to just stop talking to you.

----

He uses annoying spelling:

Hgh! HellooO?! I am wondering... Is there anyone ArOoUunNDd in HheReEeee?!

----

The quest requires a lot of items. I think about 7 different items for the meal, which takes up a lot of space in my bag. It may be okay, but it makes the quest quite difficult.

-----

And the amount of items seems extremely high. For example for one person dessert 49 apples, 19 bananas, 32 pears, and 22 watermelons are required.

**Comment by nylon0700** [comment]
removed rant with annoying spelling
adjusted required quantity for each ingredient in each recipe

by design (intentional):
main dish requires 7 ingredients
dessert requires 4 ingredients
ALL ingredients for main dish/dessert are required by chef stefan *at once*
ALL ingredients are easily available around the world, no rare stuff

**Comment by nylon0700** [comment]
This should be assigned

**Comment by nylon0700** [comment]
fixed all originally reported issues
