### ISSUE TITLE
Kobold drop too many slim/eared bottles

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#241]
## 🐞 Describe the bug

commit d7e99ae6622c995c489541fbbcaf78a0f4736af0 introduced drops of slim/eared bottles to Kobolds. Compared to other drops, the probability is extremely high. I am worried that such a high number of slim/eared bottles is not useful.

**Comment by nhnb** [comment]
related: too high drops of ugmash in commit 4092346cd7a03058599893235014a44acb7fa497

**Comment by AntumDeluge** [comment]
I believe the ugmash drop was an accidental commit. Not sure about the bottles. Ugmash is a special quest item & wasn't originally meant for enemy drops I believe.

**Comment by nylon0700** [comment]
slim|eared bottles drop rates adjusted in master

**Comment by nylon0700** [comment]
ugmash drop rates adjusted in master

**Comment by nylon0700** [comment]
> related: too high drops of ugmash in commit [4092346](https://github.com/arianne/stendhal/commit/4092346cd7a03058599893235014a44acb7fa497)

ugmash drop commit was not intended to mix up with other commits

**Comment by nylon0700** [comment]
Please redefine this as its own prolem,
several issues require separate addressing for resolution
