### ISSUE TITLE
player walking on upper layer

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#244]
![web client 1](https://user-images.githubusercontent.com/6003164/65893117-6e235980-e375-11e9-9349-3e8d2bcf4fff.PNG)
## 🐞 Describe the bug
web client-player walking on upper layers
A clear description of the issue.

## 🌍  Environment

[ ] Java client
[X] Web client

**Comment by nhnb** [comment]
The issue was caused by outfits being downloaded asynchronously using a JavaScript promise. 

This caused the drawing code to be delayed until after the map was completely draw.
