### ISSUE TITLE
corn grower

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#246]
## 💡 Describe your idea
would like to see growing corn,  taking corn to the mill in deniran, getting cornmeal.  and making cornbread at the bakery.  the chef there can make cornbread if you bring;
1 milk
2 sacks of cornmeal
1 egg
1 flour

A clear description of your idea
the king of deniran is craving pinto beans and cornbread.  

## 🔬 Motivation
 feed the hungry king
reward would be;  karma, some xp, and some money
A clear description of the background or motivation for the feature request. What problem is solved?

## 📝 Alternatives

A clear description of any alternative solutions or features you've considered.

## 🔭 Additional information
corn_field.png is already made, when player picks the corn, there is a icon of corn called "real_corn" might be better to say "ear of corn" maybe can have some food value.  maybe 40 hp 
![corn_meal](https://user-images.githubusercontent.com/6003164/66166633-d6886a00-e605-11e9-8a86-a8f0c7a4959a.png)  here is a recolored bag of cornmeal its a little darker than the flour.

Anything else

**Comment by nylon0700** [comment]
corn fields active
all else is optional
