### ISSUE TITLE
maybe unexpected behaviour on item: summon pet scroll

### ISSUE THREAD

**Issue by Redcxx** [arianne/stendhal#247]
I think the code [here](https://github.com/arianne/stendhal/blob/master/src/games/stendhal/server/entity/item/scroll/SummonPetScroll.java#L95): 
````
String type = getInfoString().replaceAll("_", " ");
if (type == null) {
  // default to cat, if no other type is specified
  type = "cat";
}
````
should be
````
String type = getInfoString();
if (type == null) {
  // default to cat, if no other type is specified
  type = "cat";
} else {
  type = type.replaceAll("_", " ");
}
````
otherwise player will lose the item with server encountering a `Null Pointer Exception`

**Comment by nhnb** [comment]
Thank you for your fix.
