### ISSUE TITLE
sounds for players being attacked

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#248]
## 💡 Describe your idea

A clear description of your idea
need a sound when players are getting attacked.  these sounds where made by antumdeluge and are cco
https://opengameart.org/content/thwack-sounds
## 🔬 Motivation
 
A clear description of the background or motivation for the feature request. What problem is solved?

## 📝 Alternatives

A clear description of any alternative solutions or features you've considered.

## 🔭 Additional information

Anything else

**Comment by AntumDeluge** [comment]
@bleutailfly Let me know if you don't like any of those sounds. I wasn't sure about all of them. I won't be offended if you want to remove any of the ones I made.
