### ISSUE TITLE
lucky charms can't stack in bags

### ISSUE THREAD

**Issue by hly444** [arianne/stendhal#250]
## 🐞 Describe the bug

A clear description of the issue.

lucky charm can all store on keyring in one slot, but can't stack in bag.

**Comment by nhnb** [comment]
Is this really related to bag vs. keyring? Or are there different types for lucky charms. For example one may be a quest reward and the other one may not be. Do they have the same text on "Look"?

**Comment by hly444** [comment]
what I mean is same type of lucky charms can't stack in bags, but is stackable on the keyring.
