### ISSUE TITLE
Tiled: Missing "resources.png" in 0_fado_forest_s

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#255]
## 🐞 Describe the bug

It appears the path to "tiled/tileset/logic/item/resources.png" has been messed up in "tiled/Level 0/fado/forest_s.tmx".

![fado_forest_s_missing_resources_logic](https://user-images.githubusercontent.com/3631473/66712534-ec5b0500-ed52-11e9-8bc5-fef52482770d.png)

Should be a simple fix.

**Comment by nylon0700** [comment]
corrected offending path

**Comment by nylon0700** [comment]
$diff forest_s.2019-11-04.orig.tmx forest_s.orx.2019-11-04.0.tmx
106c106
<   <image source="../../../../../../90_ECLIPSE/stendhal/tiled/tileset/logic/item/resources.png" width="192" height="32"/>
---
>   <image source="../../tileset/logic/item/resources.png" width="192" height="32"/>

**Comment by nylon0700** [comment]
Ok, once more:


[omero@naldvras:~/tmp]
$diff forest_s.2019-11-04.orig.tmx forest_s.orx.2019-11-04.0.tmx
106c106
<   <image source="../../../../../../90_ECLIPSE/stendhal/tiled/tileset/logic/item/resources.png" width="192" height="32"/>
---
>   <image source="../../tileset/logic/item/resources.png" width="192" height="32"/>

**Comment by nylon0700** [comment]
[omero@naldvras:~]
$diff tmp/forest_s.2019-11-04.orig.tmx tmp/forest_s.orx.2019-11-04.0.tmx
106c106
<   <image source="../../../../../../90_ECLIPSE/stendhal/tiled/tileset/logic/item/resources.png" width="192" height="32"/>
---
>   <image source="../../tileset/logic/item/resources.png" width="192" height="32"/>

**Comment by AntumDeluge** [comment]
Fixed via r5eefb4
