### ISSUE TITLE
StrandedWitchNPC/StrandedWizardNPC issues

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#259]
## 🐞 Describe the bug

- StrandedWitchNPC answers to help, offer and job with the same text
- StrandedWitchNPC does not have a name, but is called "StrandedWitch"
- StrandedWizard answers to help, offer and job with the same text
- StrandedWizard does not have a name, but is called "StrandedWizard"

**Comment by nylon0700** [comment]
Both Stranded(wizard/witch) names are related to AdMemoriaInPortfolio quest
Names for StrandedWizard/StrandedWitch will be finalized once AdMemoriaInPortfolio quest is stable

**Comment by nylon0700** [comment]
StrandedWizardNPC proper name Brosoklelo
StrandedWitchNPC proper name Blasyklela

**Comment by nylon0700** [comment]
Proper names assigned to both StrandedWizardNPC/StrandedWitchNPC
Further issues should be adressed in separate reports, please
