### ISSUE TITLE
AdMemoriaInPortfolio gives a ridiculous amount of items as reward

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#260]
## 🐞 Describe the bug

AdMemoriaInPortfolio rewards the player with both a two high number of different items and a  two orders of magnitude too high amounts of those items.

**Comment by nylon0700** [comment]
AdMemoriaInPortfolio quest is currently being tested.
The reward quantities is intentionally set to 1000

The reward quantities will be set to something more reasonable once the quest is stable

**Comment by nylon0700** [comment]
reward quantities are now fixed
