### ISSUE TITLE
Portfolio does not work in webclient

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#261]
## 🐞 Describe the bug

Portfolio does not work in webclient

**Comment by nylon0700** [comment]
Is this referring to the quest, the item provided by the quest or something related?

**Comment by nylon0700** [comment]
question: webclient. is it stable for release yet?

**Comment by nylon0700** [comment]
Ad Memoria In Portfolio quest disabled
No way found to add a portfolio slot (keyring-like)
