### ISSUE TITLE
need some eyes on web client, can't see where i'm going.

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#262]
## 🐞 Describe the bug

need eyes, cant see where im going

![need eyes, cant see where im going](https://user-images.githubusercontent.com/6003164/67883414-70b2d380-fb1a-11e9-9c6d-adb11aa2c578.PNG)

**Comment by AntumDeluge** [comment]
This should be fixed with commit 6fa1813a59.

**Comment by bleutailfly** [comment]
got eyes now
