### ISSUE TITLE
Ice Shield (new Item for the game)

### ISSUE THREAD

**Issue by Megajack64** [arianne/stendhal#265]
## 💡 Describe your idea

One shield whit medicinal propierties.

## 🔬 Motivation
 
Adition of new items for the game, whit some special powers.

## 🔭 Additional information
I like this features:

Dropped from: Legendary Ice elemental. whit 0.5%
Defense: 40
Minimal level to use: 50
Aditional atributes: You will not be poisoned while using this shield.

##Archive
![Ice_Shield](https://user-images.githubusercontent.com/55405437/68778544-f3e32780-05f8-11ea-9e8b-6d2af106f175.png)

Anything else
If the petition is accepted  and one licence is requered use the " CC-BY" Licence.

**Comment by nylon0700** [comment]
Adding the item itself would not be such a big issue. That icon/sprite looks very good.
The problem I see is implementing that ´peculiar´ anti-venom property...

**Comment by Megajack64** [comment]
> Adding the item itself would not be such a big issue. That icon/sprite looks very good.
> The problem I see is implementing that ´peculiar´ anti-venom property...

Can't add the property of the medicinal ring?
Some weapons have 3 attributes. (attack, level of use and life steal).

**Comment by AntumDeluge** [comment]
Adding anti-poison isn't a problem anymore. The issue that is going to come up (as did with the rings) is whether or not it is a good idea to make players 100% invulnerable to poisoning. As new status effects & new items are implemented, invulnerability makes more sense because players will have choose equipment based on what they want to resist (e.g., if they want to wear a ring that protects them from shocked status, they are still susceptible to poisoning).

Up until recently, poisoning was the only status effect. So a single item that allowed players to be completely resistant to poison made the game too much easier.

**Comment by Megajack64** [comment]
The game is already quite difficult, especially for new players.

If you want to limit the benefit that the shield would have, it is very easy to compensate for the problem.

Remember that it is an ice shield. So you can make it disappear when you enter hell by saying something like:
"The infernal heat has destroyed your ice shield"

You can also make it disappear in 3 days and say something like this:

"The heat of your body has melted the ice shield"

The destruction of the ice shield can be given by using it and having it in the backpack.

Destruction can also occur using both conditions. Entering hell and having it 3 days.

This will make the benefit for a limited time unlike the ring.

If you want to limit the benefit and have the player control it. You can put time of use of 12 hours, which 
would only be effective when you put the shield in the slot 
and the time would stop when it is in the backpack. Time would be in reverse and the shield would disappear at the end of time.

The latter would give many modifications, so I do not think it is possible.

**Comment by AntumDeluge** [comment]
[Ice shield added](https://github.com/arianne/stendhal/commit/e0d29603476fa5bb0751e9e39e58da5734382832).

- Dropped by legendary ice elemental at 0.5%.
- DEF: 40
- ice susc.: 0.9
- fire susc.: 1.15
- poison resist: 50%
- min. level: 110
