### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MBoberski** [arianne/stendhal#281]
Hello,

sorry if my question is stupid, but I was unable to find answer for it. Is there a way to compile client to web, javascript version. And if it is then how to do it?

TIA
Martin

**Comment by nhnb** [comment]
Hi Martin,

please see https://stendhalgame.org/wiki/Navigation_for_Stendhal_Builders_and_Hosters for general information about building a distribution and using an IDE.

https://stendhalgame.org/wiki/How_to_setup_a_Stendhal_webclient_development_environment has information specific to the Stendhal web client and https://stendhalgame.org/wiki/Marauroa_Chat_Tutorial/HTML5_Client has information for developing a web client for your own game.
