### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by MBoberski** [arianne/stendhal#284]
Hi,
I was following https://stendhalgame.org/wiki/Stendhal_on_Eclipse and when I try to start server I get:

![image](https://user-images.githubusercontent.com/2800036/70397449-9c2ab700-1a12-11ea-8282-3c8c495d39d4.png)

What could be a problem?

Martin

**Comment by AntumDeluge** [comment]
It looks like you need to add the Stendhal root directory to your classpath.

**Comment by AntumDeluge** [comment]
In your run configurations, go to the tab labelled "Classpath". Select "User Entries", then press the "Advanced..." button. Then select "Add folders" & locate the Stendhal project directory. You should end up with something that looks like this:

![Eclipse Classpath Tab](https://i.postimg.cc/6QWwhSZ2/eclipse-classpath-tab.png)

**Comment by MBoberski** [comment]
![image](https://user-images.githubusercontent.com/2800036/70398318-70133400-1a1a-11ea-8be8-59c6341e0b7b.png)
I already had that

**Comment by MBoberski** [comment]
Ok I re-added server config ant it worked. I have one more small question:

![image](https://user-images.githubusercontent.com/2800036/70398466-16ac0480-1a1c-11ea-8c5b-6ddb58024cc4.png)

I have that empty skin on web client, is that a bug or WIP?

**Comment by MBoberski** [comment]
![image](https://user-images.githubusercontent.com/2800036/70398492-5672ec00-1a1c-11ea-90ba-32403158e0e6.png)

And this is from desktop client.

**Comment by AntumDeluge** [comment]
Ya, for some reason, you have to manually add the "stendhal" folder a second time.

The outfit layers missing on web client is a work-in-progress. We've added some new outfit parts layers (eyes, mouth, mask, & hat) for next release, but they have only been implemented in the desktop client so far.

**Comment by AntumDeluge** [comment]
But, I'm not sure why the character clothes aren't showing up in web client. Might be a new outfit that hasn't been ported to the web client yet.

**Comment by AntumDeluge** [comment]
It sounds as though this issue is resolved. So I will be closing it soon unless there is any other problem.
