### ISSUE TITLE
Harold doesn't inform me about examine

### ISSUE THREAD

**Issue by JensKorte** [arianne/stendhal#285]
## 💡 Describe your idea

When asking Harold for help in buying I get no information about the command examine _<number>_.
At the end of harolds answer to buying there should be a sentence like "To get more details about a product  use examine _number_ after show."

## 🔬 Motivation
 
Especially as a new user to stendhal you don't know the details of the blue, chaos, anything tag and need more details.

**Comment by AntumDeluge** [comment]
Thank you for this request. I will get this implemented.

**Comment by AntumDeluge** [comment]
Harold now shows info about ***examine*** command/keyword when asking for ***help*** about ***buying*** or ***selling***: f25f637
