### ISSUE TITLE
stendhal contains non-free sprites

### ISSUE THREAD

**Issue by Zefk** [arianne/stendhal#29]
I have discovered over 60 RPG Maker 2003 edits or resizes and a few RPG maker XP edits. RPG maker sprites are only allowed in RPG maker engines that one has purchased. They are not opensource.

You should honestly download the RPG Maker RTP packs and check for more. I will list the folder directory name and files. It is a RPG Maker 2003 edits unless I mention RPG Maker XP. All I ask is that you inform me of more edits character wise. I only checked the characters.

**/monsters/amazon:**

-amazoness_archer_commander
-amazoness_commander

**npc/animal:**

-dog
-Small_dog
-kitten

**/monsters/animal:**

-Slimes (all of them)
-Tiger
-lion

**/monsters/farm_animals:**

-Chick
-Cow
-Bull
-Ram
-White horse
-Horse
-beaver (XP Edit)

**/monsters/flying_beast:**

-bluebird
-carnary
-pink_bird
-green_bird
-Peach_bird
-red_brid
-seagull

All the birds are rmxp edits.

**/monsters/minotaur:**

-Mino_king
-Minotaur

**/monsters/sheepmen:**

-All of them are edits

**/monsters/golem:**

-stone_golem

**/monsters/huge_animal:**

-chaos_green_dragonrider
-chaos_red_dragonrider
-red_dragon
-Green_dragon
-Black_death
-Golden_Death
-flying_golden_dragon
-twin_head_dragon

**/monsters/human:**

-littlewizard
-armored_leader
-armorer_leader
-armored_warrior
-super_human
-soldier_wizard (hat)

**/monsters/myhical_animal:**

-gashadokuro

**/monsters/troll:**

-red_troll
-Troll

**/monsters/undead:**

-Ghost
-Death

**/npc:**

-boynpc
-chessplayernpc
-Childnpc
-deadmannpc
-gardenernpc
-man_000_npc
-man_006_npc
-oldmannpc
-princessnpc
-Mothernpc
-armorleadernpc
-Kingnpc
-kingcozartnpc
-woman_003_npc
-youngkingnpc
-stormtroopernpc

**/npc (Can be debated on:)**

Some features look like edits or resizes.

-mithrilforgernpc (hat)
-plinknpc (hair)

**Other: (two sprites on one spritesheet)**

-cat.png (big cat is okay, little cat is an edit.)

**monsters/ent:**
-dead_ent

![browntree](http://i.imgur.com/bNw3VzQ.png)

The dead ent is an edit of the brown tree here:
http://www.hbgames.org/forums/viewtopic.php?t=78803&p=929850

**Comment by nhnb** [comment]
Thank you for the report. I immediately deleted all those file and some more from Git as a stop-gap messure, although I did not have time to look at most of them in detail so far. We will do a release soon without those files.

All of the listed files have in common, that they are not original Stendhal artwork. But they are from charas and mirage, where they have been (I fear illicitly) labeled as either public domain, CC0 or GPL.

**Comment by Zefk** [comment]
> Thank you for the report.
You are welcome.

**Comment by AntumDeluge** [comment]
- stone_golem: #48
- gashadokuro: #49

**Comment by AntumDeluge** [comment]
-cat.png (big cat is okay, little cat is an edit.)
Actually, the big cat is distributed with addon package for RPG Maker 2000 runtime (https://2drpg.com/2000.php), so it needs to be removed as well.
