### ISSUE TITLE
Auto selling for selectable items

### ISSUE THREAD

**Issue by JensKorte** [arianne/stendhal#291]
## 💡 Describe your idea

If I fight the creatures, I often find the same things, especially items which are too low level or weak to me.  
It would be nice, if I could configure for every item if I want to autosell it as soon as I say Hi to a NPC that buys it. 

## 🔬 Motivation

In the gnome village I often get a leather armor. Every time I have to say Hi to garbiddle, ask to sell x leather armor and answer with yes. 

## 🔭 Additional information

It could also be possible to enable this after e.g. Level 10 after solving a special quest.

**Comment by AntumDeluge** [comment]
Perhaps something more universal would be to support creating custom macros.

**Comment by AntumDeluge** [comment]
Closing in favor of #685
