### ISSUE TITLE
webclient issue

### ISSUE THREAD

**Issue by tigertoes13** [arianne/stendhal#294]
i signed onto test last night has had an extra set of eyes... could not get rid of them, so perhaps there should be a blank set of everything for rectifying that problem... keep in mind, i had my alien body which has all the things which are necessary plus the hair... my normal main game getup
nothing else to say

**Comment by AntumDeluge** [comment]
Ya, the problem is that the alien outfit has static eyes built into the head. Because your outfit is custom, you will need an admin to remove the eyes layer. If we make a blank set of eyes, players can run around without eyes.

**Comment by AntumDeluge** [comment]
We could make the alien eyes non-static, but you would still need an admin to set it for you.

**Comment by AntumDeluge** [comment]
The issue is similar for your hair. Your character is stuck with hair_036 unless an admin/GM changes your outfit on main server. The only other way to change your hair without changing your outfit is if we change the hair_036 sprite in a future release. But that would affect the outfits of all players using that hair on main server.

**Comment by AntumDeluge** [comment]
If I did it correctly, eyes can be set to "-1" by an admin to make them "blank". But regular players cannot do this.

**Comment by tigertoes13** [comment]
i just noticed that you had written this stuff... i was never notified by email that you had... and promptly gave up...
will ask that someone make the change, as being a 4-eyes is ok if i am wearing glasses, but tigertoes is so tired of having 4 eyes ingame :D  thanks deluge... and i have a replacement hair that i have to test... but my desktop is still waiting to be setup after the power supply incident... will let you guys know :)
