### ISSUE TITLE
butterflies stuck

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#299]
## 🐞 Describe the bug

A clear description of the issue.
butterflies need that thing that npcs use when they walk into a none moving object  there is a butterfly stopped on the side of a building, kinda looks dead.

## 🔥 How to reproduce

3. See error

## 🌍  Environment

[ ] Java client
[ ] Web client
Location in game: ...

## 🔭 Additional information

Anything else

**Comment by AntumDeluge** [comment]
The butterfly's path in Semos Plains N is fixed on test server: 2cfe729ff7be30d103bef7cf6bd62201fb3ab841

**Comment by AntumDeluge** [comment]
Tested on test server. Butterfly's path is now fixed.
