### ISSUE TITLE
Web Client: Can't Use Double-Click nor Right-Click Menu with Mobile Browsers

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#300]
Mobile web browsers reserve double-click/double-tap for zooming on web page. Haven't found a setting to disable it, so using double-taps to interact with the game screen currently isn't possible.

Also, there is no way to open entity context menu (normally right-click with a mouse/cursor) with touch screen. Touch screens generally use a long press to bring up context menus. Long press does work for moving items on the screen, but it does not for opening entity context menus.

Tested on Android with Chrome & Firefox browsers.

*([mirrored on SourceForge](https://sourceforge.net/p/arianne/bugs/5963/))*

**Comment by nhnb** [comment]
Long pressing is supposed to work. But there are multiple instances of this error in the log:

`Uncaught ReferenceError: timestampMouseDown is not defined`

**Comment by nhnb** [comment]
Touching something for half a second should trigger right-click action handling such as the popup menu
