### ISSUE TITLE
Review drop changes

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#301]
We need to do a review of the changes to creature drops to verify that they are all well thought of and do not result in flooding of valuable or non-stackable items.

And ideally the drops should make sense for the kind of creature which drops them.

[Changes since 1.30 until 2019-12-26](https://stendhalgame.org/temp/drop.html)

- [x] animal
- [x] elemental
- [x] giant
- [x] human_assassin
- [x] human_barbarian
- [x] human_blordrough
- [x] human_cannibal
- [x] human_imperial
- [x] human
- [x] insect
- [x] kobold
- [x] mutant
- [x] ogre
- [x] orc
- [x] reptile
- [x] troll
- [x] undead
- [x] mythical_being
- [x] northpole

**Comment by bleutailfly** [comment]
legendary ice elemental
the ice sword and ice armor are 100% drops, that is way to much, and needs to be fixed
ice armor should not come from a level 50 monster.  the creature also respawns every 10 seconds, needs to be longer
@@@@@
ugmash drops ; the ugmash can stay with the giant, but the other giants needs to be removed from drop list (elder giant, and master giant.
barbarian king has 2 ugmash drops, remove the 5.0.
@@@@@
poison drops that have been added,  rule of thumb, if a creature can poison you, then it can drop poison.  the following needs poisons removed from drop list
disciple assassin, apprentice assassin, assassin, ninja, shadows assassin, master assassin
@@@@@
torcibud drinks need to be removed from the kobolds, they are to much food for such a low creature.  even the giant kobold.
@@@@@
ogres bean drops,  they can be 1 and 3, not 5 and 10
@@@@@
orcs have 2 ugmash drops
@@@@@
red troll and cave troll have 2 ugmash drops
@@@@@
ghost hound
  <atk value="320"/>
+      <atk value="120"/>
-      <def value="110"/>
+      <def value="120"/>
-      <hp value="110"/>
+      <hp value="360"/>
-    <level value="45"/>
+    <level value="46"/>
-    <experience value="1250"/>
+    <experience value="1800"/>
-    <respawn value="12096000"/>
+    <respawn value="2368800"/>
double stats ???????
@@@@@
antumdeluge or tigertoes, would you please review mermaids and blordroughs and see if you agree with the drops.
  tigertoes would you please rename the elves I know you can come up with better names than me.

**Comment by bleutailfly** [comment]
ghost hound stats didnt copy and paste real well

**Comment by AntumDeluge** [comment]
The changes in drops that I found are listed on [testing page](https://stendhalgame.org/wiki/Stendhal_Testing#Enemy_Drops).

**Comment by nylon0700** [comment]
legendary ice elemental: the ice sword and ice armor are 100% drops, that is
way to much, and needs to be fixed. ice armor should not come from a level 50
monster. the creature also respawns every 10 seconds, needs to be longer

legendary elemental:

- respawn time 2d
- level value increase 100
- drop rate for ice sword 5%
- drop rate for ice armor 5%
- atk value increase 600
- def value increase 65
- hp value increase 700
- xp value increase 3500
- speed value decrease 0.3

**Comment by nylon0700** [comment]
barbarian king:
- drop rate for ugmash 1.0

**Comment by AntumDeluge** [comment]
Reviewed changes to animals.xml. Seems alright to me. Monkeys have more than 4 items with high drop rates, but nothing valuable. So I don't think it is a problem.

**Comment by nylon0700** [comment]
> torcibud drinks need to be removed from the kobolds, they are to much food for such a low creature. even the giant kobold.

a0) food and drinks are separate items.

b0) koboldish torcibud varieties are only found in Wo'fol city

c0) koboldish torcibud varieties are set to appear last in the list of dropped items  
c1) koboldish torcibud varieties drop quantity are set to be 1 unit
c2) koboldish torcibud varieties drop rates are set to be lower than 1%

d0) giant kobolds are by no mean a low creature

**Comment by nylon0700** [comment]
> ogres bean drops, they can be 1 and 3, not 5 and 10
I agree with that: pinto beans is conceived as "bunch of"

**Comment by nylon0700** [comment]
> ogres bean drops, they can be 1 and 3, not 5 and 10
> 

agreed: beans should be considered "bunch of" and not singletons

**Comment by AntumDeluge** [comment]
Reviewed human_blordrough.xml. Some blordroughs now drop the magic cape item at the low rate of 0.1%. Seems fine to me.

**Comment by AntumDeluge** [comment]
No new drops in *undead.xml*. However, see #286 for review on changes to ghost hound stats.

**Comment by nylon0700** [comment]
poison drops for human assassins are rare even when assassins do not poison directly

**Comment by AntumDeluge** [comment]
The cannibals drop rates are pretty high & they have more than four items that are dropped. So that means there is a higher chance of players missing out on some items. However, none of the items dropped by cannibals are very valuable. So, it might be alright.

**Comment by AntumDeluge** [comment]
Checked off *human_imperial.xml*. I think it's alright, but let me know if anyone disagrees. I just added sedative drops to imperial priest (2-3 @ 25%) & imperial high priest (2-5 @ 19%) since there were only 2 creatures in the game previously that dropped the item.

**Comment by AntumDeluge** [comment]
I had a new cannibal warrior enemy ready to add after release. But I decided to go ahead & add it now. I moved the new potato & carrot drops to cannibal & cannibal warrior to even out the number drops from each cannibal type. So *human_cannibal.xml* should be good now.

**Comment by nylon0700** [comment]
> I had a new cannibal warrior enemy ready to add after release. But I decided to go ahead & [add it now](https://github.com/arianne/stendhal/commit/06a0e23dd0). And I [moved the new potato & carrot drops to cannibal & cannibal warrior](https://github.com/arianne/stendhal/commit/6cc2c3c1e6) to even out the number drops from each cannibal type. So _human_cannibal.xml_ should be good now.
> 

Most cannibals still have a drop list, which is also conditioned by drop probabilities.
Potentially/theoretically>
-cannibal, drops 4 items
-elder cannibal, drops 3 items
-cannibal warrior, drops 3 items

The drops list can be (much) longer, since one has also the drop probability as a filter.

**Comment by nylon0700** [comment]
The northpole zone is special and should be transferred to his own tracking issue

**Comment by tigertoes13** [comment]
the only reason going to northpole is to get the candies that are dropped.. i anticipate lots of visits from people, so, rather than maked everyone hang around for goodies, all the guys drop 1 each of 4 types of candies/cake... and rather than someone hanging out for hours and leaving northpole with thousands of candies to eat or sell, i was gonna make then 'drop' the candies when they decided to leave... it should also be made no-teleport in, no using ring to 'spouse' in, no marking scrolls and all that crap... i had also wanted to make it a one-time deal... but had not discussed it with anyone

**Comment by nylon0700** [comment]
@tigertoes13 what I meant is that since the northpole area is only accessible during special timeframe (xmas?), the issue for balancing drops there should be transferred to its own tracking issue and separated from this one tracking issue...

**Comment by nhnb** [comment]
Update list: https://stendhalgame.org/temp/drops2.html

**Comment by AntumDeluge** [comment]
Should be able to check off northpole after e42ecb6.

**Comment by AntumDeluge** [comment]
All changed kobold drops were reverted except for ugmash drop from giant kobold. This was changed from 0.0005 to 1.0. Which I think is fine.

**Comment by AntumDeluge** [comment]
tripe item disabled, so I think it's safe to check off ogre drops. They also drop pinto beans which is needed for Meal for Groongo quest. So that drop is fine.
