### ISSUE TITLE
Northpole creatures have numbers

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#302]
## 🐞 Describe the bug

All creatures should have nice names without numbers:
- elf builder1
- elf builder2
- elf kid1
- elf kid2
- elf kid3
- elf kid4
- elf kid5
- elf skater1
- elf skater2

## 🔥 How to reproduce

Look at [data/conf/creatures/northpole.xml](https://github.com/arianne/stendhal/blob/master/data/conf/creatures/northpole.xml)

## 🌍  Environment

Current development version

**Comment by AntumDeluge** [comment]
Are these supposed to be attackable creatures? I'm wondering if they would be better implemented as [SilentNPC](https://github.com/arianne/stendhal/blob/master/src/games/stendhal/server/entity/npc/SilentNPC.java).

**Comment by tigertoes13** [comment]
sorry, i didnt close this... i did all the renaming and fixed logic tile and changed all the code and tested them out on test map... added the candies and made the changes to the xml files and, i believe, it is good to go.
