### ISSUE TITLE
potion shop npc

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#303]
## 💡 Describe your idea
a npc to buy random stuff to stock her shelves
A clear description of your idea

## 🔬 Motivation
 
A clear description of the background or motivation for the feature request. What problem is solved?

potion shop npc

Buys:
- [x] mandragora (1500)
- [x] toadstool (60)
- [x] poison (40)
- [x] greater poison (60)
- [x] mega poison (500)
- [x] deadly poison (100)
- [x] disease poison (2000)
- [x] sedative (200)
- [x] venom gland (2000)

Sells:
- [x] minor potion (150) *(normally 100 from other sellers)*
- [x] potion (300) *(normally 250 from other sellers)*
- [x] greater potion (600) *(normally 500 from other sellers)*
- [x] mega potion (1650) *(normally 1500 from other sellers)*
- [x] antidote (100) *(normally 50 from other sellers)*
- [x] greater antidote (150) *(normally 100 & 80 from other sellers)*
- [x] sedative (400)

## 📝 Alternatives

A clear description of any alternative solutions or features you've considered.

## 🔭 Additional information

Anything else

**Comment by AntumDeluge** [comment]
What do you want the NPCs name to be?

**Comment by AntumDeluge** [comment]
[Added potions dealer to Deniran potions shop](https://github.com/arianne/stendhal/commit/6135ee3fd6). But she still needs a proper name (currently set to "foo").

Still needs the following:
- [ ] proper name

Optionally can add:
- [ ] description
- [ ] items for her to sell
- [ ] more responses to keywords
