### ISSUE TITLE
selling more blue armors

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#305]
## 💡 Describe your idea
adding more armors for alexander to sell
A clear description of your idea
alexander buys the blue shield he could also buy the rest of blue items.  
- [x] blue helmet 900
- [x] blue boots 200
- [x] blue striped cloak 500
- [x] blue armor 13000
- [x] blue legs 400
- [x] blue shield  900

## 🔬 Motivation
 
A clear description of the background or motivation for the feature request. What problem is solved?

## 📝 Alternatives

A clear description of any alternative solutions or features you've considered.

## 🔭 Additional information

Anything else

**Comment by AntumDeluge** [comment]
The only issue I see with these is that blue striped cloak can already be sold in Amazon for 280. Amazon is much more remote than Ados, so it should be sold for more there. 280 seems too low for that cloak.
