### ISSUE TITLE
a place to sell xeno helmets

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#306]
## 💡 Describe your idea

A clear description of your idea
diehelm brui buys boots and helmets need to add xeno helmets to his list.
xeno helmet 7000

## 🔬 Motivation
 
A clear description of the background or motivation for the feature request. What problem is solved?

## 📝 Alternatives

A clear description of any alternative solutions or features you've considered.

## 🔭 Additional information

Anything else

**Comment by AntumDeluge** [comment]
[Diehelm Brui already buys xeno helmet in Mithrilbourgh for 8000](https://github.com/arianne/stendhal/blob/78e8fe36108698bae24b6b0214024f12b25eb62d/src/games/stendhal/server/entity/npc/ShopList.java#L228).

**Comment by bleutailfly** [comment]
well i looked on wiki and xeno helmet is not there

**Comment by AntumDeluge** [comment]
[Added to wiki](https://stendhalgame.org/wiki/Stendhal_NPCs#Diehelm_Brui). Though, he doesn't actually buy any of the other helmets listed there.
