### ISSUE TITLE
Summoning Items Using Alias Results in Invalid Item

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#310]
## 🐞 Describe the bug

If I use an alias to summon an item, for example *blank scroll* is alias of *empty scroll*, it successfully summons the item, but it is an invalid item.

## 🔥 How to reproduce

- Execute: `/summonat player bag blank scroll`
- A new item is added to the players inventory with the "GFX not found" failsafe image.
  - **NOTE:** failsafe image does not work in web client, so it is just an empty image.

**Comment by nylon0700** [comment]
I always thought the empty/blank scrolls where actually separate items...
Havent checked recently but separate icons exist thus my assumption.
Wasnt ´empty´ supposed to be in a quest? Just asking.

Had no idea we had alias for items...

**Comment by AntumDeluge** [comment]
[empty scroll](https://stendhalgame.org/item/scroll/empty_scroll.html). "blank scroll" is not an item. "blank" is simply an alias for "empty". So you can say to an NPC "buy empty scroll" or "buy blank scroll".

The file that configures aliases is [common/parser/words.txt](https://github.com/arianne/stendhal/blob/9fce1be6dd1de56725baabba30162e96b8a1e795/src/games/stendhal/common/parser/words.txt#L1504).

**Comment by AntumDeluge** [comment]
Looking through the items, there is a [blank scroll](https://stendhalgame.org/item/documents/blank_scroll.html) that is currently unused (I think), & it doesn't have an image. So, you are right @nylon0700. When I was executing `/summonat player bag blank scroll`, it was actually giving me the "blank scroll" item. Thereby displaying the failsafe image. I didn't realize "blank scroll" was an actual item, so I thought it was summoning the correct "empty scroll". This item probably shouldn't exist since it isn't used & the words "blank" & "empty" can be used interchangeably.

**Comment by nylon0700** [comment]
The Item I was referring did use an icon under:
> data/sprites/items/documents/scroll.png

rolled up scroll with a nice colored ribbon

![scroll](https://user-images.githubusercontent.com/53799271/74631475-5b12f980-515d-11ea-9c45-96165d29bda3.png)

**Comment by AntumDeluge** [comment]
[documents.xml](https://github.com/arianne/stendhal/blob/master/data/conf/items/documents.xml#L243) shows that *empty scroll* uses that image. I wonder why it's not showing up correctly on website & in game.
