### ISSUE TITLE
Hazel asking low-level players high-level items

### ISSUE THREAD

**Issue by nylon0700** [arianne/stendhal#312]
## 🐞 Describe the bug
Hazel in Kirdneh asks an Immortal Sword from a L12 player

## 🔥 How to reproduce

1. Go to 'Kirdneh' and talk to ´Hazel´

## 🌍  Environment

[ ] Java client
[ ] Web client

Location in game: ...

## 🔭 Additional information

Anything else
An immortal sword is not obtainable at L12

**Comment by AntumDeluge** [comment]
I agree with this 100%. I'm working on a solution.

**Comment by AntumDeluge** [comment]
Hazel will now only give immortal sword (& many other items) for quest if players is level 151 or above. Some other items only require the player to be level 51 or above: b10826a
