### ISSUE TITLE
Review item changes and new items

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#313]
We need to review the following item changes and new items since 1.30:

https://stendhalgame.org/temp/item.html

- [x] chaos hammer
- [x] chaos sword
- [x] keyring (changes reverted)
- [ ] smoked cod
- [ ] smoked ham
- [x] smoked meat
- [ ] smoked trout

- [x] antivenom.
- [x] antivenom ring.
- [x] candycane. (disabled)
- [x] cobra venom.
- [x] corn.
- [x] decent meal.
- [x] greenmint. (disabled)
- [x] gumdrops. (disabled)
- [x] habanero pepper.
- [x] lemon.
- [x] lemondrop. (disabled)
- [x] lollipop. (disabled)
- [x] magic cloak. (no changes since 1.31)
- [x] mauve apple. (disabled)
- [ ] olive oil.
- [x] peppermint. (disabled)
- [x] pinto beans.
- [x] portfolio. (disabled)
- [x] potato.
- [x] purple apple. (disabled)
- [x] royal armor. (disabled)
- [x] royal boots. (disabled)
- [x] royal cloak. (disabled)
- [x] royal dagger. (disabled)
- [x] royal helmet. (disabled)
- [x] royal legs. (disabled)
- [x] royal shield. (disabled)
- [x] taffy. (disabled)
- [x] tripe. (disabled)
- [x]  turtle shell ring.
- [x]  vial.
- [ ] vinegar.

**Comment by nylon0700** [comment]
Adding comments to open issues
- purple apple
- mauve apple
quest/token items to allow player fullfil the AdMemoriaInPortfolio quest
items get bound to the destinatary NPC to mark each phase of the quest,
purple/mauve apple cannot be consumed by player 

Brosoklelo grants a purple apple to be delivered to Vlamiklela (in Kirdneh)
Vlamiklela will take the purple apple from player inventory and turn that into a mauve apple to be delivered back to Brosoklelo. Once player returns to Brosoklelo, the latter will take purple apple from player inventory and enables portfolio, completing the quest

purple/mauve apple stats are unimportant, they should just be considered a token item
granting no special benefits to player

**Comment by nylon0700** [comment]
On decent meal:
Its given to player at the final phase of MealForGroongo quest
It is a quest item that needs to be delivered to Groongo, it cannot be consumed by player (gets bound to Groongo to prevent player consuming decent meal accidentally)

stats for decent meal are purely indicative,
since it cannot be consumed by others than Groongo,
will grant no benefits to player and will be removed from player inventory at quest completion stage

**Comment by nylon0700** [comment]
Smoked products:

Produced by Olmo, demonstrate how a single NPC can produce multiple products
instead recurring to multiple NPCs that can only produce one item at a time

Their stats are indicative, but are supposed to sligthly improve the "plain" equivalent
eg. smoked meat is slightly faster recovering health than plain meat and provides a bit extra health... that is the idea... Producing the smoked products is somewhat a slow process compared to getting plain equivalents (+ingredients, +time), thus producing them should compensate a bit the player for the effort

**Comment by nylon0700** [comment]
The following items were introduced as ingredients required by Chef Stefan in Fado restaurant in order to prepare the decent meal for Groongo (quest):

- habanero pepper
- lemon
- olive oil
- vinegar
- pinto beans
- potato

Their stats are purely indicative: the ingredients are supposed to be carried back to Stephan and will be removed from player inventory.

Consuming them would provide very minimal benefit in terms of recovered health, they have currently no market value.

**Comment by nylon0700** [comment]
Tripe was introduced too be fed to Cats (pet)
It was original item, unused.

**Comment by AntumDeluge** [comment]
Chaos sword & chaos hammer have been reverted back.

**Comment by AntumDeluge** [comment]
Checking off:
- antivenom ring (a ring with 50% chance to resist poison)
- cobra venom (drink that poisons entity)
  - amount: -1000
  - frequency: 10
  - regen: -60
- antivenom (drink that cures poisoning)
  - amount (duration?): 1600

All are special items for Antivenom Ring quest.

**Comment by AntumDeluge** [comment]
Turtle shell ring is dropped by gashadokuro. It adds +1 def when worn on the finger.

**Comment by AntumDeluge** [comment]
I think the special apples can probably be disabled.

**Comment by AntumDeluge** [comment]
Candycane, greenmint, gumdrops, lemondrop, lollipop, peppermint, & taffy disabled with e42ecb6.

**Comment by AntumDeluge** [comment]
The keyring as an item isn't obtainable in game yet. Not sure why it was enabled in the first place.

**Comment by AntumDeluge** [comment]
Olive oil should not poison people.

**Comment by AntumDeluge** [comment]
Not sure if vinegar & olive oil should poison players. It's not bad poisoning, only -1 HP, so might be okay.

**Comment by nylon0700** [comment]
> Not sure if vinegar & olive oil should poison players. It's not bad poisoning, only -1 HP, so might be okay.

The idea was that drinking/use olive oil or vinegar is bad for your health or in other words, make one sick. Poison effect is minimal, discourages using/drinking.
