### ISSUE TITLE
Collision missing in Fado Forest SE2

### ISSUE THREAD

**Issue by nylon0700** [arianne/stendhal#316]
## 🐞 Describe the bug
Logic collision tiles missing in Fado Forest SE2

## 🔥 How to reproduce
Travel to Fado Forest SE2 zone
 
1. Go to 'Fado Forest SE2'

## 🌍  Environment

[x] Java client
[ ] Web client

## 🔭 Additional information

![SCREENSHOT DeskWinw 2020-01-14-05 21 43 collision-problem](https://user-images.githubusercontent.com/53799271/72315490-3c6b9f80-3693-11ea-9449-ff8ea37f4899.png)

**Comment by AntumDeluge** [comment]
Collision with bushes, rocks, etc. is inconsistent on different maps throughout the world. This is due to maps being made by multiple users with different ideas of what constitutes collision.
