### ISSUE TITLE
coal needs a new background image

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#320]
![Screenshot_2020-01-18_09-43-21](https://user-images.githubusercontent.com/6003164/72665540-33ead000-39d7-11ea-928b-d3779ed5dbbf.png)
![Screenshot_2020-01-18_09-43-21](https://user-images.githubusercontent.com/6003164/72665549-49f89080-39d7-11ea-8159-f97a57d9fc2e.png)

## 🐞 Describe the bug

A clear description of the issue.

## 🔥 How to reproduce

3. See error

## 🌍  Environment

[ ] Java client
[ ] Web client
Location in game: ...

## 🔭 Additional information

Anything else

**Comment by AntumDeluge** [comment]
Removed background. Might do something nicer in the future, but looks better than it did.
