### ISSUE TITLE
Some Misplaced Collision in Deniran Caves

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#323]
## 🐞 Describe the bug

There are a couple collision tiles where there should be none in Deniran Caves. *(I'm sorry, I forgot to write down the map & coordinates. I will update this description when I figure it out.)

**Edit:** The map is *-2_deniran_lost_caves_n2_e2* at *101,15* & *102,15*.

![collision_deniran_caves](https://user-images.githubusercontent.com/3631473/72735427-a59a5980-3b50-11ea-8608-63709afe6a4a.png)

@bleutailfly

**Comment by bleutailfly** [comment]
removed collision
