### ISSUE TITLE
Zogfang does not react to trigger word: dwarves

### ISSUE THREAD

**Issue by nylon0700** [arianne/stendhal#331]
## 🐞 Describe the bug
Zogfang asks>
Would you like to help again clearing this Keep of our enemies, those dwarves?

dwarves is supposedly a trigger word in this context (painted blue)
saying dwarves in reply is not eliciting any response/hint from Zogfang

## 🔥 How to reproduce
Talk to Zogfang in Ados abandoned Keep, level -1
ask for task (again)

Logic>
task for Zogfang has been done before.
dwarves trigger word should elicit a reminder or not be included in question

**Comment by AntumDeluge** [comment]
Fixed: f8561acc07bd4c9b416654fe138834aa3d764f4b
