### ISSUE TITLE
unicorn horns for zelan

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#335]
## 💡 Describe your idea

A clear description of your idea
--[[
 ***************************************************************************
 *                      Copyright (C) 2019 - Arianne                       *
 ***************************************************************************
 ***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************
]]

local quest = simpleQuest:create("unicorn_horn_for_Zelan", "unicorn horns for Zelan", "Zelan")
quest:setDescription("Zelan needs help gathering unicorn horns.")
quest:setRequestReply("Hello! I'm in need of some unicorn horns to make some daggers. 
It is really dangerous in the woods surrounding Atlantis.  If you are a brave sort
 I could really use some help gathering unicorn horns. Will you help me?")
quest:setAcceptReply("Great!  Be careful out there lots of large monsters, 
and those centaurs are really nasty")
quest:setRewardReply("Thank a bunch!")
quest:setRejectReply("Thats ok, I will find someone else to help me.")
quest:setItemToCollect("unicorn horn", 10)
quest:setRepeatable(false)
quest:setXPReward(50000)
quest:setKarmaReward(5.0)
quest:addItemReward("soup", 3)
quest:addItemReward("money", 20000)
quest:setRegion(Region.ATLANTIS)

quest:register()

## 🔬 Motivation
 
A clear description of the background or motivation for the feature request. What problem is solved?
this is the path he walks
path 63,66  64,66  65,66  66,66  67,66  68,66  69,66  70,66  71,66  72,66  73,66  74,66  75,66

## 📝 Alternatives

A clear description of any alternative solutions or features you've considered.

![atlantiswarriornpc](https://user-images.githubusercontent.com/6003164/74107638-3658c980-4b40-11ea-9fb6-b998ac2b5bae.png)

## 🔭 Additional information

need a unicorn horn made 

Anything else
no

**Comment by AntumDeluge** [comment]
I will add this for you @bleutailfly.

**Comment by AntumDeluge** [comment]
@bleutailfly, would you like Zelan to respond to any of the following? *job, help, offer, etc.* Also, would you like him to have a description when players click on him?

**Comment by bleutailfly** [comment]
i think the quest templet works fine for me.    I dont want to much more stuff added, or I will get confused and make a muck of it.  If you think it needs more stuff, then feel free to add the other stuffs, but for now as the quest templet is just fine for me.   thanks
