### ISSUE TITLE
needs to say thanks and not thank

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#341]
## 🐞 Describe the bug

A clear description of the issue.
01:44] <Zelan> Greetings! How may I help you?
[01:44] <bleutailfly> done
[01:44] <Zelan> Thank a bunch! As a reward I will give you 3 soups and 20000 money.

## 🔥 How to reproduce
needs to say thanks instead of thank
3. See error

## 🌍  Environment

- Java client
- Web client

Location in game: ...

## 🛠️ Suggested fixes

Ideas on how to fix the problem: ...

## 🔭 Additional information

Anything else

**Comment by AntumDeluge** [comment]
Fixed.
