### ISSUE TITLE
Equipment Defense Inaccurate?

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#342]
Defense level of equipped items does not appear to be mathematically accurate.

Equipped:
- trophy helmet (def 88)
- black armor (def 26)
- black legs (def 15)
- killer boots (def 22)
- mithril cloak (def 28)
- mithril shield (def 45)
---
**Added Total:** 224
**Actual Total:** 400

Perhaps there is something else added to the equation that creates this higher value?

**Comment by nylon0700** [comment]
do twin swords count too?

**Comment by AntumDeluge** [comment]
Count for what? Twin swords don't have defense?

**Comment by bleutailfly** [comment]
what about players natural defence they receive from atks by monsters?

**Comment by tobiwankenobi-stendhal** [comment]
Different item types have a different weight in the calculations. Shield count x4, e.g. 
Source:     src/games/stendhal/server/entity/RPEntity.java        
```
return SHIELD_DEF_MULTIPLIER * shield + ARMOR_DEF_MULTIPLIER * armor
                                + CLOAK_DEF_MULTIPLIER * cloak + HELMET_DEF_MULTIPLIER * helmet
                                + LEG_DEF_MULTIPLIER * legs + BOOTS_DEF_MULTIPLIER * boots
                                + WEAPON_DEF_MULTIPLIER * weapon + RING_DEF_MULTIPLIER * ring;
```

**Comment by AntumDeluge** [comment]
Oh, interesting. I did not know that @tobiwankenobi-stendhal. Thanks.
