### ISSUE TITLE
Web Client: Consuming Items Consumes Multiple

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#344]
## 🐞 Describe the bug

When clicking consumable items from inventory, it consumes 2 instead of 1. My guess is this has come as a result of the new option to single click items on ground to pick them up.

## 🌍  Environment

- Web client

**Edit:** After further looking into the problem, it appears that it actually *may not* be a problem & may not be related to default action being pick up. I think what the players who reported it to me were experiencing was the items being consumed with a single click. They were familiar with having to double-click items in inventory to use them. I notice that web client uses single click to use items in inventory. I will have to test it more on a mobile device though to see what the behavior is.

**Comment by nhnb** [comment]
There was actually a new bug on master, that was not part of the last release. On mobile both a touchend and a mouseup event were processed.
