### ISSUE TITLE
looks odd

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#347]
![Screenshot_2020-02-22_21-01-54](https://user-images.githubusercontent.com/6003164/75102267-d68a0600-55b6-11ea-96af-8bfaf4028658.png)
## 🐞 Describe the bug

The `<tally>3</tally>`  looks cheap or generic.

## 🌍  Environment

- Web client

**Comment by AntumDeluge** [comment]
Fixed with 4d0f2849e8afe02f0bef2fe205db695c8d83f387
