### ISSUE TITLE
items still in bag

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#348]
## 🐞 Describe the bug
I put some items in the community chest and they still remained in my bag or at least the image of them. 
A clear description of the issue.

## 🔥 How to reproduce

3. See error

## 🌍  Environment

- Java client
- Web client
using web client, and i used firefox this time
![Screenshot_2020-02-23_09-58-26](https://user-images.githubusercontent.com/6003164/75114366-6e253e00-5623-11ea-8327-990c8b4fbe44.png)

Location in game: ...

## 🛠️ Suggested fixes

Ideas on how to fix the problem: ...yeah, kick web client to the curb

## 🔭 Additional information

Anything else

**Comment by nhnb** [comment]
- What is the name of the items you moved?
- Was this local, on main or test server?
- Is that the chest in Semos city?

**Comment by bleutailfly** [comment]
ham and meat
main 
chest in semos city

**Comment by AntumDeluge** [comment]
This has happened to me where the bag will not refresh when items are moved or used/consumed.

**Comment by AntumDeluge** [comment]
I don't remember the exact commits, but I believe this has been fixed in a prior release. Going to close.

If anyone experiences the issue again, we will re-open.
