### ISSUE TITLE
Improve stats panel

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#36]
The stats pannel in the webclient should display all the information that the traditional client displays. Most notable are the remaining XP to reach the next level, atk level or defense level.

It should also display the status icons such as eating or being poisoned.

Tasks
---
- [x] show remaining XP to next level for level and stats
- [ ] show status icons
- [ ] show karma bar (when feature enabled)
- [ ] show HP bar (configurable)

**Comment by AntumDeluge** [comment]
Remaining XP for level, ATK, & DEF are done: https://github.com/arianne/stendhal/commits/master/srcjs/stendhal/ui/component/PlayerStatsComponent.ts?since=2022-03-22&until=2022-04-05

Still needs:
- status icons
- hp bar
- karma bar

#254

**Comment by AntumDeluge** [comment]
The rest of the stats panel items are listed in #254 so I am going to close this.
