### ISSUE TITLE
How to Catch Player Disconnected to call TurnNotifier.dontNotify

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#373]
When a player logs out normally, [*LogoutListener.onLoggedOut*](https://github.com/arianne/stendhal/blob/99fef13bf2986d4717bd819c962dd5f54aae1966/src/games/stendhal/server/core/events/LogoutListener.java#L23) can be used to call [*TurnNotifier.dontNotify*](https://github.com/arianne/stendhal/blob/99fef13bf2986d4717bd819c962dd5f54aae1966/src/games/stendhal/server/core/events/TurnNotifier.java#L191). But how can we catch an event where the player did not log out normally (e.g. connection was lost) so we can call *TurnNotifier.dontNotify* in those instances?

**Comment by nhnb** [comment]
That listener is supposed to be called on timeouts as well. And as far as I can tell, it does work.
