### ISSUE TITLE
buying royal items

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#380]
## 💡 Describe your idea

A clear description of your idea

## 🔬 Motivation
 
A clear description of the background or motivation for the feature request. What problem is solved?

## 📝 Alternatives

A clear description of any alternative solutions or features you've considered.
king edward of deniran 
buying royal items
his army needs some better weapons and he needs you to find them for him.
- [x] royal boots   8000
- [x] royal helmet  13000
- [x] royal dagger  100000
- [x] royal cloak   18000
- [x] royal legs    38000
- [x] royal armor   58000
- [x] royal shield  73000

## 🔭 Additional information

Anything else

**Comment by AntumDeluge** [comment]
Added with 760830c. Pending enabling on main server.
