### ISSUE TITLE
Missing collision with tree in Orril forest N at (21, 35)

### ISSUE THREAD

**Issue by cosminhume** [arianne/stendhal#384]
## 🐞 Describe the bug

Players are able to walk through the tree in Orril forest N at (21, 35).

## 🔥 How to reproduce

1. Go to `0_orril_forest_n` at `(21,35)`
2. Walk through the tree

## 🌍  Environment

- Java client

Location in game: `0_orril_forest_n` at `(21,35)`

## 🛠️ Suggested fixes

Ideas on how to fix the problem:

- add collision on the map

## 🔭 Additional information

- screenshots: 
![tree](https://user-images.githubusercontent.com/42698386/89094151-a77b8a00-d3c9-11ea-9d68-1f6b674638dc.png)
![minimap](https://user-images.githubusercontent.com/42698386/89094168-afd3c500-d3c9-11ea-9549-89f92c8c2671.png)

**Comment by nhnb** [comment]
Thank you for the report, @bleutailfly just fixed it.
