### ISSUE TITLE
Trader Mastodon Bot

### ISSUE THREAD

**Issue by ghost** [arianne/stendhal#386]
## 💡 Describe your idea

Let's have a [Mastodon](https://en.wikipedia.org/wiki/Mastodon_(software)) bot for [Harold](https://stendhalgame.org/npc/Harold.html), just like we have one [on Twitter](https://twitter.com/stendhaltrade)!

I, for one, would surely follow it :wink: 

## 🔬 Motivation
 
Some players (like myself) do not use Twitter but do use Mastodon, and might like to have a Stendhal bot to follow there.

Its presence might also attract a new player or two.

## 📝 Alternatives

I had a look through the code to see how this is done. If I understand correctly, [PrepareOfferHandler](https://github.com/arianne/stendhal/blob/master/src/games/stendhal/server/maps/semos/tavern/market/PrepareOfferHandler.java) is where we start a [AsynchronousProgramExecutor](https://github.com/arianne/stendhal/blob/master/src/games/stendhal/server/util/AsynchronousProgramExecutor.java) which runs an executable (configured in the `stendhal.program.trade` property) with the tweet message as a parameter.

### Variant 1

I'm thinking of starting a second instance of `AsynchronousProgramExecutor`, for the new program that will "toot" (that's like tweeting, but for Mastodon).

### Variant 2

Alternatively, we could adjust the existing program for Twitter to also post to Mastodon.
By the way, is the source for the tweet program available somewhere?

## 🔭 Additional information

A possible instance for the bot account might be [botsin.space](https://botsin.space/), for example. Any other idea is welcome.
Also, I would be willing to try to implement this feature myself.

Thoughts?

**Comment by nhnb** [comment]
The twitter program basically the tutorial application:

~~~~
#!/usr/bin/env python
 
import sys
import tweepy
 
CONSUMER_KEY = '...'
CONSUMER_SECRET = '...'

ACCESS_KEY = '....'
ACCESS_SECRET = '...'

 
auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_KEY, ACCESS_SECRET)
api = tweepy.API(auth)
api.update_status(sys.argv[1])
~~~~

**Comment by cosminhume** [comment]
I went with variant 1: a second instance of `AsynchronousProgramExecutor`.
I did something similar to the tweet script, and tested on my test Mastodon instance.
Here's a screenshot of it in action:
![toot](https://user-images.githubusercontent.com/42698386/90307888-66b06480-dee3-11ea-9c2c-4c8ddfa9b5b5.png)
@nhnb, if you'd like to integrate this let's have a private chat.

**Comment by nhnb** [comment]
Sorry, this took years, literally.

https://mastodon.social/@stendhaltrade
