### ISSUE TITLE
missing image

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#389]
## 🐞 Describe the bug

A clear description of the issue.

there is a missing mask
![Screenshot_2020-09-22_08-41-34](https://user-images.githubusercontent.com/6003164/93883485-9ce5be80-fcaf-11ea-9494-06e10d267612.png)

this was taken on the test server will have to check if main server is the same

## 🔥 How to reproduce

3. See error

## 🌍  Environment

- Java client
- Web client

Location in game: ...

## 🛠️ Suggested fixes

Ideas on how to fix the problem: ...

## 🔭 Additional information

Anything else

**Comment by bleutailfly** [comment]
yep it is on the main server also

**Comment by bleutailfly** [comment]
there is 2 images that need to be drawn , guess i will have to make some mask :)

**Comment by AntumDeluge** [comment]
I believe @bleutailfly fixed this with 627ef3508de5a438d6fd73f5cabc55904b54a9b1.
