### ISSUE TITLE
the musth elephant def is way to high

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#392]
## 🐞 Describe the bug

A clear description of the issue.
the musth elephant def is way to high for its level . the def needs to be around 86 instead of 219

## 🔥 How to reproduce

3. See error

## 🌍  Environment

- Java client
- Web client

Location in game: ...

## 🛠️ Suggested fixes

Ideas on how to fix the problem: ...

## 🔭 Additional information

Anything else

**Comment by nylon0700** [comment]
@bleu, couldnt just edit animal.xml and submit the change?

**Comment by nylon0700** [comment]
An example:

$diff -u animal.xml.orig animal.xml
--- animal.xml.orig	2020-03-31 17:41:46.000000000 +0200
+++ animal.xml	2020-10-20 23:23:09.000000000 +0200
@@ -799,7 +799,7 @@
     <description>You see a musth elephant. It is highly aggressive and unpredictable.</description>
     <attributes>
       <atk value="218"/>
-      <def value="219"/>
+      <def value="90"/>
       <hp value="2250"/>
       <speed value="0.8"/>
       <size value="3,2"/>

I will run the balancer to see proper musth elephant stats... Stay tuned ;)

**Comment by nylon0700** [comment]
`
$diff -u animal.xml.orig animal.xml
--- animal.xml.orig	2020-03-31 17:41:46.000000000 +0200
+++ animal.xml	2020-10-20 23:23:09.000000000 +0200
@@ -799,7 +799,7 @@
     <description>You see a musth elephant. It is highly aggressive and unpredictable.</description>
     <attributes>
       <atk value="218"/>
-      <def value="219"/>
+      <def value="90"/>
       <hp value="2250"/>
       <speed value="0.8"/>
       <size value="3,2"/>


`

**Comment by nylon0700** [comment]
running the balancer tool, one gets:

`Suggested values:
	musth elephant (level 86): *	ATK: 258		DEF: 44		HP: 2250
`

It's a suggestion from the balancer heuristic of course.
Nothing prevents to set musth elephant to have a DEF (+/-) 86...

**Comment by AntumDeluge** [comment]
The musth elephant will be too easy now. It was created intentionally to have a high defense & low attack. That said, I am currently not active with the project so my opinions shouldn't be paramount.
