### ISSUE TITLE
Pizza delivery quest outfit

### ISSUE THREAD

**Issue by nudelchef** [arianne/stendhal#396]
After completing the Pizza Delivery Quest in Semos, your outfit changes back to your normal one, but the custom color isn't applied.

**Comment by AntumDeluge** [comment]
It appears that [PizzaDelivery.java](https://github.com/arianne/stendhal/blob/54bf28b/src/games/stendhal/server/maps/quests/PizzaDelivery.java#L544) calls [Player.returnToOriginalOutfit()](https://github.com/arianne/stendhal/blob/6b8f250/src/games/stendhal/server/entity/player/Player.java#L1638) which does not retrieve any stored outfit colors. I don't see any methods in [DressedEntity.java](https://github.com/arianne/stendhal/blob/5f83340/src/games/stendhal/server/entity/DressedEntity.java#L28) or `Player.java` to retrieve original outfit colors. Should probably be implemented. Also, `returnToOriginalOutfit` method should probably be defined in `DressedEntity.java`.

It would appear that [OutfitChangerBehavour.java](https://github.com/arianne/stendhal/blob/53a2640/src/games/stendhal/server/entity/npc/behaviour/impl/OutfitChangerBehaviour.java) suffers from the same problem. Has anyone checked if colors are restored when rented costumes expire?

**Comment by AntumDeluge** [comment]
This should now be fixed with 2f2d55b & e194fca.
