### ISSUE TITLE
Can the default port 32160 of the server be changed to four digits? So that the client can run on android

### ISSUE THREAD

**Issue by zonesgame** [arianne/stendhal#397]
## 💡 Describe your idea

A clear description of your idea

## 🔬 Motivation
 
A clear description of the background or motivation for the feature request. What problem is solved?

## 📝 Alternatives

A clear description of any alternative solutions or features you've considered.

## 🔭 Additional information

Anything else

**Comment by nhnb** [comment]
Are you really sure, that Android cannot connect to port 32160? I have not done development on Android, but I had no issues with Android apps connecting to unprivileged ports.

**Comment by zonesgame** [comment]
wifi can be connected to the server. The calling card cannot connect to the server. I will publish the project on github as soon as possible

**Comment by AntumDeluge** [comment]
Other Android clients, such as [Minetest](http://www.minetest.net/), connect using 5-digit port.

**Comment by AntumDeluge** [comment]
Closing as it appears @zonesgame has resolved the issue in their client.
