### ISSUE TITLE
Mature Themes Setting in Webclient

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#403]
## 💡 Describe your idea

The web client needs a setting to disable mature & violent images, like the Java client has.

**Edit:** Included in #254.

**Comment by nhnb** [comment]
It is not as simple as adding a setting:
- At the moment the client tries to load a potential non existing image. It is fine as long as the error is locally. It is not fine to have tons of 404 errors in the server log.
- "Mature" is a word, that most non-native speaker in Germany do not know. Blood is well known.
- We might want: showing nude players off by default, but showing blood+corpses on by default
- We need a way to store this setting on the server.

**Comment by AntumDeluge** [comment]
Updated Java client to use a unique setting for disabling nude characters: 874a117

Let me know if that label is good.

    We need a way to store this setting on the server.

This setting has to be unique to each user account, right? How would a web-based app normally do something like that? Wouldn't they use a cookie stored on the user machine? I'm guessing that we don't want to use cookies with the web client. So do we need to add database columns for user settings?

**Comment by AntumDeluge** [comment]
Until we have proper settings storage, blood can be disabled with `noblood` query string.

Related commits:
- 1458032
- f431c4c
- 6cb7e0b
