### ISSUE TITLE
Announce Deathmatches

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#407]
## 💡 Describe your idea

Idea by [latifundio](https://stendhalgame.org/character/latifundio.html): Have Thanatos announce to world when a deathmatch begins.

## 🔬 Motivation
 
Fun & attracting helpers to aid in deathmatch.

**Comment by tigertoes13** [comment]
be sure to announce the lvl of the player needing help

**Comment by monsterdhal** [comment]
That could also lure playerkillers to sabotage running deathmatches. At least we had a time when such behaviour was a problem.

**Comment by AntumDeluge** [comment]
> That could also lure playerkillers to sabotage running deathmatches. At least we had a time when such behaviour was a problem.

Solution to that would be to simply make the deathmatch a no PVP area.

**Comment by AntumDeluge** [comment]
> be sure to announce the lvl of the player needing help

I don't think that would be necessary as `/who` shows levels.

**Comment by AntumDeluge** [comment]
Also, might be a good idea to set a timer to suppress too many announcements within a period of time.

**Comment by latifundio** [comment]
Since now it is a non-pvp zone players can't use summon scrolls anymore. Might be something to note for the players that where doing it solo and used that strategy.

**Comment by AntumDeluge** [comment]
> Since now it is a non-pvp zone players can't use summon scrolls anymore. Might be something to note for the players that where doing it solo and used that strategy.

There might be a way to work around it to allow using summon scrolls in arena area.

**Comment by AntumDeluge** [comment]
Summon scrolls will be usable within deathmatch again in 1.41: 23f619c1259b244472262dddcd2f9c71d1570b07
