### ISSUE TITLE
Ideas to Promote Team Play & Player Satisfaction

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#408]
A list of ideas that could promote team play more. Feel free to comment & add more ideas.

- [x] enable ATK experience from creatures regardless of whether or not they have hit the player recently *(NOTE: atk xp should only be awarded for successful hits)*.
  - ~~This will reduce number of players standing around training & increase players fighting monsters together.~~
- [x] Reduce player attack strength by around 50% & increase attack success by around 50%.
  - It has been an issue for a long time that players are hit much more often by creatures than they successfully hit creatures. One of the reasons for this is to create balance because player & creature stats work differently. This results in some player frustration due to the fact that they miss so often & don't do any damage. Changing these values will increase player satisfaction while maintaining current balance.

## VETOED
<del>
Disallow certain activities with characters that share accounts

We could store shared account character names in a player attribute on login, so we don't have to make a call to the database at every check. This attribute would be checked before certain activities were allowed or certain rewards were given. Some examples of disallowed activities/rewards for shared accounts:
- PvP/training
- achievements for helping players (such as Deathmatch Helper)
</del>

**Comment by nhnb** [comment]
I am sorry, but I have to veto this.

# There will never be any kind of benefit for spreading characters across multiple accounts.
# There will never be any kind of benefit for using multiple IP addresses.

Please, please do not do this as it creates a lot of additional work for me, in case of account hacks.

**Comment by AntumDeluge** [comment]
@nhnb Please correct me if I am wrong, but I think we are talking about two different things. I'm not talking about players sharing accounts with other players. I'm talking about one player logging in with two characters at the same time from the same account.

But now that this is brought up, I'm realizing it won't do any good to try & filter out characters because Stendhal doesn't disallow opening multiple accounts. So this will actually just promote players creating multiple accounts with Stendhal's current ruleset.

**Comment by AntumDeluge** [comment]
> Now i think what we need is a final dungeon with:
>
> - a requirement of at least 4 players to enter it.
> - Time limit before the dungeon collapse (no more than an hour?).
> - random generated map with few puzzles and traps (to keep it interesting).
> - chance of encounter enemies above lvl 1000 the more deep you go (boss fights?) with some nice rewards.

This sounds like fun, a dungeon that requires a party of at least 4 to enter.

**Comment by tigertoes13** [comment]
i am putting in a very large creature with a nicie place to store him... had planned to make it 3 minimum, but i suppose that is negotiable ... and , of course, this might be the test for a larger area with more minimum...

**Comment by latifundio** [comment]
[quote] i am putting in a very large creature with a nicie place to store him... had planned to make it 3 minimum, but i suppose that is negotiable ... and , of course, this might be the test for a larger area with more minimum... [/quote]

It would be cool if the legs, head and body could be targeted and each part have its own weakness, like the head only weak to arrows, the legs weak to big weapons and the body weak to stab like daggers and short swords. 

Also a minimum of required players should depend on the roles needed to complete the challenge. When you say 3 i remember the old trio of warrior, archer and mage.
