### ISSUE TITLE
Close corpse inventory automatically

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#42]
The inventory windows of corpse should be closed automatically,
* when the player walks away
* the last item is taken from the corpse
* the corpse is moved away
* the corpse is removed from the zone due to timeout

**Comment by AntumDeluge** [comment]
Last I checked, there was an issue with larger corpses closing immediately after creature is killed. It is caused by distance not compensating for corpse size. It is listed in #254, but thought I would mention it here.
