### ISSUE TITLE
Web Client: Click-Consume is Broken

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#430]
## 🐞 Describe the bug

Cannot use consumable items with click/double-click in web client.

**Edit:** Appears to work inconsistently. I have not yet determined what causes it to fail at times.

**Comment by nhnb** [comment]
On mobile Chrome, sometimes the items in by bag are rearranged instead of being used.

**Comment by AntumDeluge** [comment]
Might need to disable touch event handlers in `ItemContainerImplmentation`.

**Comment by AntumDeluge** [comment]
Should be fixed now. Will close after more testing.
