### ISSUE TITLE
/atlas opens atlas in same tab

### ISSUE THREAD

**Issue by markuskeunecke** [arianne/stendhal#432]
## 🐞 Describe the bug
Using the atlas command in web client basically works but opens the atlas (at least for me) in the same tab and thus you need to reopen your session again in a new tab.

## 🔥 How to reproduce
1. Use /atlas command in web client

## 🌍  Environment
- Web client

## 🛠️ Suggested fixes
Let the atlas be opened in a new browser tab or browser window.

**Comment by nhnb** [comment]
All web pages are opened in the same tab by design in order to prevent people from getting killed in the background.

**Comment by markuskeunecke** [comment]
So I get logged out? And can re-login? I was just surprised that my game window was gone missing after I issued a /atlas-command.

**Comment by AntumDeluge** [comment]
> So I get logged out? And can re-login?

Yes, your character is disconnected as soon as the page changes.

**Comment by markuskeunecke** [comment]
Okay, that's a safe guard I was not aware of. Especially I didn't think about forgetting about the client tab in the background. ;) Maybe this needs a better approach or should be left as is.

**Comment by AntumDeluge** [comment]
Using a confirmation dialog before changing pages might be an option.

**Comment by markuskeunecke** [comment]
Or showing the atlas within the game window. But this would be more a feature request.
