### ISSUE TITLE
Issues in RPEntity.drawMultipartOutfit

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#456]
## 🐞 Describe the bug

The refactoring of RPEntity.drawMultipartOutfit has potential for performance improvements in the most critical path. The current state, however, makes performance worse:

[ ] The outfit canvas is coped to an image, then serialized to a base64 string, then parsed again to be drawn onto the game canvas. This is done 20 times per second for every outfit-based RPEntity on screen. I think it should be possible to just call `this.drawSpriteImage(ctx, this.ocanvas);` skipping the image step completely.

[ ] The outfit images are drawn onto the canvas without a check whether they have been loaded. This will cause a crash on slow networks

[ ] The outfit canvas is not cleared before drawing. I think it is okay for now because we don't have semi transparency in any existing outfit.

[ ] Suggestion for improvement: Once all the outfit part images have been loaded, do not redraw the outfit canvas unless the outfit specification changes.

## 🌍  Environment

- Web client

**Comment by AntumDeluge** [comment]
Reverted combining outfit layers with b8b3086875 to fix performance issues. I don't want to block release & probably won't be able to come up with a decent fix in a timely manner.

**Comment by AntumDeluge** [comment]
This should be fixed now with the following commits:
- f7047d71e677ee90ae20419b78afd20c98c1df9a
- f5bddd52b08712cde67fd6bc422c7efaac84e386
