### ISSUE TITLE
modify chatlog name upon save

### ISSUE THREAD

**Issue by tigertoes13** [arianne/stendhal#464]
## 💡 Describe your idea

A clear description of your idea

## 🔬 Motivation
 
A clear description of the background or motivation for the feature request. What problem is solved?

## 📝 Alternatives

A clear description of any alternative solutions or features you've considered.

## 🔭 Additional information

Anything else

**Comment by tigertoes13** [comment]
it would be beneficial to add the chars name and the date, including time, to the chatlog when user saves the chatlog... reason i ask this, i had an important conversation with another player, then saved, then forgot i did it, and then had another conversation the next day, and saved that, only to write over previously un-renamed chat log... yes, aint older minds wonderful :D

**Comment by AntumDeluge** [comment]
Java client chat log now...
- saved with filename in format of `character_channel_date_time.log`
- saved to "chat" sub-directory
