### ISSUE TITLE
Deathmatch Can Be Restarted Without Claiming "Victory"

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#470]
## 🐞 Describe the bug

A player can start a new round of deathmatch without claiming "victory" for the previous one. This leads to the points for the previous round being lost.

## 🛠️ Suggested fixes

Require player to claim "victory" before starting a new round.

*([mirrored on SourceForge](https://sourceforge.net/p/arianne/bugs/5996/))*

Related: https://sourceforge.net/p/arianne/bugs/3284/

**Comment by tigertoes13** [comment]
this should include the fact that a player can also leave without claiming victory/complete/done...
i stand guilty of these occurrences :(

**Comment by AntumDeluge** [comment]
Just came across [this very old bug](https://sourceforge.net/p/arianne/bugs/3284/) that may be the same or related. This has been an issue for a long time.
