### ISSUE TITLE
Use stendhal as a demo show in kruise-game.

### ISSUE THREAD

**Issue by ringtail** [arianne/stendhal#472]
Hi, I'm the maintainer of kruise-game(https://github.com/openkruise/kruise-game) which is an opensource cloud-native game server workload. I am a fan of stendhal and want to use it as a demo to show how to containerize a game server and run on kubernetes. Could we use stendhal in our docs and examples?

Thanks, Look forward to your reply!

**Comment by nhnb** [comment]
Sure, go ahead.

Do you think that Stendhal will work as is? Or are there things, that we should change, to make it easier?

**Comment by markuskeunecke** [comment]
I think one thing we could do to help him is to provide a containerized version of the game server. I think this can be done without too much hassle. A thing to discuss would be how to handle the game web page. A pragmatic approach could also include a http server providing the web pages as you can see them on stendhalgame.org.

**Comment by markuskeunecke** [comment]
I am giving it a fast try to implement a container image using h2db for ease of deployment.
