### ISSUE TITLE
Provide a container image for Stendhal server

### ISSUE THREAD

**Issue by markuskeunecke** [arianne/stendhal#473]
## 💡 Describe your idea

Provide a containerized version of the Stendhal server.

## 🔬 Motivation
 
This feature request was motivated by #472

**Comment by chrisliu1995** [comment]
Will Stendhal support multi-containers architecture?

Different functions are deployed in different container separately, which is conducive to targeted expansion and contraction.

**Comment by nhnb** [comment]
> Will Stendhal support multi-containers architecture?
> Different functions are separately deployed in different containers, which is conducive to targeted expansion and contraction.

Having one container for the webserver, one container for the PHP server, one container for the game server and one container for the database is trivial and works as expected without anything special at all.

I have outline a multi-server architecture for the gameserver at https://gamedev.stackexchange.com/a/5967/450
@chrisliu1995 feel free to work on that. Given that the Stendhal architecture can handle at least one magnitude more users than the design of Semos city, this topic is not on my priority list.

**Comment by chrisliu1995** [comment]
As https://github.com/arianne/stendhal/issues/472 said, kruise-game would like to use Stendhal as an example of MMORPG game. 

We project aims to solve the problem that it is difficult to manage different server-roles in a MMORPG game. Therefore, it will be better if Stendhal could be easily divided into multiple containers. 

`<Having one container for the webserver, one container for the PHP server, one container for the game server and one container for the database >` looks good to us.

**Comment by markuskeunecke** [comment]
Okay, the current containerization approach uses integrated database. But I think I can change the initialization process to support both H2 or external database. @chrisliu1995

**Comment by markuskeunecke** [comment]
The first throw was not as easy as I thought. So I went back to rethink my approach for the image. I will outline it here before starting to code it down:
- server.ini should be generated without user interaction on container start based on environment variables (this enables usage of kubernetes secretes)
- StendhalServer.main uses a container command line switch to enable the previous headless server.ini generation
- headless server.ini generation uses this environment variables
-- **STENDHAL_KEY_SIZE** (with default _512_) for the RSA key size
-- **STENDHAL_DB_TYPE** (with default _h2db_) for the type of database to use, other option would be mysql
-- **STENDHAL_DB_PATH**: The path to the H2DB files in the file system, used in combination with _STENDHAL_DB_TYPE=h2db_, default _/stendhal/data/h2db_. Could be used to be mounted as external volume.
-- **STENDHAL_DB_HOST**: The hostname of the (MySQL) server
-- **STENDHAL_DB_NAME**: The name of the database within the database server
-- **STENDHAL_DB_USER**: The username to be used accessing the database
-- **STENDHAL_DB_PASSWORD**: The user's password.

The first approach was too tightly bound to H2DB. This would have blocked also deploying the PHP pages in a webserver container.

**Comment by nhnb** [comment]
Given that there is quite a number of settings that must be changed after initial generation of server.ini, it might be a good idea not to have that file inside the container at all.

So either provide that file from outside storage similar to data directory of the database server. Or read all settings from environment, if and only if Docker provides a secure way to do that. On classic Linux, environment variables of one process are visibility to all other processes of any user account.

**Comment by markuskeunecke** [comment]
@nhnb: Can you tell me which settings must be changed after initial generation of server.ini? If this is really a lot we should inject server.ini from outside. This would be possible anyway as StendhalServer skips server.ini generation if there's a server.ini present.

Docker [documentation](https://docs.docker.com/engine/swarm/secrets/) says that secrets are the prefered way to store sensitive information. Within a Kubernetes environment [secrets](https://kubernetes.io/docs/concepts/configuration/secret/) can be exposed to the pod as environment or as files.

**Comment by nhnb** [comment]
Incomplete list:
- server_contact
- server_abuseContact
- server_welcome
- server_extension
- [extensionname*1*..extensionname*n*]
- content_security_policy
- limit_characters_per_account
- stendhal.twitter.trade.username
- stendhal.twitter.trade.password
- stendhal.program.trade
- stendhal.secret
- proxy_credentials
- password_pepper
- max_number_of_players
- logging_folder
- http_port
- http_forwarded

**Comment by markuskeunecke** [comment]
For a local development environment with docker-compose I think we can use the environment variables approach as it can be configured more easily. In a production environment one should inject the server.ini into the container from the container runtime environments preferred secrets storage.

I can provide a docker-compose file and an .env template for both h2db and mysql. This enables for easy testing.

I am not sure how we could support @chrisliu1995 with some means of server.ini generation. I think there's a concept of [init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) in Kubernetes, but I have no experience in that. The needed stuff is in the binaries I'd put into the image.

Those additional variables should be part of such an init process generating the server.ini and storing it as a secret.

**Comment by chrisliu1995** [comment]
I found that you want to split out two containers, main server & db, is that right?

It was mentioned before that a webserver can be independent, so is there a plan for supporting this part?

**Comment by markuskeunecke** [comment]
Basically we aim at using one database container (optional if you do not need game server webpage, like https://stendhalgame.org), game server itself and a webserver providing the game server webpage.

Database will simply be a MySQL container. For the webserver we might simply use a basic webserver image, maybe extended with the PHP sources and other necessary files.

**Comment by markuskeunecke** [comment]
We can now build a container image of a Stendhal server based on the distribution.
