### ISSUE TITLE
Increase Number of Displayed Players in HoF

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#476]
## 💡 Describe your idea

Our hall of fame is pretty small. I would like to see the rankings listed up to 20th or 25th place for each category.

*([mirrored on SourceForge](https://sourceforge.net/p/arianne/feature-requests/1474/))*

**Comment by nhnb** [comment]
At the moment the hall of fame page is extremely crowed. We should probably reduce the total number of entries on that page. We would have a "more" link at the end of each category, which a detail-view of that category

**Comment by AntumDeluge** [comment]
I like the idea of adding links to show more.
