### ISSUE TITLE
make the achievement display for more time so that we can get a screenshot of it

### ISSUE THREAD

**Issue by tigertoes13** [arianne/stendhal#495]
i got, to me, the most important achievement earnable today... and it faded from the screen before i was able to get a screenshot of it, leaving me very melancholy and upset with myself for being caught up in the moment but not able to make my brain work in less stressed condition...

maybe suggest,  hey, wanna get a screenshot of this? or just leave it up until the player clicks on it, thus, if i had seen something like that, i would have come to a sane mindset and taken the screenshot...

let me know if i can shed any more info needed... thanks ever so much...
YAY... I DID IT TODAY....

**Comment by tigertoes13** [comment]
forgot to say what i did :(  i maxed out my helmet :D.

**Comment by AntumDeluge** [comment]
When I get a couple other things done, I will take a look at this. Shouldn't be very hard to implement.

**Comment by AntumDeluge** [comment]
Currently, the achievement banner stays on the screen for 10 seconds. Should we increase the time or add a setting to keep it on the screen until player clicks it?
