### ISSUE TITLE
Webclient plays creature noise on mute

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#505]
## 🐞 Describe the bug

The webclient plays rat sounds despite being muted.

## 🔥 How to reproduce

1. Ensure that the client is muted by the button in the top right hand corner next to the menu button.
2. Walk next to a rat.

## 🌍  Environment

- Web client

**Comment by AntumDeluge** [comment]
I'll try to get this fixed. I made a lot of changes to sounds player trying to get looped sound sources working.
