### ISSUE TITLE
Webclient chat log stops scrolling down

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#507]
## 🐞 Describe the bug

When the chatlog is scrolled all the way to the end, it should automatically scroll to the end again, when new text is added. But this stops after a couple of messages.

## 🔥 How to reproduce

1. Scroll the chat log all the way to the end
2. Look at items again and again until the chat log stops scrolling to the end.

## 🌍  Environment

- Web client

**Comment by AntumDeluge** [comment]
Reference: d6aec722842910c91253d8d89d3d44b6d492548b
