### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by JamesXNelson** [arianne/stendhal#511]
Hi there!

Stendhal is really amazing, and I often find myself wishing I could use stendhal resources in non-GPL products.

I've had acquantainces tell me that, so long as GPL-based resources are placed into separate source control with a GPL license, and are built into a binary format that anybody anywhere can get and produce themselves, that it is ok to now use those GPL binary files (images, jars of java classes, etc) in a closed source product, as long as it would be possible to replace those GPL resources with "something else" and the program would still function (i.e. nobody can take all stendhal resources to create stendhal-with-R-rated-p2w, because that makes the whole thing a derivative of stendhal as a whole).

Anyway... because this is always such a murky legal worry, I find that the best thing to do when considering inclusion of GPL works into non-GPL products, the best thing to do is to ask the contributors / maintainers their intentions, and simply respect that.

i.e. one must ask the maintainers before using a single byte[] about their intentions for their work. If the maintainer/s say/s "Only GPL projects may use anything here", then you thank them for your time and move on. If they say "we just want any derivatives of our work to also be copyleft", then you take the time to maintain as a separate GPL open source repository with your changes, then produce a binary of some kind to be downloaded at runtime to enhance "my-not-GPL program".

So!

If I were to build an open source, dual-licensed cc0/gpl3 repository containing mountains of image resources from many projects, with controls for selecting image resources by license requirements, would you see Stendhal resources as "any modifications to these must be GPL open source" or would you prefer "any game using Stendhal images must be GPL-compatible licensed"?

**Comment by AntumDeluge** [comment]
Stendhal has many assets from many different sources under different licenses (all GPL compatible). We keep a list of our assets with their license info & source [here](https://github.com/arianne/stendhal/blob/master/doc/sources). You can use the assets however you like within the restrictions of the pertaining license. Be careful if your project uses DRM. Many licenses explicitly do not allow for inclusion in such.

GPL licensing with assets is a bit obscure. I can't tell you in 100% confidence how to use them. My understanding is that to include GPL licensed assets, your project must be GPL compatible. Creative Commons licensing is a bit clearer. You can use CC licensed assets in most projects, so long as you follow the terms of the license. E.g., crediting the author and/or linking to the source in a manner that is clear to anyone using your software as the author requires. Again, be careful about DRM projects. Some of the less strict CC licenses allow inclusion in DRM protected software, but others do not. Also be aware of differences across different versions of the licenses.

In order of most strict to least, the different licenses that our assets are under are:
- GPL
- Creative Commons Attribution-ShareAlike (CC BY-SA)
- Creative Commons Attribution (CC BY)
- OpenGameArt.org Attribution (OGA BY)
- Creative Commons Zero (CC0)
