### ISSUE TITLE
need to hire more ladies to distribute rhosyds, and santas, and easter bunnies

### ISSUE THREAD

**Issue by tigertoes13** [arianne/stendhal#525]
because there are so many maps now, rose has a difficult time being accessible to those who want her rhosyd
## 🔬 Motivation
it will be more fair to characters to have access to those nps...
## 📝 Alternatives
create a couple more rose, santa and easter bunny, split the maps up and give each npc an equal number each for each category

each category of npc will need to have a central part of the database so they know if the char that says 'hi' has been presented with gift/egg/flower/whatever, already

**Comment by AntumDeluge** [comment]
The alternative would be to limit the maps teleporting NPCs can visit even more.

**Comment by nhnb** [comment]
Note: This bug report was made after it Easter Bunny disappeared because of a server restart.
