### ISSUE TITLE
A texture of a bed in 'Semos guard house' is displaying in wrong way.

### ISSUE THREAD

**Issue by eMKejTestingWarriors** [arianne/stendhal#558]
## 🐞 Describe the bug

When you try to go on the area over the bed, your hero is displayed on the bed, not behind it.
When you go on a square below the bed, bed is displayed on your hero's head, not under it.

## 🔥 How to reproduce

1. Go to 'Semos guard house'.
2. Click on field (3,2) or (3,4) [a bed and square below].
3. Textures are displaying in the wrong way.

## 🌍  Environment

- Java client
- Web client

Location in game: Semos guard house
Version: 1.44

**Comment by AntumDeluge** [comment]
Confirmed. Thank you. This is an issue with collision placed incorrectly.

![stendhal-2023 10 29-02 52 10](https://github.com/arianne/stendhal/assets/3631473/85812c36-67ed-4b5e-af70-ac6dd2863273)

**Comment by AntumDeluge** [comment]
Fixed with 49b64c15cf3b4dd4b76555a4a52812a00ba99e8e.
