### ISSUE TITLE
Inaccessible fields in 'Semos guard house' marked as accessible on a minimap.

### ISSUE THREAD

**Issue by eMKejTestingWarriors** [arianne/stendhal#559]
## 🐞 Describe the bug

There are five fields marked with pale green on minimap, which are inaccessible for player: (17,2), (18,2), (2,13), (3,13), (4,14).

## 🔥 How to reproduce

1. Go to 'Semos guard house'
2. Point one of fields (17,2), (18,2), (2,13), (3,13), (4,14) with the cursor.
3. See default cursor changing to "Move" cursor ("Look" cursor for (3,13), (4,14)).
4. Click minimap in place coresponding with the field.
5. Hero cannot go there.

## 🌍  Environment

- Java client
- Web client

Location in game: Semos guard house

## 🔭 Additional information

Version 1.44
<img width="302" alt="2" src="https://github.com/arianne/stendhal/assets/149269748/144d013c-d091-4957-8362-ea1023f51e51"><img width="302" alt="1" src="https://github.com/arianne/stendhal/assets/149269748/c7c43975-38f2-4b59-8d37-8ef1dd0a48f4">

**Comment by AntumDeluge** [comment]
The area by the fireplace is simply inaccessible. It doesn't really matter if those are collision tiles or not. The armor that you have marked are actually sign entities that have collision. Normally signs don't show up on the minimap. But I will add collision behind those.
