### ISSUE TITLE
Pizza Delivery Quest Broken

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#567]
## 🐞 Describe the bug

When I first talked to Leander my inventory was full & he asked me to come back when I had space:

> [17:14] &lt;dodle&gt; quest
> [17:14] &lt;Leander&gt; I need you to quickly deliver a hot pizza. If you're fast enough, you might get quite a nice tip. So, will you do it?
> [17:15] &lt;dodle&gt; yes
> [17:15] &lt;Leander&gt; Come back when you have space to carry the pizza!

But after making space he wouldn't respond to my task query:

> [17:17] &lt;dodle&gt; hi
> [17:17] &lt;Leander&gt; Hallo! Glad to see you in my kitchen where I make pizza and sandwiches.
> [17:17] &lt;dodle&gt; quest
> [17:17] &lt;dodle&gt; pizza
> [17:17] &lt;Leander&gt; I need someone who helps me delivering pizza. Maybe you could do that task.
> [17:17] &lt;dodle&gt; task
> [17:17] &lt;dodle&gt; bye

__EDIT:__ Tested again on test server. It only breaks if you try to accept the quest without space in your inventory. Quest state is set to "start".

**Comment by nhnb** [comment]
Thank you for the report. Fixed.
