### ISSUE TITLE
Static Keyboard for Web Client

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#57]
I know that the web client is not optimized for mobile devices, but I was testing it on my Android phone & found the most difficult part being the devices software keyboard taking up so much space on my tiny screen.

I think a togglable keyboard on the web client's page would make mobile play more appealing.

**Comment by nhnb** [comment]
I fixed the issue which opened the keyboard after every touch on the game window.

**Comment by AntumDeluge** [comment]
Thank you @nhnb.
