### ISSUE TITLE
"Log out" and "Select character" buttons on desktop version

### ISSUE THREAD

**Issue by eMKejTestingWarriors** [arianne/stendhal#570]
## 💡 Describe your idea

Such buttons could be added to options panel. After using them, the appropriate window can be showed (for example, the same as we see after signing in or after launching the game).

## 🔬 Motivation
 
Sometimes a user wants to just change character or account (if he/she has more than one) without having to close the game.

**Comment by AntumDeluge** [comment]
I've thought about this before. It is generally pretty common behavior for game clients to have a function to log out to a character selection screen. I think it would make sense for the Java client to work this way.

**Comment by AntumDeluge** [comment]
The project is focusing on the web client, &amp; a new desktop client based on it. Currently, there aren't any members of the development team (that I am aware of) that plan to add new features to the Java client. It can be considered to be in a bugfixes only state.
