### ISSUE TITLE
Possibility of password recovery for users with email.

### ISSUE THREAD

**Issue by eMKejTestingWarriors** [arianne/stendhal#572]
## 💡 Describe your idea

When we try to sign in, we could have possibility to recover/change our forgotten password.
It is commonly realised as a button "Forgot password?".
Of course, if someone has not fill the email field, they will not have this option.

## 🔬 Motivation
 
Adding such an option is a good practice to help avoid losing players who use the application just occasionally (they can easily forget their account password, and lack of the functionality may discourage them from playing the game).

**Comment by nhnb** [comment]
Email based password reset is a high risk function for several reasons:
- people use throw away email address
- email addresses expire after a certain period of inactivity (e. g. Hotmail or Google accounts)

At this time we do not have the capacity to deal with that. As far as stendhalgame.org is concerned we can manually do a password recovery as described in the FAQ.
