### ISSUE TITLE
Creating Separate Branch for Each Release Clutters Git

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#58]
I get a little frustrated trying to sort through all the branches. Creating a simple tag for each release should be enough.

**Comment by nhnb** [comment]
Almost all release have commits after branch creation. I am not happy of declaring a week of "you may not commit to master unless it really has to go into the pending release".

Furthermore, doing a release takes two evenings which already is a lot of time and we should be very careful about doing anything that increases the risk of having to aboard and postpone a release.

Last but not least, there have been situations in the past which forced us to do an immediate bugfix release on the branch.

The release branches are spelled in uppercase and all follow the same naming convention so they are very easy to filter.

**Comment by AntumDeluge** [comment]
Okay, so each release branches away from master before it is released. I can understand your reasoning for doing this.

I just need to learn any methods that Git can use to filter branch listings.
