### ISSUE TITLE
"master" Tag Causes Issues

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#59]
If a tag & a branch exist with the same name, a warning is emitted about the name being ambiguous.
```
$ git checkout master
warning: refname 'master' is ambiguous.
```
On some machines I can't switch to that branch until I delete the tag.

**Comment by nhnb** [comment]
Using the same name for a branch and a tag is supported by git. But some git commands prefer refs/head/[name] and other git commands prefer refs/tags/[name]. Therefore I strongly recommand against using the same name for branches and tags.

**Comment by AntumDeluge** [comment]
The reason I posted this is because both stendhal & marauroa repos have branches & tags named "master". And I am unsure why the tag exists, because I often have to delete it from my refs after doing a fetch.

**Comment by AntumDeluge** [comment]
I found my way around avoiding this issue by calling `git fetch remote master` instead of `git fetch remote`, `git pull remote master` instead of `git pull remote`. Still, seems strange to have a tag named "master".

**Comment by AntumDeluge** [comment]
Changed the name, because the problem isn't with tags & branches having the same name in general. It's with the master tag. On Windows clients, one can't simply use `git push` to push to master branch when there is a tag named "master".

I recommend deleted the tag named "master" as it will cause an error for Windows users when trying to push. Those that may not be all that familiar with Git may be confused & not know how to solve the problem. The "master" tag also carries over to forked repos.

**Comment by AntumDeluge** [comment]
We just discovered that the "master" tag in the Git repo is also messing up zip/tarball downloads. Instead of downloading an up-to-date archive from the master branch, it is downloading the older "master" tag version:

That is also why on SourceForge, the most recent commits aren't visible from the master tree view: https://sourceforge.net/p/arianne/stendhal/ci/master/tree/

It shows the most recent commit as 7f114d, which is dated back in March of 2017. The GitHub "master" tag is at ade5f88, which is only two days newer. Either way, the master tag is messing up both repos & should be deleted.

**Comment by AntumDeluge** [comment]
I went ahead & copied the master tag to [old-master](https://github.com/arianne/stendhal/releases/tag/old-master) & deleted the tag named "master", but it keeps reappearing in GH & SF repos. :-\

**Comment by AntumDeluge** [comment]
Sync script that was causing issue has been fixed.
