### ISSUE TITLE
Make Kewords Dialog Customizable

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#606]
## 💡 Describe your idea

I recently added a dialog to the web client with commonly used words useful for quick access on touch enabled devices:

![Screenshot_20231212_193802_Stendhal (debug)](https://github.com/arianne/stendhal/assets/3631473/efb72bdc-d646-46f6-885c-30aeeffb9b23)

Currently the list of available words is hard coded but it would be trivial to make it customizable.

**Comment by nhnb** [comment]
Please see [ChatOptionsEvent](https://github.com/arianne/stendhal/blob/f8819460dbdca2278f8d97230cb94a48b74acecf/srcjs/stendhal/event/ChatOptionsEvent.ts#L20).

**Comment by AntumDeluge** [comment]
We may need to handle "buy ..." & "sell ..." a little different.

![image](https://github.com/arianne/stendhal/assets/3631473/6a0c774f-b502-4dcb-bf7c-ff520cb92158)
