### ISSUE TITLE
Hackim Easso traps me forever

### ISSUE THREAD

**Issue by ToBeFree** [arianne/stendhal#61]
Help! Let me out! Did this never happen to anyone over all the years? Hackim Essao is holding me hostage! 😨 

![stendhal-2017 10 28-22 33 50](https://user-images.githubusercontent.com/1029811/32138285-499951f0-bc30-11e7-93ca-eb5307ff5335.png)

**Comment by AntumDeluge** [comment]
Can NPCs be pushed? I forgot & am not at a computer at the moment. I don't think they can.

**Comment by ToBeFree** [comment]
can't be pushed. :)

**Comment by ToBeFree** [comment]
❤️
