### ISSUE TITLE
Clean up top level directory

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#628]
## 💡 Describe your idea

We should try to keep as few files and directories as possible in the top level directory.

## 🔬 Motivation
 
Sites like Github and Codeberg display a directory listing above the README.md file.

## 🔭 Additional information

Items need to stay at top level:
- .github
- .classpath
- app
- buildtools
- data
- doc
- libs
- src
- tests
- .gitignore
- .project
- .settings
- LICENSE.txt
- README.md
- build.ant.properties
- build.xml
- package.json

Items that should not be in git:
- [x] build-archive _(a03170bee13b81d01b384943e11f4564da6e4f6d)_
- [x] log _(5c0353adee0edad80bd5d524b0c8f6966013bfb4)_
- [x] package-lock.json (with the exception of typescript-doc, there are no dependencies in there)

Items that could be moved:
- [x] android  ➡️  app/android _(5bfc8a762a6ecae19b2d8266a8c201ac7301bb3e)_
- [ ] srcjs  ➡️  app/web ❓   ➡️  src/js (like marauroa) ❓ _(#670)_
- [x] tiled  ➡️  data/... ❓ (there is some code that treats distribution different from project, but I don't know the details) _(#669)_
- [x] change Eclipse's build directory from `bin` (changed to `build/eclipse`) _(144a0e8d1a971772153c00a465b3d9d294b15408)_
- [x] move top-level scripts to `bin` directory: _(fd449cd2c957f45962f93cd1928d12cba25dd5bd & 7432652e66109a8172e3e1a5a36926b3385a295e)_
    - comtest.sh  ➡️  bin ❓
    - runBalanceRPGame.sh  ➡️  bin ❓
    - runpte.bat  ➡️  bin ❓
    - runpte.sh  ➡️  bin ❓
    - runserver.bat  ➡️  bin ❓
    - runserver.sh  ➡️  bin ❓
    - runtest.sh  ➡️  bin ❓
    - wordlist.bat  ➡️  bin ❓
    - wordlist.sh  ➡️  bin ❓

**Comment by AntumDeluge** [comment]
A Marauroa PR is open that will allow us to move `srcjs` directory to `src/js` ( https://github.com/arianne/marauroa/pull/26 ). When it is applied & Marauroa is updated I will merge #670.
