### ISSUE TITLE
Make CollisionAction.REVERSE or .REROUTE the default for NPCs

### ISSUE THREAD

**Issue by ToBeFree** [arianne/stendhal#63]
(server; enhancement / feature suggestion. Not a bug report because the only known issue with the current behavior has been fixed specifically in #61 )

The current default behavior has potential to trap players in corners or to block their path, because the NPC can not be pushed.

Note that when changing the default to "REVERSE", NPCs running in large circles might become less predictable and harder to find. I like the idea of "REROUTE" realistically making an NPC find a way around the obstruction without changing the general path.

**Comment by ToBeFree** [comment]
There is one possible problem when two NPCs that are moving in opposite directions hit each other on their way. At least sheeps behave weirdly in that case:

📗📗📗📗📗📗📗📗📗📗📗 
📗📗📗📗 🐑  🐑  📗📗📗
📗📗📗📗📗📗📗📗📗📗📗 

Left sheep wants to get to the right,
right sheep wants to get to the left.

- collision
- sheep 1 moves up, sheep 2 moves up
- collision
- sheep 1 moves down, sheep 2 moves down
- repeat

**Comment by AntumDeluge** [comment]
I think this might be a good idea. But I'll wait from input from other developers.

Does REROUTE work with NPCs that use a static path?

**Comment by ToBeFree** [comment]
I did not try REROUTE, I just assumed from its name that it would do what I thought. :D

**Comment by ToBeFree** [comment]
```
	/**
	 * Plan a new path to the old destination.
	 */
	public void reroute() {
		if (getPath().isLoop()) {
			// If entity cannot be rerouted use reversePath
			reversePath();
		} else if (hasPath()) {
			Node node = guide.path.getDestination();
			final List<Node> path = Path.searchPath(this, node.getX(), node.getY());

			if (path.size() >= 1) {
				setPath(new FixedPath(path, false));
			} else {
				/*
				 * It can happen that some other entity goes to occupy the
				 * target position after the path has been planned. Just
				 * stop if that happens and we are next to the goal.
				 */
				clearPath();
				stop();
			}
		}
	}
```

https://github.com/arianne/stendhal/blob/889f224cfe0e014469a9b02557bdbaf917cdfb2d/src/games/stendhal/server/entity/GuidedEntity.java#L256

**Comment by ToBeFree** [comment]
Already being used by player path finder:

`
@Override
	protected void handleObjectCollision() {
		if (hasPath()) {
			reroute();
		}
	}
`

https://github.com/arianne/stendhal/blob/7eef9028539f5060f1ba090a7c25484ec969bf6e/src/games/stendhal/server/entity/player/Player.java

**Comment by ToBeFree** [comment]
Note how it does a REVERSE when it can't find a new route. Very nice!

**Comment by AntumDeluge** [comment]
So actually, for NPCs using a static path, REROUTE is the same as REVERSE.

**Comment by AntumDeluge** [comment]
Default NPC behaviour is not *CollisionAction.REVERSE*: c62c0ee
