### ISSUE TITLE
Strange font on chat input

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#630]
## 🐞 Describe the bug

The test client uses a strange font for the chat input, which has very wide spaces and serifs on characters.

![image](https://github.com/arianne/stendhal/assets/364184/6be9a0dd-b112-4417-85e9-090dffe8e2ba)

## 🔥 How to reproduce

1. Use testclient
2. Write something into the chat input field

## 🌍  Environment

- Web client

**Comment by AntumDeluge** [comment]
This is probably related to the fonts used in 732ec163e272d2ccd57f6a3487f1535150dea5aa. Firefox mobile browser is affected. Mobile Android Chrome, Edge, Samsung Internet, and WebView look normal. I have not checked desktop browsers.
