### ISSUE TITLE
Hands are not showed

### ISSUE THREAD

**Issue by eMKejTestingWarriors** [arianne/stendhal#633]
## 🐞 Describe the bug

There are two types of clothing selecting which causes the hands do not appear.

## 🔥 How to reproduce

1. Log in to Stendhal.
2. Click on your hero with RMB.
3. Choose option "Set outfit".
4. Change clothes for one from screens.

## 🌍  Environment

- Java client
- Web client

<img width="278" alt="Zrzut ekranu 2024-01-10 200204" src="https://github.com/arianne/stendhal/assets/149269748/90f4d8b5-4125-486d-9639-e9ae4a6bfdeb">
<img width="204" alt="Zrzut ekranu 2024-01-10 200338" src="https://github.com/arianne/stendhal/assets/149269748/43da65ef-0fb1-4f8a-b7f1-b64db5d2126a">
<img width="209" alt="Ubranie w którym się nie renderują ręce" src="https://github.com/arianne/stendhal/assets/149269748/ffbae442-918e-458d-85a0-8a8fdd9017c9">

**Comment by AntumDeluge** [comment]
Thank you for the report.
