### ISSUE TITLE
Options panel - sliders leave streaks

### ISSUE THREAD

**Issue by eMKejTestingWarriors** [arianne/stendhal#634]
## 🐞 Describe the bug

In option panel, when you grab and move slider, streaks are visible until you free button. 

## 🔥 How to reproduce

1. Click "Menu" button.
2. Click "Settings" button from menu panel.
3. Click "Sounds" button.
4. Grab any slider.
5. Move it right and left (do not free button).

## 🌍  Environment

- Java client
- Windows

## 🔭 Additional information

The same problem appears when you try to rotate your character in "Change outfit" panel.

<img width="364" alt="Suwaki źle działają" src="https://github.com/arianne/stendhal/assets/149269748/8541fa83-d126-4bbd-bcaf-971078b5e89d"><img width="265" alt="image" src="https://github.com/arianne/stendhal/assets/149269748/7568e826-25b7-4435-bb17-9beb56e3bc45">

**Comment by AntumDeluge** [comment]
May be related to #636.

**Comment by AntumDeluge** [comment]
This is likely related to the system graphics card/drivers. As it likely isn't related to the Java client & the Java client is being outmoded it probably won't receive any fix.
