### ISSUE TITLE
Drop-down menus in settings panel are hidding in the wrong way.

### ISSUE THREAD

**Issue by eMKejTestingWarriors** [arianne/stendhal#636]
## 🐞 Describe the bug

When you use drop-down menu in settings panel after using elements located below, a thin line stay in the place where the menu was displayed.

## 🔥 How to reproduce

1. Go to sounds settings panel.
2. Move one of three first sliders right and left.
3. Click "Sound device" button.
4. Click the button again to hide options list.

## 🌍  Environment

- Java client
- Windows 11

## 🔭 Additional information

<img width="264" alt="Złe zamazywanie w settings" src="https://github.com/arianne/stendhal/assets/149269748/8c7c42c6-2ed1-43ae-8ce9-0128c9b1714d">

**Comment by AntumDeluge** [comment]
This is likely a Java issue. I don't have Windows 11, so I can't reproduce it. Does the issue persist if you change to a difference Java version?

**Comment by kiheru** [comment]
My guess would be a driver issue. Sometimes graphics issues pop up that can not be reproduced on any other system, and usually they disappear after some system or driver update. I would like to hear from other Windows 11 users though.

**Comment by AntumDeluge** [comment]
Appears to be the same issue as #634
