### ISSUE TITLE
Add contributor and license page/dialog

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#651]
## 💡 Describe your idea

The webclient should have a dialog or page to show contributors and license. 

## 🔬 Motivation
 
The classic clients does have those as files.

**Comment by AntumDeluge** [comment]
It appears this is complete with ead049dd8ca3c0117864b7e185a3e807699da3b5, so I will close. Re-open or let me know if there is still work to be done with it.

**Comment by nhnb** [comment]
That commit only adds a license display

**Comment by AntumDeluge** [comment]
Okay, I thought it linked to contributors page.

**Comment by AntumDeluge** [comment]
![image](https://github.com/arianne/stendhal/assets/3631473/7529de12-1968-4368-8a55-46594a1e38b6)
