### ISSUE TITLE
Horizontal Rule/Divider for Months on Chat Page

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#66]
Could we add a horizontal rule to separate months on the [website chat page](https://stendhalgame.org/chat)? I sometimes get confused at the end of the month when there are a lot of entries & end up selecting the wrong dates, especially on my small touchscreen device.

I attempted to do this myself, but I don't have it set up correctly locally to test it.

**Comment by nhnb** [comment]
Hello @AntumDeluge,

I vertically aligned the month names to the top of the row. Please check whether this is a solution for the issue,

**Comment by AntumDeluge** [comment]
That is definitely better.

![tmp_15207-screenshot_20180304-1148241383772829](https://user-images.githubusercontent.com/3631473/36949897-20c8f32e-1fe6-11e8-88da-0efbea3eca6f.png)
