### ISSUE TITLE
Create reproducable Android builds for f-droid

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#661]
## 💡 Describe your idea

We should work on release the android client on f-droid.

Important Requirement: F-Droid needs to publish our version and not build it themselves. This is possible, if they can produce an identical build (except for the signature)

**Comment by AntumDeluge** [comment]
As far as I am aware, this is already the case using the default parameters: `./gradlew assembleRelease` from the "app/android" directory or `ant android -Dandroid.build="assembleRelease"` from root directory.

**Comment by AntumDeluge** [comment]
The meta data I have been working on is found here:

- https://github.com/AntumDeluge/fdroiddata/blob/org.stendhalgame.client/metadata/org.stendhalgame.client.yml
- https://gitlab.com/AntumDeluge/fdroiddata/-/blob/org.stendhalgame.client/metadata/org.stendhalgame.client.yml?ref_type=heads

@nhnb I invited you as a contributor to https://github.com/AntumDeluge/fdroiddata in case you want to make any changes yourself. Currently my APK signing key is listed as allowed because the linter requires it to be present. But you will probably want to use yours.

**Comment by AntumDeluge** [comment]
Not sure what is wrong, but F-Droid's integrity check is still failing even after adding the correct signing key fingerprint:

```
ERROR: APK Signature Scheme v2 signer #1: APK integrity check failed. CHUNKED_SHA256 digest mismatch. Expected: <7cb2dceb3bd1ab6cc461b2ea64be18a5f0df65c34240071c3a74d533c6c2003d>, actual: <2d368198faf84ebf801584eca2208215c5ae8501f89436737a57d589e37dfb86>
2024-03-10 03:59:31,188 ERROR: 
/tmp/tmpsoj51d26/sigcp_org.stendhalgame.client_1045005.apk: 
2024-03-10 03:59:31,188 INFO: ...NOT verified - /tmp/tmpsoj51d26/sigcp_org.stendhalgame.client_1045005.apk
2024-03-10 03:59:31,414 DEBUG: > diff -r /tmp/tmpsoj51d26/tmp_binaries_org.stendhalgame.client_1045005.binary /tmp/tmpsoj51d26/_tmp_tmpsoj51d26_sigcp_org.stendhalgame.client_1045005
2024-03-10 03:59:31,619 WARNING: Keeping failed build "tmp/org.stendhalgame.client_1045005.apk"
2024-03-10 03:59:31,619 DEBUG: removing tmp/binaries/org.stendhalgame.client_1045005.binary.apk
2024-03-10 03:59:31,648 ERROR: Could not build app org.stendhalgame.client: compared built binary to supplied reference binary but failed
==== detail begin ====
verification of APK with copied signature failed
Comparing reference APK to APK with copied signature...
Unexpected diff output:
Binary files /tmp/tmpsoj51d26/tmp_binaries_org.stendhalgame.client_1045005.binary/content/classes.dex and /tmp/tmpsoj51d26/_tmp_tmpsoj51d26_sigcp_org.stendhalgame.client_1045005/content/classes.dex differ
```

**Comment by AntumDeluge** [comment]
Opened forum thread here: https://forum.f-droid.org/t/apk-signature-scheme-v2-signer-1-apk-integrity-check-failed/25601/3

**Comment by AntumDeluge** [comment]
I got the build to work ( https://gitlab.com/AntumDeluge/fdroiddata/-/jobs/6376196890 ). The problem was that the default Java version on the GitLab runner is 11, while our apk is built with version 17.

**Comment by AntumDeluge** [comment]
Failing again: https://gitlab.com/AntumDeluge/fdroiddata/-/jobs/6379592983 :unamused:

**Comment by AntumDeluge** [comment]
Nevermind. [Success!](https://gitlab.com/AntumDeluge/fdroiddata/-/jobs/6379722207) I guess I had to wait a little longer for apk to be rebuilt.

After 1.46 release I will create a merge request to have our apk added to F-Droid's repository.
