### ISSUE TITLE
Elder ogre redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#68]
Elder ogre redone using TEMPLATE fat light.png from 24x32 characters pack extended by diamonddmgirl and hair_036.png from stendhal repository.
![reogre](https://user-images.githubusercontent.com/37004874/36926945-6cdc4012-1e48-11e8-9c71-0d886fed343b.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 8dd1077
