### ISSUE TITLE
Admin: /alter Command Doesn't Update Entity Name

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#680]
## 🐞 Describe the bug

After using the `/alter` or `/altercreature` command to change a creature's name, player must exit map & re-enter for name to be updated.

This is a low-priority bug as the command is only useful to administrators.

To reproduce:
- right-click any creature as admin & select "(*) Alter"
- set entity's name to new value (`/alter #<num> name set <new_name>`)
- note that entity's visible name does not update
- exit map & return to update

Note that `/alter #<num> title set <new_title>` _does_ immediately update visible name.

**Comment by nhnb** [comment]
The server should prevent admins from changing the name of entities because it is extremely likely that admins do not understand the consequences.

**Comment by AntumDeluge** [comment]
Updated scripts so admins cannot change name attribute.
