### ISSUE TITLE
Elf wizard redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#69]
Elf wizard redone using Flower-01.png, Mage-M-01 light.png, and Townfolk-Old-M-002 light.png from 24x32 characters pack extended by diamonddmgirl and ears_long-light.png from cabbit-bases-collection by deluge.
![relfwiz](https://user-images.githubusercontent.com/37004874/36927094-46dff9ac-1e49-11e8-8c56-35e2584b2774.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: b9f8f88
