### ISSUE TITLE
Imperial scientist redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#70]
Imperial scientist redone using Cultist-01.png and Mask-M-01 light.png from 24x32 characters pack extended by diamonddmgirl and similar to old colors.
![rimpsci](https://user-images.githubusercontent.com/37004874/36928425-df5a0a42-1e53-11e8-98fd-26f50d8affbb.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 4c6c5dc

**Comment by AntumDeluge** [comment]
Thank you so much @olonu!

**Comment by AntumDeluge** [comment]
I used your SourceForge email address, onu@users.sourceforge.net, to create most of those commits with your edits. If you add that email address to your GitHub account the commits I made will be attributed to you & link back to your GitHub profiles. The first two or three I didn't think to use your SF email address, so they won't link to you. Sorry.
