### ISSUE TITLE
Dark mutant redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#72]
Dark mutant(blacky.png) redone using Mask-M-01 light.png and TEMPLATE thin light.png from 24x32 characters pack extended by diamonddmgirl,horns redone from dark soldier rework(chaos soldiers in stendhal repository), and similar to old colors.
-Old dark mutant had a scepter/trident/pitchfork/etc.
![rblacky](https://user-images.githubusercontent.com/37004874/36944902-142c7b22-1f73-11e8-9802-06f86921173c.png)

**Comment by AntumDeluge** [comment]
Looks good @olonu, I'll get this added as soon as I can.

**Comment by AntumDeluge** [comment]
Committed to master branch: 0044e6a
