### ISSUE TITLE
Aura concept

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#73]
Use shield sprite. https://opengameart.org/content/shield-sprite
Fill in colors. 
![shieldex](https://user-images.githubusercontent.com/37004874/36945105-ec57604a-1f76-11e8-9e16-c97be685c844.png)
Package of auras before reducing size.
Reduce size.
![shieldex1](https://user-images.githubusercontent.com/37004874/36945109-f851da60-1f76-11e8-992f-4b977237edf3.png)
Now you have package of auras for cabbit sprites.  Two possible examples follow.
![shieldex5](https://user-images.githubusercontent.com/37004874/36945119-152c1e0c-1f77-11e8-8752-3b5734046b08.png)
![shieldex6](https://user-images.githubusercontent.com/37004874/36945120-16d01d44-1f77-11e8-8306-e7a26e898f87.png)
I'm not sure this would work, but there are no auras available right now.

**Comment by AntumDeluge** [comment]
I wonder if we could render auras independent of sprites. So they aren't actually part of them like they were before.

**Comment by olonu** [comment]
I think we're going with the discharges for the time being, especially since there is so much similarity to the old sprites auras/discharges.  Plus, it almost guarantees you can still see some sprite instead of blocking it from view.  Vampire lord's aura is different enough from this concept that this doesn't really point into that.  This might work later in some sort of orby effect.  Closing.

**Comment by olonu** [comment]
Closing this has no effect on rendering auras independent of sprites.  That still sounds good.

**Comment by AntumDeluge** [comment]
Might even be able to use semi-transparency so sprites aren't blocked out. But that would increase load for slower computers. May have to use a workaround when transparency is disabled in the client.
