### ISSUE TITLE
Imperial experiment redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#74]
Imperial experiment redone using helmet from Zombies and Skeletons(https://opengameart.org/content/zombies-skeletons)(CC0)(artisticdude), Zombie and Skeleton 32x48(https://opengameart.org/content/zombie-and-skeleton-32x48)(CC0)(Reemax), and similar colors to old.
![rimpexp](https://user-images.githubusercontent.com/37004874/36961260-7dc3f646-2018-11e8-8f34-180487bd6bc8.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 69d14a4

Very nice!
