### ISSUE TITLE
Sheepman frame [4,2] residue...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#75]
Sheepman frame [4,2] has some sort of residue issue from editing in front of the nose.  I thought that it was worse than it was when I initially saw it, but it was some pixels.  It's corrected better.
![rsheepman2](https://user-images.githubusercontent.com/37004874/36992419-dcb016de-2078-11e8-9ed5-0da56536189a.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 8876def

Thank you.
