### ISSUE TITLE
Imperial demon redone no wings/wings/aurawings using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#78]
Imperial demon without wings redone using Mask-M-01 light.png and TEMPLATE thin light.png from 24x32 characters pack extended by diamonddmgirl and similar to old colors.
![rimpdnow](https://user-images.githubusercontent.com/37004874/37077445-079675ce-21a9-11e8-90a3-487143996526.png)

Imperial demon with wings redone using Mask-M-01 light.png and TEMPLATE thin light.png from 24x32 characters pack extended by diamonddmgirl, fallen_angel-001-48x64.xcf wings, and similar to old colors.
![rimpdwi](https://user-images.githubusercontent.com/37004874/37077547-6dbcf2ce-21a9-11e8-887b-4a7452c6da9f.png)

Imperial demon with wings and aura redone using Mask-M-01 light.png and TEMPLATE thin light.png from 24x32 characters pack extended by diamonddmgirl, fallen_angel-001-48x64.xcf wings, similar to old colors, and Electrical disintegration animation(https://opengameart.org/content/electrical-disintegration-animation)(superjoe)(CC0).
![rimpwiau](https://user-images.githubusercontent.com/37004874/37077640-cbfdf6bc-21a9-11e8-9ff2-ed70e7a3b189.png)

**Comment by olonu** [comment]
Include horns from dark soldier rework also in list of stuff in use.

**Comment by olonu** [comment]
The all encompassing aura/discharges may not be the best choice as it hides the sprite a lot.  As such, here is a reduced aura/discharge more similar to the old sprite's aura/discharge.  Playing around with the original Electrical disintegration animation may produce a better more believable aura/discharge later.  This disintegration animation is probably as close as you're going to find to the original sprites' discharges without drawing your own.
![rimpdaure](https://user-images.githubusercontent.com/37004874/37110147-14fa3582-220a-11e8-9cee-962b81d078b2.png)

**Comment by olonu** [comment]
I'm ok on edits.  All I'm saying is we don't want it looking like the monsters have the paralysis status sprite from chaos sorcerer, which is more uniform.  It has its discharges now.  If you want to change the discharges in the reduced form for other sprites, it's mostly based on disintegrate07.png.  If you want the discharges for the overlay for this sprite, they follow below.
Discharge 1
![disaur1](https://user-images.githubusercontent.com/37004874/37134085-b535b2ec-2264-11e8-82ae-50d6c15a2c32.png)
Discharge 2
![disaur2](https://user-images.githubusercontent.com/37004874/37134089-baf0bc2c-2264-11e8-820a-05c35a889e32.png)
Discharge 3
![disaur3](https://user-images.githubusercontent.com/37004874/37134094-bdf6cdda-2264-11e8-8a78-6ef6d2915bb4.png)
Discharge 4
![disaur4](https://user-images.githubusercontent.com/37004874/37134096-bf0afc78-2264-11e8-80f0-96f9ebe61897.png)
[(2,3,4,1),(3,4,1,2),(4,1,2,3),(1,2,3,4)], column 4 gets "chopped" to sort of create a "randomness".
These may need a little correcting for gray specks still.  I think the combined sprite is mostly corrected.

**Comment by AntumDeluge** [comment]
Thank you @olonu. Much appreciated.
