### ISSUE TITLE
Elite sheepman redone using... 

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#79]
Elite sheepman redone using sheepman from stendhal repository, similar to old colors, and the snail shell from batch_one_0.png(Redshrike)(https://opengameart.org/content/a-load-of-overworld-34-rpg-sprites).
![rsheepeli](https://user-images.githubusercontent.com/37004874/37134946-d7935b24-2268-11e8-97f9-d58ab3ab2420.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: a823df7

Nice idea using the snail shell.

**Comment by AntumDeluge** [comment]
I have also submitted the sheepmen sprites to OpenGameArt.org: https://opengameart.org/node/81800
