### ISSUE TITLE
Armored sheepman redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#80]
First, there is a 2 pixel correction to row 1 frame 3 for regular sheepman around the pants left arm area.
![rsheepman3](https://user-images.githubusercontent.com/37004874/37185528-d15b77b8-230e-11e8-96e4-8faceb3b918a.png)
Armored sheepman redone using sheepman sprite, similar to old colors, and Sword and shield (16x16)(https://opengameart.org/content/sword-and-shield-16x16)(qubodup)(CC0).
![rsheeparm](https://user-images.githubusercontent.com/37004874/37185563-eeb7cb90-230e-11e8-827a-95bd1dd4f291.png)

**Comment by olonu** [comment]
Sheepman elite is fine in regards to the 2 pixel error on regular sheepman.  It was corrected while doing the pants.

**Comment by olonu** [comment]
Frame 3 row 1 armored sheepman needed shield shifted right 1.  Shield has been shifted and adjusted.
![rsheeparm1](https://user-images.githubusercontent.com/37004874/37187979-e966961a-231a-11e8-8f84-601176bc4c65.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: c53833e & bd0ab7f

Thank you @olonu.
It's interesting that you used that shield. I was actually looking it at the same one today to use for the [kobold sprites](https://opengameart.org/node/81952). But, I ended up going with a [different one](https://opengameart.org/node/64857).
