### ISSUE TITLE
Oni concept

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#81]
A lot of our monsters are types of demons.  When you do a search on google you find demons; however, no one wants a game like this full of demon demons plus it'd be boring.  Kobold brings up your traditional demons, but our kobolds were more cutesy than demon and are now doggy/cutesy.  Oni brings up Japanese demons, but our oni were purple "foreigners" with long chins.  This style I suspect is part of the copyright sprite.  It can't be copied and taking scalable inspiration from it may lead to something like happened with the apprentice assassin hood.  There are some options.  Draw your own head set.  It'd probably take an artist.  Find another style completely which would probably resemble demon demons more.  Abandon the features and simply make the Cabbit sprites purple.  These two run boredom.  I found a sheet of head sprites that may remedy the situation.
![rpgportraits](https://user-images.githubusercontent.com/37004874/37203362-6a0dc14a-235b-11e8-89ec-81730cb0e5a4.png)
https://opengameart.org/content/rpg-portraits
Observe column 7, the long chinned alien.
By doubling the alien's ears, reorienting the ears, then adding nozzles, you can get...
![roniqueen](https://user-images.githubusercontent.com/37004874/37203418-91442d08-235b-11e8-9cf8-1e81b1c68b35.png)
The head would need cycling around on the base and contrasting.  The nozzles don't have to be long and antennae like, they could be shortened again.
![test](https://user-images.githubusercontent.com/37004874/37203762-c86775fa-235c-11e8-814c-fef3b948144a.png)

**Comment by AntumDeluge** [comment]
I think that looks perfect.

**Comment by AntumDeluge** [comment]
Closing. Moved on from "concept" to "production". See #83.
