### ISSUE TITLE
Archmage elf redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#82]
Archmage elf redone using ears_long-light.png from the cabbit-bases-collection, Princess-01 light.png from 24x32 characters pack extended by diamonddmgirl, and similar to old colors.
![rarchmage](https://user-images.githubusercontent.com/37004874/37268518-cc1a9186-259c-11e8-8705-9cd4acaa481d.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 76833fe
