### ISSUE TITLE
Oni queen redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#83]
First, this is the oni head cycled using RPG portraits column 7.  This can now be reused on other oni.
![ronihead](https://user-images.githubusercontent.com/37004874/37305150-f06973d2-2609-11e8-8b97-b05e9a288c84.png)
Oni queen redone using Queen_01 light.png from 24x32 characters pack extended by diamonddmgirl, similar to old colors, and RPG portraits column 7(https://opengameart.org/content/rpg-portraits)(Buch)(CC0).
![roniqueen](https://user-images.githubusercontent.com/37004874/37305176-038c004c-260a-11e8-845f-b52d94b8e737.png)

**Comment by olonu** [comment]
Fourth row had a small disagreement with second around cloak back head area.
![roniqueen1](https://user-images.githubusercontent.com/37004874/37305663-987395d4-260b-11e8-9414-69ccdf386d17.png)

**Comment by AntumDeluge** [comment]
- Oni queen committed to master branch: 694bb88
- Created oni source for GIMP with your "head cycled" image: 071f576

Also, there are a couple things I wanted to point out to you in case they weren't intentional:
1. Frame 3,2 (south-facing center): There are black pixels above the ear that are not in frames 3,1 & 3,3. I removed these in the GIMP source file that I created. But did not update the PNG image. I wanted to let you know first.
2. Frames 1,3; 2,3; & 3,1: The outfit sleeve seems to be covering the oni's arm.

**Comment by AntumDeluge** [comment]
That last commit I just made (76809d7) isn't related to your oni queen sprite. I had just messed up with the crown in the GIMP source file that I created.

**Comment by olonu** [comment]
I think issue 1 corrected.  Ya, that was an error, probably from aligning against the queen head or a base head with the oni head.  I used bucket fill outside the image with a random color and found them too.
![roniqueen2](https://user-images.githubusercontent.com/37004874/37387152-bc12c114-2731-11e8-8a90-7a8a4face6f6.png)
The second issue is I think inherent to the queen sprite itself in at least two of the frames.  I thought about making hands as I was putting the thing together, but in order to conform thought it'd be better to agree with the queen sprite.  Some dresses can have stuff like this occur.  I don't really know here.
![queen_01 lightchaconv](https://user-images.githubusercontent.com/37004874/37387480-ec5d52d4-2732-11e8-8279-26f492e35741.png)
![queen_01 light](https://user-images.githubusercontent.com/37004874/37387482-ef8d689a-2732-11e8-892d-b05c25edf26b.png)
It's not a charas conversion artifact.

**Comment by AntumDeluge** [comment]
Ah, okay. You are right about the dress.

**Comment by olonu** [comment]
If someone wants to do an oni, they can use the cycled head for the other 3 sprites.  I'm not sure I'll finish the whole set.  I think the most difficult part will be fitting a hat to them with aligning weapons next.

**Comment by AntumDeluge** [comment]
Okay. I had reserved all the oni sprites for you on the wiki page. But I will undo that.
