### ISSUE TITLE
Elder sheepman redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#84]
Elder sheepman redone using current sheepman from stendhal repository, snail shell from batch_one_0.png(A load of overworld 3/4 RPG sprites)(Redshrike)(https://opengameart.org/content/a-load-of-overworld-34-rpg-sprites), tassle from row 2 frame 2 dark-soldier-lord.png dark soldier rework, and similar to old colors.
![rsheepeld](https://user-images.githubusercontent.com/37004874/37320989-c4482742-264c-11e8-8f48-94e07ff6afa7.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 57c4859

**Comment by olonu** [comment]
That's fine.
