### ISSUE TITLE
Oni king redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#85]
Oni king redone using King_01 light.png from 24x32 characters pack extended by diamonddmgirl,similar to old colors, RPG portraits column 7(https://opengameart.org/content/rpg-portraits)(Buch)(CC0), and Shmup Enemies(https://opengameart.org/content/shmup-enemies)(Buch)(CC0).
![roniking](https://user-images.githubusercontent.com/37004874/37336811-e2ab4d90-2688-11e8-841e-8b1e915780b1.png)

**Comment by olonu** [comment]
Little bit of consistent eye color disagreement between this and other oni probably due to how I struck the cloak colors together.  Here's revision.
![roniking1](https://user-images.githubusercontent.com/37004874/37337333-4bead892-268a-11e8-8f94-440083b1592a.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: ac469c0

Thank you @olonu for all your hard work.
