### ISSUE TITLE
Ogre soldier redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#86]
Ogre soldier redone using current ogre sprite from stendhal repository, Aristocrat-M-02 light.png hair from 24x32 characters pack extended by diamonddmgirl, 32x32 RPG Character Sprites row 5 from bottom(soldier hat only)(https://opengameart.org/content/32x32-rpg-character-sprites)(Eldiran)(CC0), hand axe [64x64](https://opengameart.org/content/hand-axe-64x64)(LordNeo)(https://opengameart.org/content/hand-axe-64x64)(CC0), and similar to old colors.
![rsoogrewpn](https://user-images.githubusercontent.com/37004874/37391009-53bd15d8-2740-11e8-8ae2-49c80379ada3.png)
In case the axe is way too big, here's ogre soldier without the axe.
![rsoogrenowpn](https://user-images.githubusercontent.com/37004874/37391109-9f18feac-2740-11e8-9fb5-fb2595cd00c6.png)

**Comment by AntumDeluge** [comment]
Axe looks fine to me. :)

**Comment by AntumDeluge** [comment]
Committed to master branch: 199e050
