### ISSUE TITLE
Dagobert redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#87]
Dagobert redone using Townfolk-Adult-M-002 light.png and Townfolk-Adult-M-003 light.png from 24x32 characters pack extended by diamonddmgirl and similar to old colors.
![rdago](https://user-images.githubusercontent.com/37004874/37455385-56de0082-2813-11e8-857f-47afa496e8ce.png)
I caught a slight disagreement in the fourth row that seems to carry through the charas converter.  It may carry through a lot of the sprites.  It seems to be leaving the forward facing shoe planked instead of shaping it in the fourth rows.  Dago has already been placed in agreement.
![townfolk-adult-m-003 light](https://user-images.githubusercontent.com/37004874/37455532-ae843d38-2813-11e8-8ae2-5cdb0921e543.png)

**Comment by olonu** [comment]
It's in a lot of the sprites with shoes.  I'm not seeing a cloak/dress similarity yet.

**Comment by AntumDeluge** [comment]
It's an artifact that occurs from using the scalex/scale2x algorithm. I use it from the command line & in [GIMP](https://www.gimp.org/) as a filter. The same thing often happens for me. Pretty sure the charas converter uses the scale2x algorithm as well.

**Comment by olonu** [comment]
It's in a lot of the sprites.  The worst offender I found in my set was amazon hunter(Fighter 01) where half the shoe was chopped, basically the bottom pixel row.  Imperial leader seems clean.  Imperial experiment is likely ok.  I corrected 21 of my sprites for various flattened issues such as shoes/cloaks/dresses/chopped foot/etc.  It's not a real bad error.  Is it necessary to resubmit?

**Comment by AntumDeluge** [comment]
No, it's not important. :)

Stuff like that can always be touched up later if it is noticeable.

**Comment by AntumDeluge** [comment]
Committed to master branch: 24f53ba
