### ISSUE TITLE
Elf bodyguard redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#88]
Elf bodyguard redone using Fighter-M-02 light.png and Townfolk-Adult-M-005 light.png from 24x32 characters pack extended by diamonddmgirl, ears_long-light.png from cabbit collection, dress_072.png cape only(may need extending later) from stendhal repository, similar to old colors, and [LPC] full plate golden armor(https://opengameart.org/content/lpc-full-plate-golden-armor)(Shaun Williams
(Submitted by VividReality))(CC-BY 3.0).
![relfbg](https://user-images.githubusercontent.com/37004874/37530166-599eecda-290f-11e8-812c-30f568a59faa.png)

**Comment by olonu** [comment]
The shoulder pads on the side views might need adjusting for cabbit sprites

**Comment by olonu** [comment]
Shoulder pad adjustment coming soon.

**Comment by olonu** [comment]
Shoulder pads adjusted.  It may not be 100% on the side sprites, but it's way better than without adjustment.
![relfbg](https://user-images.githubusercontent.com/37004874/37538775-10d46b38-2928-11e8-8ac8-50123ab9a64f.png)

**Comment by olonu** [comment]
Revision already.
![relfbg](https://user-images.githubusercontent.com/37004874/37540260-aea729be-292c-11e8-8dc9-efc42c65c848.png)

**Comment by AntumDeluge** [comment]
Commited to master branch: 39f95bd
