### ISSUE TITLE
Imperial priest redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#89]
Imperial priest redone using Aristocrat-M-02 light.png from 24x32 characters pack extended by diamonddmgirl and holly staff.png from Staff [64 x64](https://opengameart.org/content/staff-64-x64)(LordNeo)(CC0).
![rimppri](https://user-images.githubusercontent.com/37004874/37564624-0e8cc46c-2a70-11e8-9aa6-a66059aed719.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 7f99800

Thank you @olonu.
