### ISSUE TITLE
Josephine redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#90]
Josephine redone using Aristocrate-F-03 dark.png from 24x32 characters pack extended by diamonddmgirl and similar to old colors.
![rjosephi](https://user-images.githubusercontent.com/37004874/37634846-a3787f30-2bce-11e8-891f-784bbcb2fb2a.png)

**Comment by olonu** [comment]
Removed charas conversion error last line.
![rjosephi](https://user-images.githubusercontent.com/37004874/37636110-516586ea-2bd6-11e8-8b1a-a0dec636de6a.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 6f96118
