### ISSUE TITLE
Zak redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#91]
Zak(man_000_npc.png) redone using Townfolk-Adult-M-001 light-0-0.png and Townfolk-Adult-M-003 light-0-0.png from 24x32 characters pack extended by diamonddmgirl.
![rzak](https://user-images.githubusercontent.com/37004874/37763031-60caa8d0-2d94-11e8-8069-156d60f051bc.png)

**Comment by olonu** [comment]
Head border revision to bottom left
![rzak](https://user-images.githubusercontent.com/37004874/37763818-74765da0-2d96-11e8-8991-6bfa1316c5df.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 427b473
