### ISSUE TITLE
Yan redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#92]
Yan redone using Lyuba_char.png from 24x32 heroine Lyuba (sprites, faces, pictures) by Cabbit, base-f-light.png from cabbit-bases-collection, dress_093.png from stendhal repository, and some old coloration.
![ryan](https://user-images.githubusercontent.com/37004874/37768133-ed54d722-2da2-11e8-91b6-47b64a8ed7e1.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: 29a30fc
