### ISSUE TITLE
Oni archer redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#93]
First, here it is without the bow.
![roniarch copy 1](https://user-images.githubusercontent.com/37004874/37818155-90b56132-2e4f-11e8-9201-94d61d806af6.png)
Oni archer redone using TEMPLATE thin light.png from 24x32 bases by cabbit, current dress_005.png from stendhal repository, current oni head, similar to old colors, and FishBow.png from Minecraft Items(https://opengameart.org/content/minecraft-items)(SoCay)(CC0).
![roniarch](https://user-images.githubusercontent.com/37004874/37818127-7338a70e-2e4f-11e8-82f0-a59b51d9a372.png)

**Comment by AntumDeluge** [comment]
Awesome! :)

**Comment by AntumDeluge** [comment]
Committed to master branch: 6f9430d

Thanks for the alternate without bow. I can use that to add it to the GIMP source.
