### ISSUE TITLE
Oni priest redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#94]
Oni priest redone using TEMPLATE thin light.png from cabbit bases, current oni head, current dress_056.png{aka Healer-M-01 light.png dress from 24x32 characters pack extended by diamonddmgirl}, similar to old colors, smaller mushroom from Mushroom (Champignon)(https://opengameart.org/content/mushroom-champignon)(Guyome41)(CC0), and Fidget spinner{small}(https://openclipart.org/detail/283528/fidget-spinner)(rones).
-Found old sprite had a wily, old, and odd staff towards end; may add wily, old, and odd staff later
![roniprie](https://user-images.githubusercontent.com/37004874/37840515-ac997156-2e93-11e8-95a1-b92c551035e8.png)

**Comment by AntumDeluge** [comment]
Once again, amazing work. I love the colors.

I'm going to upload your oni sprites to [OpenGameArt.org](https://opengameart.org/). I'll be sure to attribute the work to you. :)

**Comment by AntumDeluge** [comment]
Do you have the source with layers? It's okay if not.

**Comment by AntumDeluge** [comment]
Commited to master branch: 1e18a86

**Comment by AntumDeluge** [comment]
Do you want me to reserve *oni_warrior* for you?

**Comment by olonu** [comment]
I don't have a source with layers, but I have the recoloration of the fidget spinner.  Surprisingly, this scaled down good from 300x300 pixels.  
![ronprfid](https://user-images.githubusercontent.com/37004874/37854637-1952dd36-2ec2-11e8-826e-4989bdcbcfc8.png)

**Comment by olonu** [comment]
The cap portion can be gotten by clipping the sides on the smaller shroom's head.

**Comment by olonu** [comment]
No, don't reserve oni_warrior yet.  I usually only call for a reservation on something when I've literally got it together.  Recoloring didn't take as long as I thought it might, and I found several tricks along the way to shorten time on recoloring.

**Comment by olonu** [comment]
The biggest thing on oni_warrior is that slack back cap.

**Comment by AntumDeluge** [comment]
Okay, but that means that somebody could reserve it while you are working on it (though, that won't likely happen).

Thanks, I will add these parts to the oni source file.
