### ISSUE TITLE
Dark elf ranger redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#95]
Dark elf ranger redone using ears_long-dark_ash.png from cabbit-bases-collection, Ranger-F-01 light.png from 24x32 characters pack extended, similar to old colors for clothing/eyes, and dark_ash colors for skin.
![rdelfran](https://user-images.githubusercontent.com/37004874/37859098-083ced16-2ee5-11e8-80a3-22b75113b88e.png)

**Comment by olonu** [comment]
small revision
![rdelfran](https://user-images.githubusercontent.com/37004874/37859118-87d5c958-2ee5-11e8-9a21-4b21ada720b6.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: a818477
