### ISSUE TITLE
Elf mage redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#96]
Elf mage redone using base-f-light.png and ears_long-light.png from cabbit-bases-collection, Princess-01 light.png from 24x32 characters pack extended by diamonddmgirl, dress_027.png from stendhal repository, and similar to old colors.
![relfmage](https://user-images.githubusercontent.com/37004874/37860696-6f4bf206-2f01-11e8-86c1-29cee0bc6ef4.png)

**Comment by AntumDeluge** [comment]
Committed to master branch: ce3bf54
