### ISSUE TITLE
Child dark elf redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#97]
Child dark elf redone using elf-m-dark_ash.png from cabbit bases collection, Townfolk-Child-M-001 light.png from 24x32 characters pack extended by diamonddmgirl, and MagicWand 40x41.png from MagicWands(https://opengameart.org/content/magicwands)(ZigWin)(CC0).
![rdelfchild](https://user-images.githubusercontent.com/37004874/37862080-9eb2a49c-2f1d-11e8-925b-db03749dd219.png)

**Comment by AntumDeluge** [comment]
Commited to master branch: 5aa79cb

**Comment by AntumDeluge** [comment]
Just wanted to mention @olonu, you may find a few more Cabbit-style hair & outfits here: https://github.com/AntumDeluge/cabbit-collection/tree/master/art/sprite/outfit

**Comment by AntumDeluge** [comment]
Oh, another note. Not important, but, when you put a link in braces on here, if you put a space before the closing brace, it will link correctly:
   (https://opengameart.org/content/magicwands)(ZigWin)(CC0).
   vs.
   (https://opengameart.org/content/magicwands )(ZigWin)(CC0).
