### ISSUE TITLE
Elf redone using...

### ISSUE THREAD

**Issue by olonu** [arianne/stendhal#99]
Elf redone using TEMPLATE thin light.png, ears_long-light.png, and hair-short-004-black.png from cabbit collection/stendhal repo, Townfolk-Adult-M-002 light.png and Townfolk-Adult-M-005 light.png from 24x32 characters pack extended by diamonddmgirl, and similar to old colors.
![relf](https://user-images.githubusercontent.com/37004874/37873289-b77117b4-2fe7-11e8-859b-3f7e84253139.png)
In addition, I have extracted the shirt from Townfolk-Adult-M-005 light.png for possible use as a double sided vest.
![vest](https://user-images.githubusercontent.com/37004874/37873298-d71919d6-2fe7-11e8-8dd7-2bad47d30200.png)
I also extracted the dress from Townfolk-Adult-M-002 light.png
![townfolk-adult-m-002 light-0-0](https://user-images.githubusercontent.com/37004874/37873303-f1cea0d4-2fe7-11e8-9aa3-2efe76df3e5d.png)
I don't know if they've already been extracted.

**Comment by AntumDeluge** [comment]
Thank you onu. Committed to master branch: bf49a4c
